### ISSUE TITLE
Swagger doesn't show body when using `@foal/typestack`'s ValidateBody with entity

### ISSUE THREAD

**Issue by ByScripts** [FoalTS/foal#1000]
Version of FoalTS: 2.6.0

Hi FoalTS,

I followed [this guide](https://foalts.org/docs/common/validation-and-sanitization#with-a-validation-class-class-validator) to replace AJV validation with `class-validator` + `class-transformer` with my entities.

1. I added annotations to my entity (`@IsInt`, `@Max`...)
2. In my controller, I replaced `@foal/core`'s `ValidateBody(schema)` with `@foal/typestack`'s `ValidateBody(MyEntity)`

But then the body disappeared from Swagger. I'm no longer able to send json body.

When using `@foal/core`'s `ValidateBody(schema)`, the body is here.

**Comment by LoicPoullain** [comment]
Hi @ByScripts 

Foal does not support Swagger generation with TypeStack packages: `class-validator` and `class-transformer`.

The reason why it was easy to integrate this feature with AJV is that we pass directly a JSON schema to `@foal/core`'s `ValidateBody(schema)`.

If you use TypeStack, you will have to define the swagger spec by hand:
```typescript
@ValidateBody(...)
@ApiRequestBody(...)
```

**Comment by ByScripts** [comment]
Ok, I see. Thank you 👍🏻
