### ISSUE TITLE
Allow to pass custom state in OAuth2 providers

### ISSUE THREAD

**Issue by HRK44** [FoalTS/foal#1001]
I need to pass some data in the `state` query param (oauth2), but since it's used for the cookie verification, I can't override it else it always throws a `InvalidStateError`. I'm not using the oauth2 as a way to log in a user, just to "link" an account to a 3rd party using oauth2, so I don't have any user identifier on the callback, that's why I need to pass the user id to the auth method using the `state` param.

**Comment by HRK44** [comment]
I managed to bypass that by adding my custom data in the cookie (as you are doing for the state), not sure if that's the intended way but it works.

**Comment by LoicPoullain** [comment]
> I need to pass some data in the `state` query param (oauth2), but since it's used for the cookie verification, I can't override it else it always throws a `InvalidStateError`. I'm not using the oauth2 as a way to log in a user, just to "link" an account to a 3rd party using oauth2, so I don't have any user identifier on the callback, that's why I need to pass the user id to the auth method using the `state` param.

Yes, the `state` parameter is a reserved keyword that is used to add protection against CSRF attacks. It follows the OAuth2.0 specification and is implemented in the same way as in other frameworks such as Laravel. Its value shouldn't be changed/overridden and its management must be left to the framework.

> I managed to bypass that by adding my custom data in the cookie (as you are doing for the state), not sure if that's the intended way but it works.

In you case, yes I think this would be the best option: save the data in a cookie and retrieve it after the user has been redirected. But this cookie must not be the one used to save the `state` random value generated by the framework (whose name is `oauth2-state`). This must be another cookie whose name is left to your choice.
