### ISSUE TITLE
Angular Universal foalts

### ISSUE THREAD

**Issue by jonfrusciante** [FoalTS/foal#1002]
Hi...compliments for the great work.
Is possibile to integrate angular Universal ???

**Comment by kingdun3284** [comment]
> Hi...compliments for the great work. Is possibile to integrate angular Universal ???
Of course it's possible. Basically foalts uses express underhood. All you need is a middleware to filter frontend request to angular's render function.

**Comment by jonfrusciante** [comment]
@kingdun3284  Could you give me an example??

 I'd really appreciate it.

**Comment by kingdun3284** [comment]
> @kingdun3284 Could you give me an example??
> 
> I'd really appreciate it.

Read the readme first: https://www.npmjs.com/package/@nguniversal/express-engine
And read this https://foalts.org/docs/upgrade-to-v2/custom-express-instance/ as well.

**Comment by LoicPoullain** [comment]
Looks like this issue has been answered. I'm closing it 👍
