### ISSUE TITLE
Running npm run makemigrations throws 'Cannot find module '@entity''

### ISSUE THREAD

**Issue by HRK44** [FoalTS/foal#1006]
Version of FoalTS: 2.6.0

When I try to run the `npm run makemigrations` command, if I have some imports in my entities that use the `@entity` it throws this error:

> Error during migration generation:
> Error: Cannot find module '@entity'

This is the `makemigrations` command (should be the default one) : `foal rmdir build && tsc -p tsconfig.app.json && npx typeorm migration:generate --name migration && tsc -p tsconfig.app.json`

and this is my `tsconfig.app.json` :

```
{
    "extends": "./tsconfig.json",
    "include": [
        "src/**/*.ts"
    ],
    "exclude": [
        "src/e2e/*.ts",
        "src/**/*.spec.ts",
        "src/e2e.ts",
        "src/test.ts"
    ]
}
```

`tsconfig.json`:

```
{
    "compilerOptions": {
        "module": "commonjs",
        "sourceMap": true,                              /* Generates corresponding '.map' file. */
        "outDir": "build",                              /* Redirect output structure to the directory. */
        "strict": true,                                 /* Enable all strict type-checking options. */
        "strictPropertyInitialization": false,          /* Enable strict checking of property initialization in classes. */
        "moduleResolution": "node",                     /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
        "esModuleInterop": true,                        /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
        "experimentalDecorators": true,                 /* Enables experimental support for ES7 decorators. */
        "emitDecoratorMetadata": true,                  /* Enables experimental support for emitting type metadata for decorators. */
        "skipLibCheck": true,                           /* Skip type checking of declaration files. */
        "forceConsistentCasingInFileNames": true,       /* Disallow inconsistently-cased references to the same file. */
        "noImplicitAny": false,
        "target": "ES2021",
        "resolveJsonModule": true,
        "rootDir": "src",
        "lib": [
            "ES2021"
        ],
        "baseUrl": "src",
        "paths": {
            "@lib": ["lib"],
            "@entity": ["app/entities"],
            "@service": ["app/services"],
            "@interface": ["app/interfaces"],
            "@hook": ["app/hooks"],
            "@middleware": ["app/middleware"]
        }
    },
    "include": [
        "src/**/*.ts",
        "ormconfig.js",
        "config/*.js"
    ]
}
```

and `package.json` :

```
    "_moduleAliases": {
        "@service": "build/app/services",
        "@entity": "build/app/entities",
        "@interface": "build/app/interfaces",
        "@hook": "build/app/hooks",
        "@middleware": "build/app/middleware",
        "@lib": "build/lib",
        "@dbconfig": "build/ormconfig.js"
    },
```

It works fine if I import using `from './'` but I want to know why it's not working with `import { ... } from '@entity'`

**Comment by LoicPoullain** [comment]
Hi @HRK44 👋 

Did you solve your problem? Do you still need help on this issue?

**Comment by HRK44** [comment]
@LoicPoullain problem is still there, I'm just using relative paths in the entity files when importing other entities (instead of `@entity`). So I guess this issue is still valid, unless there's a solution for that

**Comment by LoicPoullain** [comment]
Thank you for your reply.

Do you use a special library to manage module aliases in your application ?

**Comment by HRK44** [comment]
I'm using `"module-alias": "^2.2.2"`.

Have this in my tsconfig :
```
        "paths": {
            "@lib": ["lib"],
            "@enum": ["app/enums"],
            "@platform": ["app/platforms"],
            "@entity": ["app/entities"],
            "@service": ["app/services"],
            "@interface": ["app/interfaces"],
            "@hook": ["app/hooks"],
            "@middleware": ["app/middleware"],
            "@providers": ["app/providers"]
        }
```

and this in my package.json :
```
    "_moduleAliases": {
        "@service": "build/app/services",
        "@enum": "build/app/enums",
        "@platform": "build/app/platforms",
        "@entity": "build/app/entities",
        "@interface": "build/app/interfaces",
        "@hook": "build/app/hooks",
        "@middleware": "build/app/middleware",
        "@lib": "build/lib",
        "@dbconfig": "build/ormconfig.js",
        "@providers": "build/app/providers"
    },
    "_moduleDirectories": [
        "./build"
    ],
```

and using `import 'module-alias/register';` at the top of my index.ts file

**Comment by LoicPoullain** [comment]
Ok, so the problem probably comes from here.

When running the application, the `index.ts` file is read at first and so the `module-alias` module is registered.

But in the case of the migrations, this file is not read. Only the migration files and the files they import are read. This is probably why you get this error.

Could the commands `npx typeorm -r  module-alias/register migration:run` or `node -r  module-alias/register ./node_modules/.bin/typeorm migration:run` fix the problem? Or something similar?

**Comment by HRK44** [comment]
> Ok, so the problem probably comes from here.
> 
> When running the application, the `index.ts` file is read at first and so the `module-alias` module is registered.
> 
> But in the case of the migrations, this file is not read. Only the migration files and the files they import are. This is probably why you get this error.
> 
> Could the commands `npx typeorm -r module-alias/register migration:run` or `node -r module-alias/register ./node_modules/.bin/typeorm migration:run` fix the problem? Or something similar?

I tried and it didn't work. What seems to work is when I import the `module-alias` inside the module `index.ts` (so in entity/index.ts). Maybe would be good to mention that in the docs

**Comment by LoicPoullain** [comment]
> I tried and it didn't work. What seems to work is when I import the module-alias inside the module index.ts (so in entity/index.ts). Maybe would be good to mention that in the docs

Glad that you found how to fix the issue! I'd rather not to add it to the documentation as I feel like it is a specific issue related to the use of a 3rd-part library (module-alias). If anyone has the same problem, he or she will be able to find the solution on this issue. 🙂
