### ISSUE TITLE
Support ServerSideEncryption

### ISSUE THREAD

**Issue by khaliqgant** [FoalTS/foal#1013]
At the moment it looks like the [`upload` function](https://github.com/FoalTS/foal/blob/master/packages/aws-s3/src/s3-disk.service.ts#L33-L37) is used but does't accept an option to pass in the `ServerSideEncryption` header. The `upload` function [takes the same params](https://github.com/aws/aws-sdk-js/blob/master/lib/services/s3.js#L1251) as the the [`putObject`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/classes/s3.html#putobject) function:

```typescript
s3.putObject({
        Bucket: bucketName,
        Key: key,
        Body: fileStream,
        ServerSideEncryption: 'AES256',
        Metadata: { 'docId': 'DOCID', 'docKey': 'XYZZY', 'index': 'pdf' }
})
``` 
[Reference](https://gist.github.com/shentonfreude/19d78c626a1745af950ad08e3d0ab1da) for the above

It would be great if the `disk.write` updated usage could look like this:
```typescript
 await this.disk.write(path, file.buffer, {
      name,
      ServerSideEncryption: 'AES256'
 });
```

FoalTS is fantastic btw, awesome work!

**Comment by khaliqgant** [comment]
Hi @LoicPoullain have you had any chance to take a look at this?

Thanks!

**Comment by LoicPoullain** [comment]
> FoalTS is fantastic btw, awesome work!

Thank you!

> Hi @LoicPoullain have you had any chance to take a look at this?

I'm thinking of adding a fourth parameter (not the third) to the `write` function to pass custom options to the `putObject` method. This would be specific to the `S3Disk` service (and not `Disk)`.

I still need to think about this to check that it won't introduce backward incompatibility, especially on the typing.

**Comment by LoicPoullain** [comment]
@khaliqgant is the `ServerSideEncryption` option is specific to the entire bucket or is it used only for specific files in the bucket?

**Comment by khaliqgant** [comment]
> @khaliqgant is the `ServerSideEncryption` option is specific to the entire bucket or is it used only for specific files in the bucket?

Thanks for your attention to this! It’s a bucket wide policy

**Comment by LoicPoullain** [comment]
Ok thanks. 👍 

Yes, so I think the best place to specify the option will be in the configuration then. It will allow us to keep using the generic `Disk` and `@ValidateMultipartBody` hook in this case. In this way, we will still be able to write a unique code that uses the local file system in development (for testing) and the S3 bucket in production.

**Comment by LoicPoullain** [comment]
Feature added in v2.8. Will be released this week or week-end.

**Comment by khaliqgant** [comment]
Awesome, thanks! Thanks again for your impressive work
