### ISSUE TITLE
@foal/cli - npm by default (or an option to set this)

### ISSUE THREAD

**Issue by lcnvdl** [FoalTS/foal#1016]
Hi! I was talking to a follower who cannot use FoalTS.

He's trying to create an app, and he got an error message, because foal is trying to install the dependencies using YARN.

We have the option to uninstall it (in order to solve the problem), but I was asking:

- Is there any chance to select (or add the possibility to select) the package manager?

Example:

```bash
foal createapp myNewApp --npm
```

Thanks!

**Comment by lcnvdl** [comment]
I'm adding some screenshots.
![error_1](https://user-images.githubusercontent.com/5065981/146435020-1833eb83-3500-4ad4-be2c-c108c991e3a2.jpg)
![error_2](https://user-images.githubusercontent.com/5065981/146435030-ff136773-73b8-4769-8ca5-ea758cfbdf2b.jpg)
![error_3](https://user-images.githubusercontent.com/5065981/146435035-933284ed-4383-4eaf-8e6c-bca7d064dd99.jpg)

**Comment by lcnvdl** [comment]
I'm adding some screenshots:
![error_1](https://user-images.githubusercontent.com/5065981/146435158-da282d33-3664-4e13-95f4-68d562675f9b.jpg)
![error_2](https://user-images.githubusercontent.com/5065981/146435162-a4b86798-ca4a-4bfb-b162-55a2c1466347.jpg)
![error_3](https://user-images.githubusercontent.com/5065981/146435167-59b4b742-3227-4ed0-a5ff-ade861c16e65.jpg)

**Comment by kingdun3284** [comment]
You can simply cd into the folder and install the dependency using ```
npm install
```

**Comment by lcnvdl** [comment]
Yes. 

I think with Yarn (in Windows 11) the setup should work anyway. Doesn't it?

**Comment by LoicPoullain** [comment]
Yes, it seems there's a problem here. @lcnvdl could you re-run the following commands and copy paste the output here so that we can get Yarn traceback?
```
foal createapp my-app
cd my-app
yarn install
```

**Comment by lcnvdl** [comment]
Hi! The guy who has the problem didn't send me any other messages. I'm sorry. I'm closing this ticket, If I have more information I'll let you know. Thank you very much.
