### ISSUE TITLE
Getting Morgan Logger to include remote-IP from proxy

### ISSUE THREAD

**Issue by warren-gallagher** [FoalTS/foal#1018]
When Foal is behind a proxy server such as NGINX, the Morgan logger always shows the localhost as the remote.
I believe this can be fixed by adding:
`app.enable("trust proxy");
`
before adding the Morgan logger.

Is there a way to set this up?

**Comment by LoicPoullain** [comment]
@warren-gallagher does it work if you add it after? Something like:
```typescript
const app = createApp(AppController);
app.enable("trust proxy"); 
```

**Comment by warren-gallagher** [comment]
This appears to work. A couple of articles I read indicated that this app.enable statement had to come first, but after reviewing the Morgan source code, it seemed that this should be OK. Thanks for your help.

FYI, I erred in the initial post. The code should read:
`
const app = await createApp(AppController);
app.enable("trust proxy", true); 
`
