### ISSUE TITLE
A variable defined in `.env` file takes precedence over the one as environment variables with same name

### ISSUE THREAD

**Issue by cantoraz** [FoalTS/foal#1021]
According to the Documentation [Environment Variables and .env Files](https://foalts.org/docs/architecture/configuration#environment-variables-and-env-files):
> If the same variable is provided both as environment variable and in the `.env` file, then the value of the environment variable is used.

But, in the code, a var from `.env' file is prior to the one from environment variables.
https://github.com/FoalTS/foal/blob/359acea679ebc049e768eebf36f1f01d52b77d33/packages/core/src/core/config/env.ts#L27-L31

I think, it's not a literal mistake in the docs. It's reasonable that environment variables should be used.

**Comment by LoicPoullain** [comment]
Hi @cantoraz 👋 

Can you check in your `package-lock.json` (or `yarn-lock.json`) that you don't have `dotenv` as dependency somewhere?

**Comment by cantoraz** [comment]
There is no `dotenv` in the `yarn.lock`.

**Comment by LoicPoullain** [comment]
Ok, thank you. Do you access the environment variable using the XXX `Config.get(...)` ?

**Comment by cantoraz** [comment]
The configuration values are accessed by using `Config.get()`.

I also use the recommend approach to retrieve environment values, as in the
doc Environment Variables and .env Files
<https://foalts.org/docs/architecture/configuration/#environment-variables-and-env-files>
:

> The recommended approach to provide sensitive information to the
> application is to use environment variables and `.env` files which are
> not committed. Then, in the configuration files, the values are retrieved.
>
> .env
>
>> JWT_SECRET="Ak0WcVcGuOoFuZ4oqF1tgqbW6dIAeSacIN6h7qEyJM8="
>>
>
> JS
>
>> const { Env } = ***@***.***/core');
>>
>> module.exports = {
>>   settings: {
>>     jwt: {
>>       secret: Env.get('JWT_SECRET'),
>>       secretEncoding: 'base64'
>>     }
>>   }
>> }
>
>
> If the same variable is provided both as environment variable and in the
> .env file, then the value of the environment variable is used.
>

Actually, the `Config.get()` invokes `Env.get()` to get the env var.

So my issue is just about the function `Env.get()` implementation and the
docs.
The point is a CONTRADICTION that, in a case of same envs being defined
both as env var and in the `.env` file, the docs said the former one took
precedence over the latter one, but was de facto reversed in `Env.get()`
implementation.

Though it's easiest to fix the doc, leaving `Env.get()` untouched, the
treatment as in the doc is more reasonable in daily dev.
But fixing the implementation probably brings in an incompatibility.
Please take it into consideration.

**Comment by LoicPoullain** [comment]
Thank you for the details and for pointing this out! Yes, the implementation is incorrect. Environment variables should take precedence like the docs say, but they're not.

Unfortunately, due to the incompatibility that it'd introduce as you mentioned, this fix will have to wait until v3 of Foal. In the meantime, I'll update the doc accordingly.

For now, I can see this workaround to "simulate" the desired behavior:
```typescript
const { Env } = require('@foal/core');

module.exports = {
  settings: {
    jwt: {
     secret: process.env.JWT_SECRET || Env.get('JWT_SECRET'),
     secretEncoding: 'base64'
    }
  }
}
```

**Comment by scho-to** [comment]
Hi @LoicPoullain,

this one doesn't seem to be too hard to fix. I can try to go at it.

**Comment by LoicPoullain** [comment]
Fixed in v3.
