### ISSUE TITLE
Is there a way to know when and end point response stream is finished?

### ISSUE THREAD

**Issue by warren-gallagher** [FoalTS/foal#1025]
I have a controller end point that creates a temporary file and then uses a stream to return that file in the response.

I would like to be able to delete the temporary file when the stream is done.

The following snippet demonstrates what I am doing thus far. How do I know when I can unlink ofile?
```typescript
        const fileStream = fs.createReadStream(ofile);
        const fileStats = fs.statSync(ofile)
        let response = new HttpResponseOK(fileStream, {stream: true});
        response.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        response.setHeader('Cache-Control', 'no-cache');
        return response
              .setHeader('Content-Length', fileStats.size.toString())
              .setHeader('Content-Disposition', `attachment; filename=${path.basename(ofile)}`); 
```

**Comment by LoicPoullain** [comment]
You can attach a listener to the file stream like this:
```typescript
fileStream.on('close', () => { /* Delete the file */ });
```
The close event is emitted when the stream and the file descriptor have been closed: https://nodejs.org/api/stream.html#event-close.

**Comment by warren-gallagher** [comment]
Thanks. I was thinking I would need to hook into the 'finish' event of the pipe.
