### ISSUE TITLE
Add steps for deployment... like really

### ISSUE THREAD

**Issue by myketheguru** [FoalTS/foal#1050]
I have been working with foalTS for a while now. I really like it. But the problems come up when I want to deploy it. It's almost impossible to deploy and fails everytime. Both on Digital Ocean droplet or Heroku, the story is the same. How do i get around this problem?

**Comment by LoicPoullain** [comment]
Hi @myketheguru 👋 

Which steps do you follow on Heroku? What errors do you get?

**Comment by myketheguru** [comment]
I get this.. Foal not found error

**Comment by LoicPoullain** [comment]
Unfortunately, without more details, I won't be able to help. What are you're doing? Do you follow a Heroku tutorial in particular? Which step is not working? Did you run a specific command? Where does the error come from? Is an error in your terminal when running a CLI command? Is it an error in the build of the Heroku platform? Is it an error that is shown in the logs of server? Is there any traceback? I would be willing to help but I need more info.

**Comment by LoicPoullain** [comment]
Could the issue #1055 could point to the same as yours?

**Comment by LoicPoullain** [comment]
Closing in favor of #1097 1097
