### ISSUE TITLE
Foal ts deploy Heroku Error :  foal: not found

### ISSUE THREAD

**Issue by bobwatcherx** [FoalTS/foal#1055]
i want deploy foalts project to heroku , but get error after : git push heroku master :

 $ foal rmdir build && tsc -p tsconfig.app.json
remote: /bin/sh: 1: foal: not found
remote: error Command failed with exit code 127.
remote:        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
remote: 
remote: -----> Build failed

**Comment by martinsnihur** [comment]
Hello,
I added the following packages to "dependencies" in the package.json file to make it work.

"@foal/cli": "^2.8.1",
"@foal/typestack": "^2.8.1",
"class-transformer": "^0.5.1",
"class-validator": "^0.13.2",
"pg": "^8.7.3",

Luck!

**Comment by bobwatcherx** [comment]
### YES this SOLVED , thanks
