### ISSUE TITLE
Graphql : response not work

### ISSUE THREAD

**Issue by bobwatcherx** [FoalTS/foal#1063]
i follow you web tutorial https://foalts.org/docs/1.x/api-section/graphql/

![tolol](https://user-images.githubusercontent.com/52072811/162561135-22ed6ac3-8db0-471d-9a20-b856184cf0e1.png)

i using query hello based from you web tutorial
but response like that

**Comment by LoicPoullain** [comment]
Hi 👋 

It looks like you're looking at an older version of FoalTS. Does it work with version 2? https://foalts.org/docs/api-section/graphql.

If not, could you share the content of the HTTP request that is made (headers, body)? What is also the software that you're using?

Thanks!

**Comment by bobwatcherx** [comment]
![kazam](https://user-images.githubusercontent.com/52072811/162872186-29a3c208-f187-428e-93b8-4df2307a956a.png)
now it's working , but i want to add request header in context

and graphiql I see there is no feature to add header

the selection of children changes graphiql to graphql-playground

**Comment by LoicPoullain** [comment]
Okay, so from what I understand, sending a GraphQL query from GraphiQL works but it fails from graphql-playground. And you'd like to send it from graphql-playground to be able to add a header to the HTTP request. Is that correct?

If so, could you create and share a repository that highlights the problem / bug? It will really help me investigate and debug the issue. 👍

**Comment by bobwatcherx** [comment]
> Okay, so from what I understand, sending a GraphQL query from GraphiQL works but it fails from graphql-playground. And you'd like to send it from graphql-playground to be able to add a header to the HTTP request. Is that correct?
> 
> If so, could you create and share a repository that highlights the problem / bug? It will really help me investigate and debug the issue. 👍

Thank you for the help .  I'm just asking if foalts has graphql-playground not graphiql ?  if you don't have it but that's okay.  I think graphiql is enough.  Thank you :)
