### ISSUE TITLE
Initalize Socket.IO and pass into WebsocketController

### ISSUE THREAD

**Issue by mwalden2004** [FoalTS/foal#1065]
Hello. I'm trying to customize my socket.io instance (specifically trying to enable the admin instance) but I can't do that as I can't access the raw socket connection. See these docs: https://socket.io/docs/v4/admin-ui/ Any help would be appreciated.

**Comment by mwalden2004** [comment]
That does not work, gives error with server not existing.

**Comment by LoicPoullain** [comment]
Let's try this:

```typescript
import { instrument } = from '@socket.io/admin-ui';

async function main() {
  // ...
  const app = await createApp(AppController, { serviceManager });
  const httpServer = http.createServer(app);

  // Instanciate, init and connect websocket controllers.
  await serviceManager.get(WebsocketController).attachHttpServer(httpServer);
  const wsServer = serviceManager.get(WsServer);
  instrument(wsServer.io, {
    auth: false
  });
}
```

**Comment by mwalden2004** [comment]
Due to complications, we had to remove socket.io from our infrastructure, so I did not get the chance to test this out but I appreciate the help. I'm going to close this issue to remove some clutter. Thank you for your help -- and awesome work on Foal.
