### ISSUE TITLE
foal cli version 2.9.0 adds old dependancies to package.json

### ISSUE THREAD

**Issue by warren-gallagher** [FoalTS/foal#1087]
Version of FoalTS: 2.9.0

When scaffolding a new project using the foal cli (version 2.9.0) other foal dependencies are added at version 2.0 and should also be at 2.9.0. 

Specific packages:
* @foal/core
* @foal/typeorm

**Comment by LoicPoullain** [comment]
Hi @warren-gallagher 👋 

Versions in the `package.json` are specified with the `^` character so that, when installing the dependencies for the first time, `npm` will search for the latest minor version of version 2 (in this case v2.9)
