### ISSUE TITLE
Support runtime checking

### ISSUE THREAD

**Issue by nicolasgere** [FoalTS/foal#11]
Hello,
i did a similar project, but i dont have time to lead it. https://github.com/nicolasgere/squirtle
So may be i can try to help you.
It could be nice to have runtime type checking using joy or something like that in order to have all the benefit of typescript during the dev.

**Comment by LoicPoullain** [comment]
Hi Nicolas,

Thanks for contributing.

I couldn’t find more docs about joy on the Internet, is it a library?

What would be the purpose of having runtime type checking besides the one during compilation? Do you have an example in mind where the last wouldn’t be sufficient?

How would joy handler interfaces checking?

Thanks

**Comment by nicolasgere** [comment]
Sorry it's joi, https://github.com/hapijs/joi, what i have in mind, it's to provide the type checking in the runtime to be sure in the request handler than the body respect the typescript type. As another typed language

**Comment by LoicPoullain** [comment]
Oh ok! Yes this feature should come up in a future release. Currently I’m going to focus on setting up a package for authentication/authorization but schema validation should come right after.

For now, this can be done using a custom pre-hook:
```ts
import { BadRequestError, Context, preHook, PreMiddleware } from '@foal/core';
import * as Joi from 'joi';

export function makeCheckSchemaMiddleware(schema: any): PreMiddleware {
  return function checkSchemaMiddleware(ctx: Context): void {
    if (Joi.validate(ctx.data, schema).errors) {
      throw new BadRequestError();
    }
  };
}

export function checkSchema(schema: any) {
  return preHook(makeCheckSchemaMiddleware(schema));
}
```

```ts
import { RestController, Service } from '@foal/core';
import * as Joi from 'joi';

import { checkSchema } from './check-schema.pre-hook';

const userSchema = Joi.object().keys({
  username: Joi.string().required(),
  password: Joi.string().required()
});

@Service()
class User implements RestController {
  constructor() {}

  @checkSchema(userSchema)
  public async create(data, params) {

  }
}

```

I don’t know yet which json schema validator the future package will be using (joi, ajv, etc). It may be nice to have the same schema for both json validation and sequelize table definition (cf `@foal/sequelize`).

**Comment by LoicPoullain** [comment]
Feature added in v0.4.0-alpha.3 (https://github.com/FoalTS/foal/pull/59) !
