### ISSUE TITLE
Todos GET request in first tutorial is returning 404

### ISSUE THREAD

**Issue by ahmadalibaloch** [FoalTS/foal#1126]
Implemented the tutorial steps one by one correctly. But after doing API Controller changes and refreshing browser or event restarting the server I get 404 like below:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/1916642/184240446-246bfeda-e5f4-47ba-b0de-c88557a87ff2.png">

Result:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/1916642/184240190-1db442a0-35b1-4a94-afc1-4f6cabf2a8c6.png">

Though the home page with "/" route is working fine and I see no error logs in node.js console.

**Comment by edrcq** [comment]
Call GET /api/todos and it will works.

**Comment by ahmadalibaloch** [comment]
thanks, did not find it in docs.
