### ISSUE TITLE
Increase timeout on a specific route

### ISSUE THREAD

**Issue by HRK44** [FoalTS/foal#1151]
I want to increase the timeout on a specific route that could take ~5min to execute, how could I do that with Foal?

**Comment by LoicPoullain** [comment]
A priori, it is not possible to do this for a particular route. To apply a different timeout to the whole server, maybe the `app.setTimeout` method?

**Comment by HRK44** [comment]
I'll try that thanks

**Comment by LoicPoullain** [comment]
Hi @HRK44 

Did it work?

**Comment by HRK44** [comment]
yes all good @LoicPoullain
