### ISSUE TITLE
FoalTS Update (via Foal CLI)

### ISSUE THREAD

**Issue by lcnvdl** [FoalTS/foal#1158]
Hi, I have a suggestion. 

It would be nice to have a FoalTS update assistant (through foal cli maybe). Something like `ng update` but simpler. 

For example, `foal upgrade` (to update to latest foal version). Or `foal upgrade --version x`. 
I find updating Foal a little bit tedious, especially since I have many microservices in a personal project I'm doing, and I have to do this one by one. 

Also, it scares me that -for example- if a new version of FoalTS will depend on a different version of Typescript, or require some dependency on a different version (like typeorm, or redis, or any other).

Thanks for reading!

**Comment by LoicPoullain** [comment]
Hi @lcnvdl 👋 

Thank you for your suggestion. 👍 

A `foal upgrade` could be a nice feature indeed (without the `--version` at first). It could check the project dependencies and upgrade all _patch_ and _minor_ versions of the packages starting with `@foal/`.

The CLI has already methods such as `getProjectDependencies` and `getProjectDevDependencies`. I'll add new ones `setOrUpdateProjectDependency` and `setOrUpdateProjectDevDependency` so as to be able to implement this feature.

Would you like to implement the feature after that?

> Also, it scares me that -for example- if a new version of FoalTS will depend on a different version of Typescript, or require some dependency on a different version (like typeorm, or redis, or any other).

Regarding this point, all minor and patch versions should backward compatible. The minimum requirements on Node and TS versions and other dependencies are set for each major version (i.e v2.x, v3.x, etc)

**Comment by LoicPoullain** [comment]
The public API of npm are documented here: https://github.com/npm/registry. There is probably something to get the framework's version numbers.

**Comment by LoicPoullain** [comment]
The command has been added in v3.1 🎉

**Comment by lcnvdl** [comment]
Thanks for this feature! I'm reviewing the FoalTS commits to better understand the code, and to be able to collaborate in the future :)
