### ISSUE TITLE
Receiving xml in request body

### ISSUE THREAD

**Issue by Malouda** [FoalTS/foal#1203]
Version of FoalTS: 3.0.0
Hi everyone,
I am hitting a snag here!! Is there a way to receive xml in the body of the request? i am receiving json just fine but when i send xml 
request body is empty!!!

Thanks

**Comment by LoicPoullain** [comment]
It looks like [this line](https://github.com/FoalTS/foal/blob/master/packages/core/src/express/create-app.ts#L105) is missing the header `application/xml`. Do you want to submit a PR for this?

**Comment by paoloevan** [comment]
I've published a PR for this #1231

**Comment by LoicPoullain** [comment]
Feature has been added in v4.1 👍
