### ISSUE TITLE
How to get the response time and log it using winston logger in foalts

### ISSUE THREAD

**Issue by zrx-kishore-rajendran** [FoalTS/foal#1204]
I need to know how to log the `method request-path response-time` just like in morgan to be logged in winston logger.

or if I could get the response time from the foalts I can use it to log it manually.

**Comment by LoicPoullain** [comment]
Hi @zrx-kishore-rajendran 👋 

Foal version 4.1 comes with a new advanced logging system and logs the response time upon an HTTP request: https://foalts.org/docs/common/logging/. This version will probably fix your issue. 👍
