### ISSUE TITLE
Question : static access to Context outside a controller

### ISSUE THREAD

**Issue by mboullouz** [FoalTS/foal#1230]
Is it possible to access the 'Context' object from outside the controllers, such as within a simple utility class like 'UiUtils'?
For instance:
```
export class UiUtils {
    static getCurrentUsername() {
         return StaticContext.user?.email;  //StaticContext is Foal Context instance
    }
 }
```
The rationale (in a non-single page application):
In a UI template, we require the ability to consistently display the current username, regardless of the active controller.

**Comment by LoicPoullain** [comment]
Hi @mboullouz 👋 

Foal does not provide such feature. Maybe you can make it work with [Node.JS async hooks](https://nodejs.org/api/async_hooks.html) but I'm not sure that will be easy.
