### ISSUE TITLE
foal: not found

### ISSUE THREAD

**Issue by francelwebdev** [FoalTS/foal#1232]
Hi @LoicPoullain ,
In some cloud provider, the packages inside devDependencies are not installed, so I get : foal: not found .
You should add the @foal/cli inside dependencies.

**Comment by LoicPoullain** [comment]
The `dependencies` property normally only refers to dependencies imported inside the application code. This is why `@foal/cli` is marked as `devDependencies`.

I'd rather to keep it that way for this reason. If needed, it's still possible to move it to `dependencies` after the project is created so as to be supported by Cloud providers. 👍
