### ISSUE TITLE
Express dependency has a known vulnerability. An updated version of express is available

### ISSUE THREAD

**Issue by warren-gallagher** [FoalTS/foal#1257]
Version of FoalTS: 4.3.0

Please see vulnerability report: [https://github.com/advisories/GHSA-rv95-896h-c2vc](https://github.com/advisories/GHSA-rv95-896h-c2vc)

**Comment by lcnvdl** [comment]
Hello Warren. As I understand, this issue will be fixed in FoalTS 4.4.0. The version is about to be published.

**Comment by LoicPoullain** [comment]
Hi @warren-gallagher 👋

Yes, v4.4 just has been released to fix this issue. Thank you for reporting this!

For security vulnerabilities, if you could send a message directly to `security@foalts.org` the next time, this would be awesome 😄.  This way, I'll receive the information directly in my mailbox and the vulnerability won't be disclosed publicly until the fix has been deployed in production. 🙂
