### ISSUE TITLE
Package manager selection when installing foal

### ISSUE THREAD

**Issue by lcnvdl** [FoalTS/foal#1265]
Nowadays there are more and more package managers for node. A VERY GOOD one (and popular) is "pnpm" (performant npm). 
It would be very nice to have support for this package manager, and offer users the choice of the package manager as a question, such as what "nest js" does.

![image](https://github.com/FoalTS/foal/assets/5065981/3fca3d95-7b76-4a09-a35f-db2622c96e69)

What do you think?

**Comment by LoicPoullain** [comment]
Currently, there's a `--no-install` flag that allows users to skip installation and run the `install` command from the package manager of their choice. I think we can keep things as they are on this point: adding new features to the CLI means more features to maintain in the future, and therefore more work. This part is a one-off action and doesn't require too much effort from users to use another package manager. I feel like maintenance costs should be more focused on things like authentication that are hard to implement without a framework.
