### ISSUE TITLE
[Performance] Process.env is slow

### ISSUE THREAD

**Issue by lcnvdl** [FoalTS/foal#1266]
The access to `process.env` is slow.

https://github.com/motdotla/dotenv/issues/562

In order to improve this, other frameworks have an `enable cache` option to the `Env` wrapper.

Something like:
```
Env.useCache = true;
```

As I've seen, FoalTS doesn't have this feature. Is there any possibility to add it?

Thanks in advance

**Comment by LoicPoullain** [comment]
```typescript
const { performance } = require('perf_hooks');

const n = 100;

function measureProcessEnvAccess() {
  const start = performance.now();
  for (let i = 0; i < n; i++) {
    const value = process.env.NODE_ENV;
  }
  const end = performance.now();
  return end - start;
}

const processEnvTime = measureProcessEnvAccess();

console.log(`Time to access properties in process.env: ${processEnvTime / n} milliseconds`);

// Output: Time to access properties in process.env: 0.0015158271789550782 milliseconds
```

According to the results of this test, the average read time of a `process.env` property is 1 nanosecond, which is negligible compared to the response time of an HTTP or DB request. I think the response time is not an issue here.
