### ISSUE TITLE
[Documentation | Getting Started | Introduction] Development Server doesn't load the new frontend app

### ISSUE THREAD

**Issue by SilvestrePerret** [FoalTS/foal#211]
**Describe the bug**
Following the Getting started Guide, the prepared frontend app doesn't load when refreshing `http://localhost:3000`

**To Reproduce**
1. Following the different steps on [this page](https://foalts.gitbook.io/docs/). 
2. Replace the `/public` directory and the `src/app/controllers/templates/index.html` template with the downloaded frontend app files.
3. Refresh in the browser `http://localhost:3000`
4. See no changes (ie. the welcome page of FoalTS).

**Expected behavior**
I expected to see the prepared frontend app after refreshing the page.

**Found Fix**
After I ran again the command `npm run develop`, the correct page loaded.

**Desktop (please complete the following information):**
 - OS: Windows 10 Family
 - Browser: Firefox
 - Version: 61.0.2

**Comment by LoicPoullain** [comment]
Hi @SilvestrePerret,

Thanks for reporting this.

Currently only typescript files are watched when using `npm run develop`. The templates are just copied-pasted in the `lib/` directory when starting the command. They should normally be watched in a future release.

The docs are now fixed, thanks! 👍
