### ISSUE TITLE
Trying to understand the ServiceManager.get()

### ISSUE THREAD

**Issue by Jrfidellis** [FoalTS/foal#214]
About this function inside the ServiceManager:
```
get<Service>(serviceClass: Class<Service>): Service {
    // The ts-ignores fix TypeScript bugs.
    // @ts-ignore : Type 'ServiceManager' is not assignable to type 'Service'.
    if (serviceClass === ServiceManager) {
      // @ts-ignore : Type 'ServiceManager' is not assignable to type 'Service'.
      return this;
    }
    // Get the service if it exists.
    if (this.map.get(serviceClass)) {
      return this.map.get(serviceClass);
    }

    // If the service has not been instantiated yet then do it.
    const dependencies = Reflect.getOwnMetadata('design:paramtypes', serviceClass) || [];
    const service = new serviceClass(...dependencies.map(Dep => this.get(Dep)));

    // Save and return the service.
    this.map.set(serviceClass, service);
    return service;
  }
```

What is the purpose of those lines:
```
    // The ts-ignores fix TypeScript bugs.
    // @ts-ignore : Type 'ServiceManager' is not assignable to type 'Service'.
    if (serviceClass === ServiceManager) {
      // @ts-ignore : Type 'ServiceManager' is not assignable to type 'Service'.
      return this;
    }
```

I can't see why someone would use the ServiceManager to get a instance of ServiceManager, could you please clarify @LoicPoullain? Thanks.

**Comment by LoicPoullain** [comment]
This feature is used when creating "generic" controllers or services.

Let's imagine that we have a controller `MyController` that uses a service named `MyLogger`. The correct way to call this service is to the use dependency injection like this:

```typescript
@Service()
class MyLogger {
  log(msg) {
    console.log(msg);
  }
}

@Controller()
class MyController {
  constructor(private logger: MyLogger) {}

  @Get('/')
  index() {
    this.logger.log('hello world');
    return new HttpResponseOK();
  }
}
```

Under the hood, the global service manager is called like this: `serviceManager.get(MyLogger)`.

Another way to use `MyLogger` with the dependency injection is to do this:
```typescript
@Service()
class MyLogger {
  log(msg) {
    console.log(msg);
  }
}

@Controller()
class MyController {
  constructor(private services: ServiceManager) {}

  @Get('/')
  index() {
    this.services.get(MyLogger).log('hello world');
    return new HttpResponseOK();
  }
}
```

Under the hood, the global service manager is called like this: `serviceManager.get(ServiceManager)`.

This is not the preferred way as it is more complex. But it can be useful when we want to create a generic controller/service like the `EntityResourceCollection` or the `LoginController`.

```typescript
@Controller()
abstract class MyParentController {
  abstract loggerClass;
  constructor(private services: ServiceManager) {}

  @Get('/')
  index() {
    this.services.get(this.loggerClass).log('hello world');
    return new HttpResponseOK();
  }
}

@Controller()
class MyController extends MyParentController {
  loggerClass = MyService;
}
```

In this example, the parent controller defines how the requests `GET /` should be handled. But these are the concrete controllers which decide which strategy to choose to log the messages.

**Comment by LoicPoullain** [comment]
Maybe this could be added in the docs (`controllers.md`?). I'm closing the issue but feel free to re-open it if the explanation is not clear!
