### ISSUE TITLE
Having JWT support for authentication

### ISSUE THREAD

**Issue by LoicPoullain** [FoalTS/foal#254]
**Is your feature request related to a problem? Please describe.**

When developing SPA or mobile applications, the use of sessions and cookies for authentication may be difficult.

**Describe the solution you'd like**

FoalTS should offer a basic support to handle authentication with JWT.

The solution should:
- have a simple hook `@AuthenticateWithJWTHeader` to decode the `Authorization` header and fill the context with the user,
- offer refresh tokens,
- offer token blacklisting.

The solution should not:
- decide how the JWT is sent to the client (cookie, body, headers, etc).

**Comment by LoicPoullain** [comment]
If you already use JWT for authentication, feel free to share your code or suggest something in this conversation :wink:

**Comment by wbhob** [comment]
I would suggest having a global provider also have an "interceptor" of sorts to send data through the decorator. That is to say, after parsing the content of the token, I could make a database call to get more properties of the user from an external function before returning control to the main method controller.

**Comment by LoicPoullain** [comment]
Thanks for the suggestion @wbhob , the feature is on its way.

**Comment by LoicPoullain** [comment]
Added in v0.7.0
