### ISSUE TITLE
Write a small guide on how to get started with FoalTS and Angular

### ISSUE THREAD

**Issue by LoicPoullain** [FoalTS/foal#257]
Points to mention:
- git initialization
- directory architecture
- proxy configuration (explain why not using CORS)
- `@angular/cli` output configuration
- the use of the `csrf` token and the `withCredentials` parameter if the authentication uses sessions and cookies

**Comment by djbeckett** [comment]
+1 - We are planning to use Angular to consume the api we are creating with Foal. I am not new to software dev but I am pretty new to web app dev, so having simple, clear examples like this is super helpful.

**Comment by LoicPoullain** [comment]
Hi @djbeckett , I'm planning to publish a tutorial/example on this in the next two weeks (currently working on it). There's also some cool feature that should come up in February (see #279 and #348)

**Comment by djbeckett** [comment]
Great! Thank you! That sounds terrific.

**Comment by LoicPoullain** [comment]
I'm going to close this for now. I won't have time to write a complete tutorial on how to build a fullstack application with FoalTS & Angular. Tutorials showing applications using Angular & Express are sufficient to get started IMO. I prefer to focus on harder things to set up on one's own: GraphQL integration, authentication with 3rd party providers (Auth0, Cognito, Google, LinkedIn, etc), migration guide from an existing Express application, etc.
