### ISSUE TITLE
Trouble testing service that connects to database

### ISSUE THREAD

**Issue by PatrickDorneles** [FoalTS/foal#273]
Hi @LoicPoullain,

I'm trying to test a service from Foal and i'm having trouble to figure out the best way to do it. It should register a user. Should i try to connect to the the real database (and do a rollback after that), should i mock the database or it is best to create a connection just for testing (maybe a file that runs before the tests)?

I looked for examples of that in the docs and found none, your help would be appreciated. thank you.

**Comment by LoicPoullain** [comment]
Hi @PatrickDorneles ,

The best way to achieve this is to use a test database and add some fake data before the test. Here's an example with a SQLite db:

```typescript
describe('UserService', () => {

  let service: UserService;
  let connection: Connection;

  // Create a connection to the database before running all the tests.
  before(async () => {
    connection = await createConnection({
      // Choose a test database. You don't want to run your tests on your production data.
      database: './test_db.sqlite3',
      // Drop the schema when the connection is established.
      dropSchema: true,
      // Register the models that are used.
      entities: [ User ],
      // Auto create the database schema.
      synchronize: true,
      // Specify the type of database.
      type: 'sqlite',
    });
    const user = new User();
    user.name = 'Mary';
    await connection.manager.save(user);
  });

  // Close the database connection after running all the tests whether they succeed or failed.
  after(() => connection.close());

  it('should have a getUsers method which returns the users of the database', async () => {
    service = createService(UserService);
    const users = await service.getUsers();
    
    strictEqual(users.length, 1);
    strictEqual(users[0].name, 'Mary');
  });

});
```

Note in this example that if another service (or a controller) uses the `UserController`, you can test it by mocking the `UserService`:

```typescript
// my-other.service.ts
class MyOtherService {
  @dependency
  userService: UserService
}

// my-other.service.spec.ts
class MockUserService {
   async getUsers() {
    return [];
  }
}

...
myOtherService = createService(MyOtherService, { userService: MockUserService }); 
...
```

Does it help?

**Comment by LoicPoullain** [comment]
My bad, your example was to register a user, not getting them. It's the same logic though

**Comment by LoicPoullain** [comment]
Hi @PatrickDorneles,

Did it solve your problem? Can I close this?

Thanks!
