### ISSUE TITLE
Support OpenAPI and Swagger UI

### ISSUE THREAD

**Issue by LoicPoullain** [FoalTS/foal#276]
See the description [below](https://github.com/FoalTS/foal/issues/276#issuecomment-470937235).

**Comment by LoicPoullain** [comment]
@FloMaetschke, could you me more details on your experience with OpenAPI / Swagger? Why did you start using it and what for? Is there something that you find very valuable that you cannot go without it? Also, if you've already implemented a solution with Foal, even basic, could you share your code?

Thanks!

**Comment by FloMaetschke** [comment]
Sorry i am just a FoalTS beginner and have just completed your tutorial. Nice!

Anyway, openapi is really useful, because it creates an interoperable service description. With this, you are able to generate service clients and documentation very easy. There are already a lot of tools out there:

E.g: https://github.com/OpenAPITools/openapi-generator 
Have a look on the supported languages. The idea is this:

(a RESTful Framework ) --> openapi --> lots of languages + documentation

vs.

(a RESTful framework) --> angular by hand
(a RESTful framework) --> react by hand
(a RESTful framework) --> language n by hand...

Here is a generator used by loopback to generate there  openapi.json:
https://github.com/strongloop/loopback-next/tree/master/packages/openapi-v3

Maybe this could be transformed to foal.ts needs very easily. 
I don't know if you (foalts) already know how the rest methods metadata are, but thats the way i would go. You just have to extend/ parse the foalts decorators and generate the json for openapi.

I would suggest to first do this and maybe create a command to generate the openapi spec.
When this is done, its easy to add/include an openapi generator and extend your foal command to directly generate the client, or just explain how to do so (less dependencies for foal).

It's just an advice how i would do that. Maybe you have a better idea or plan, i don't know.
I like foalts simplicity, so please keep this in mind.

**Comment by djbeckett** [comment]
+1 for swagger support. Especially of Foal would generate the swagger.json file based on existing controllers. That would be HUGE, in fact.

**Comment by LoicPoullain** [comment]
Someone made me also a demo today. It looks pretty awesome. I'll put this on my top priority list in March then.

Thanks for your comments 👍

**Comment by djbeckett** [comment]
Yeah, it's pretty sweet! The challenge is to avoid having the swagger data be yet another independent representation of the api. That's one thing Loopback does really well. There is a project I looked at that has it out of the box, but it's not connected to the api definition as far as I can tell.

`https://github.com/w3tecch/express-typescript-boilerplate`

If Foal could generate the swagger file from the existing entities, schemas and controllers that would be awesome.

I don't know if it's relevant, but some of the entities I am going to need are going to have 50+ properties. So to keep the controllers lighter I put the schema in a separate file next to the entity:

`account.entity.ts`
`account.schema.ts`

In the controller I grab the schema up top along with a simple id schema. (I know this id schema should be abstracted to some system-wide service, but I'll do that later. :-)

const accountSchema = AccountSchema.get();
const idSchema = {properties: {id: {type: 'integer'}}, type: 'object'};

Then just refer to these as needed in the controller action decorators:

`@Get('/:id')`
` @ValidateParams(idSchema)`
` async getById(ctx: Context) {`
` ... `

and

`@Post('/')`
`@ValidateBody(accountSchema)`
`async post(ctx: Context) {`
` ... `

Anyway, keeping the schemas separate from the controllers would help with DRY if something in addition to the controllers needed to access them, like a swagger generator.

**Comment by djbeckett** [comment]
This might be helpful. It's a [typescript + express template](https://github.com/bitwit/typescript-express-api-template) that includes swagger support. I don't know enough about it to tell, but I figured you could quickly see if there's something in there that would help FoalTS with swagger support.

**Comment by LoicPoullain** [comment]
Follow-up here: I'm working on the issue

**Comment by FloMaetschke** [comment]
thx! Very nice

**Comment by LoicPoullain** [comment]
*Work in progress*.

**Feel free to comment if you feel that something is missing, irrelevant or super useful. Any comments are welcome**.

# Issue

**What is OpenAPI?**

OpenAPI Specification (fka Swagger Specification) is an API description format for REST APIs. An OpenAPI file allows developers to describe entirely an API.

**Why use OpenAPI?**

- It is a **standard** understandable by many developers and **tools**. 
- **Interactive API documentation** can be generated from the OpenAPI Specification file to document the API and let users try out the API calls directly in the browser.
- It allows developers to first describe the API and then implement the server logic by **generating a server stub**.
- **Client librairies** can be generated from the OpenAPI Specification file to interact with the server.

**What functionalities are missing in Foal to take full advantage of OpenAPI?**:
1. Generate a set of controllers and hooks from an OpenAPI Specification file. The developper then just has to implement the API logic.
1. Generate an OpenAPI Specification file from a set of controllers and hooks.
1. Serve a web page that displays the OpenAPI Specification file with a pretty UI (Swagger UI).

**The solution should:**
- be simple, testable and progressive,
- support both YAML and JSON files,
- be DRY and use the existing hooks and decorators when possible upon generating the spec (`JWTRequired`, `ValidateBody`, etc)...
- ...but also let the developper take over if they deem it necessary,
- support multiple specifications,
- have a *watch* mode when generating the spec file,
- support both static and live documentation (?),
- let the developper choose the endpoints for consulting the specification file and the swagger UI,
- let the developer choose where the specification file is to be generated and from which controllers.

**Notes:**
- OpenAPI 3.0 data types are based on an extended subset JSON Schema Specification Wright Draft 00 (aka Draft 5). Therefore, some gateways may be found between the AJV validation hooks and the OpenAPI spec generation.

**To be dug:**
- Search for packages ou examples that "link" / "convert" AJV validation and OpenAPI spec. How are the differences handled ? With a conversion, an error, a warning?
- How do we manage the `components/schemas` and the `$ref` keyword with the framework?

# Solution (proposal)

*Still looking*

# Steps to Implement the Solution

*Still looking*

# Useful resources

- https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Getting-started
- https://swagger.io/docs/specification/about/
- https://github.com/apigee-127/swagger-tools
- https://swagger.io/tools/open-source/open-source-integrations/
- https://github.com/swagger-api/swagger-codegen
- https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations
- https://github.com/OAI/OpenAPI-Specification
- https://loopback.io/doc/en/lb4/OpenAPI-generator.html
- https://loopback.io/doc/en/lb4/Decorators_openapi.html
- https://docs.nestjs.com/recipes/swagger
- https://github.com/Surnet/swagger-jsdoc

**Comment by LoicPoullain** [comment]
Great news! I finished to implement the *OpenAPI & Swagger* PR! The new feature will be available soon (it will be deployed in the April Release at the end of the month).

To wait until then, the documentation can be found [here](https://github.com/FoalTS/foal/blob/v0-8-8/docs/api-section/openapi-and-swagger-ui.md).

Feel free to reach me back if you have any trouble.

**Comment by LoicPoullain** [comment]
The new version has been published! The docs can be found here: https://foalts.gitbook.io/docs/topic-guides/api/openapi-and-swagger-ui
