### ISSUE TITLE
Have CLI commands to quickly connect a Vue/React/Angular frontend to the backend (dev & prod) 

### ISSUE THREAD

**Issue by LoicPoullain** [FoalTS/foal#279]
# Issue 1 : "Proxifying" HTTP requests

When building a web application with a rich frontend, it it very common in development to have two servers serving on different ports. For example, with an application written in Foal and Angular, the backend server serves the port `3000` and the frontend one servers the `4200`.

Consequently requests made by the frontend do not reach the backend as they have a different origin. One hacky solution is to replace the URL path to `http://localhost:3000` in development and to enable CORS requests.

This is bad as:
- it may introduces a different codebase between the environments (dev and prod),
- and it disables a browser protection (the `Same-Origin policy`).

One way to get around this, keeping the policy and the same codebase, is to configure a proxy to redirect `4200` requests to the port `3000`. The CLI of Angular/Vue/React have all this option but not everyone knows that it exists and how to configure it.

# Issue 2 : Specify the correct build output

Once the application is ready to be shipped to production, it is time to build the frontend so that it is served by the backend. There are usually two problems:

- The frontend does not build in the right directory (the `public/` folder). It's not a big deal but it's a bit tedious to change it by hand.
- If the frontend uses a js router (`react-router`, `@angular/router`, etc), the user usually gets a 404 when refreshing a page with the browser button. One workaround is to add a `@Get('*')` route to return each time the front app (the 404 page is then managed by the front).

# Solution

Have a CLI command to quickly set the proxy and change the frontend output directory:

```
foal connect angular ../frontend
foal connect react ../frontend
foal connect vue ../frontend
```

**Comment by FloMaetschke** [comment]
This could be easily fixed by providing an option for openapi /swagger.
With this, its possible to generate the required service clients for many languages.
Thats why i would prefer to set openapi to a higher priority.

**Comment by LoicPoullain** [comment]
Hi @FloMaetschke,

Thank you for your interest!

I just added the description of the issue. I guess it's not related to what you're referring to.

Moving this conversation to #276.

**Comment by LoicPoullain** [comment]
Resolved in February Release.
