### ISSUE TITLE
Improve console UI

### ISSUE THREAD

**Issue by jamesgeorge007** [FoalTS/foal#314]
Currently, on firing in `foal createapp <name>`, the banner is hardly visible as it goes away due to the logging activity for each created file.
> Instead, I would prefer having a spinner with suitable message displayed after completion.

What do you think?

**Comment by LoicPoullain** [comment]
It's true that it's a bit annoying.

What would you suggest? Something like the vue.js CLI output?

**Comment by jamesgeorge007** [comment]
Yes, something of that sort. I shall make the required changes and propose a PR 👍

**Comment by LoicPoullain** [comment]
Shucks, I just made a PR fixe minutes ago :/

**Comment by LoicPoullain** [comment]
Closing this (improvements made in v0.7.3).
