### ISSUE TITLE
Add a type to Context.request

### ISSUE THREAD

**Issue by LoicPoullain** [FoalTS/foal#318]
**Is your feature request related to a problem? Please describe.**

`Context.request` is of type `any`. This is a bit annoying because we cannot take advantage of TypeScript here.

**Describe the solution you'd like**

Having `Context.request` be typed with `@types/express`.

**Comment by tweenietomatoes** [comment]
Formidable package <3
and maybe ctx.request.body.file ?
When i was first checking file upload operations in node back at early days, it was always exploding for big files on SSD. 
Well Foal is claimed to be an enterprise-grade so i am not sure how to make a file upload super safe.
Maybe even a trigger for clamav to test incoming files.

**Comment by LoicPoullain** [comment]
> Formidable package <3
> and maybe ctx.request.body.file ?
> When i was first checking file upload operations in node back at early days, it was always exploding for big files on SSD.
> Well Foal is claimed to be an enterprise-grade so i am not sure how to make a file upload super safe.
> Maybe even a trigger for clamav to test incoming files.

Uploading a file in FoalTS is a feature that will be added soon. It is a different [issue](#298) though.

**Comment by LoicPoullain** [comment]
Functionality in [February 2019](https://github.com/FoalTS/foal/pull/329). Closing this.
