### ISSUE TITLE
Looking for feedback!

### ISSUE THREAD

**Issue by LoicPoullain** [FoalTS/foal#322]
Hey guys,

I'm looking for feedback on Foal and I really want to know what you think! 👍 Also if you do not plan to use the framework in the future, feel free to tell why!

1. What features do you use? What features are you really excited about?
2. Are there features that you find useless, complicated or that you do not plan to use?
3. Did you encounter difficulties when using / learning the framework?
4. Do you think something is missing?
5. How do you authenticate your users (session, cookie, jwt, etc)? Do you use Foal components for that?
6. Do you use sessions?
7. What do you use Foal for (SPA, REST API, etc) ?

If you enjoy the framework, feel free to leave a ⭐️on the repository to spread the word! 😄You can also retweet my [Looking for feedback](https://twitter.com/FoalTs/status/1088004777592737793) tweet!

**Comment by tweenietomatoes** [comment]
i think, foal client should create templates folder and a sample ejs page when we use createapp.
but i couldn't decide which directory is best. maybe main directory near public folder?

**Comment by tweenietomatoes** [comment]
why we need to pass 3 params while using render, __dirname might be optional. i personally prefer to define directory in first param as "./templates/something.ejs.html"

**Comment by LoicPoullain** [comment]
> i think, foal client should create templates folder and a sample ejs page when we use createapp.
> but i couldn't decide which directory is best. maybe main directory near public folder?

Suggestion noted. Usually I create a `templates/` directory in the `controllers` folder(s).

> why we need to pass 3 params while using render, __dirname might be optional. i personally prefer to define directory in first param as "./templates/something.ejs.html"

This is due to the way Node.js handles relative paths. Without the `__dirname` argument, `./templates/something.ejs.html` would be related to where the node process is started (usually the root of the directory) and not the controller file. Maybe the third parameter could be optional though.

**Comment by gilbert** [comment]
Foal's docs say it's based on express. Is it compatible with express middleware libraries? If so, what does that look like?

**Comment by LoicPoullain** [comment]
> Foal's docs say it's based on express. Is it compatible with express middleware libraries? If so, what does that look like?

Hi @gilbert !

It's not possible to use express middlewares in your controllers or hooks. The main reason is that the framework core is almost entirely separated from Express. Express is just used as low-level layer.
However, you can provide your own express instance to `createApp` in `src/index.ts` and thus use express middlewares at a global level.

**Comment by tweenietomatoes** [comment]
>Maybe the third parameter could be optional though.

from what i know ecma 6 came with default params in functions. it can be smtg like function ( x,y = "/") you know already (ts got that advantages as well).

Well nestjs got everything possibly a person can want but varieties and amateur approach improves quality so foal looks much simpler, i came from non-js world and made an app within mins without even check tutorials much. i was expecting errors while it recorded things to database. it is much like async python frameworks.

**Comment by nobleach** [comment]
Probably my biggest gripe is the current config system. JSON is not a pleasant format for working with configs. Further, the idea of needing to have a named file each part of one's config is a bit strange to me. I'm more of a YAML fan when it comes to multi-level configs (but I realize, many people hate that too)

**Comment by LoicPoullain** [comment]
Thanks for you feedback @nobleach.

> Probably my biggest gripe is the current config system. JSON is not a pleasant format for working with configs. [...] I'm more of a YAML fan when it comes to multi-level configs (but I realize, many people hate that too)

We could support both YAML and JSON files in the future. Do you want to submit an issue for that as *feature request*?

> Further, the idea of needing to have a named file each part of one's config is a bit strange to me.

What do you mean?

*Directory structure*
```
config
  |- jwt.production.json
  |- jwt.development.json
  |- settings.production.json
  |- settings.development.json
```

*jwt.development.json*
```json
{
  "secretOrPublicKey": "xxx"
}
```

*settings.development.json*
```json
{
  "debug": true
}
```

Instead of having this, would you like to have something like the example below?

*Directory structure*
```
config.development.yml
config.production.yml
```

*config.development.yml*
```yaml
settings:
  debug: true
jwt:
  secretOrPublicKey: xxx
```

Tell me if I misunderstood

**Comment by nobleach** [comment]
Yes, I should have been more clear. A more common approach is to have config settings in one file with multiple levels:

```
app: {
    port: 8080,
    baseUrl: 'http://localhost'
},
auth: {
    alg: 'RSA'
},
api: {
    authService: 'http://auth-service:8080,
    someUrl: '/blah'
}
```
I'm not saying it's wrong to have one file per concern, I just haven't seen it done that way.

If YAML were to be an option, I'd expect it to be in one file. Maybe? Perhaps I'm wrong about this.

**Comment by LoicPoullain** [comment]
Moving the configuration discussion to a [new issue](#338).

**Comment by LoicPoullain** [comment]
Thank you all for your feedback! I'm closing the issue but feel free to open a new one if needed.
