### ISSUE TITLE
Why export keyword is not public in TS?

### ISSUE THREAD

**Issue by tweenietomatoes** [FoalTS/foal#324]
Hi, i have a general question about jscript and specifically type script.

Why export keyword is not public?

i mean something like
```
public class MyController {
}
```

**Comment by LoicPoullain** [comment]
Hi @tweenietomatoes ,

This syntax is not correct in TypeScript.

Two things to differentiate:
- JavaScript is the language interpreted by Node.js and browsers.
- TypeScript is a typed superset of JavaScript that compiles to plain JavaScript.

The `export` keyword is part of the JavaScript specification (more precisely es6, see [here](http://es6-features.org/#ValueExportImport)). It is used to export variables from a JS module (i.e. a JS file).

But the `public` keyword is part of the TypeScript spec. TypeScript brings type-checking that does not exist in plain JavaScript. JavaScript does not support access modifiers.

Does it help?

**Comment by tweenietomatoes** [comment]
so can we use public instead of export in typescript?

**Comment by tweenietomatoes** [comment]
I was trying to compare that with other languages such as Go.
For example we could use capital letter to export a function. I think export is much clearer than Go.

**Comment by LoicPoullain** [comment]
Closing this as answered by @yeager-j
