### ISSUE TITLE
Index.html in public always high priority

### ISSUE THREAD

**Issue by tweenietomatoes** [FoalTS/foal#330]
I think, index.html in public folder should be lower priority.
When we set root route within controller, index.html still coming first instead of what we set
in controller ("/").

**Comment by LoicPoullain** [comment]
Hi @tweenietomatoes ,

Thanks for the suggestion.

Could you give me more details on what you're trying to do? Why do you keep a `index.html` in the `public/` directory if you're defining a route `/` in your controller?

Thanks

**Comment by tweenietomatoes** [comment]
I didn't touch index.html because while i am experimenting with different frameworks i didn't touch defaults usually. In different frameworks in various platforms mostly i see controller is replacing the index in public when you define root.

**Comment by tweenietomatoes** [comment]
For example when you set 
```
@Get('/')
rootFunc() {
render('other-index.html'...
}
```
web server should render other-index.html instead of index.html in public.

**Comment by LoicPoullain** [comment]
I see. Actually if you do want to render the `other-index.html` template on `/` requests, you could remove `index.html` from the `public/` directory as it is useless here. The problem would be solved.

Putting the static files upstream of the request lifecycle is quite common in Node.js. It prevents the application from unnecessarily executing middlewares or scanning all the controller routes. This architecture pattern is also encouraged when deploying an application to AWS Beanstalk (see [here](https://docs.aws.amazon.com/en_us/elasticbeanstalk/latest/dg/create_deploy_nodejs_express.html) the proxy server configuration).
