### ISSUE TITLE
foal cli 'rest-api' created controllers are not validating id params

### ISSUE THREAD

**Issue by djbeckett** [FoalTS/foal#344]
**Describe the bug**
Controllers created using the foal cli `rest-api` option are not validating the 'id' parameter for the four actions that use it: `@Get('/:id')`, `@Put('/:id')`, `@Patch('/:id')` and `@Delete('/:id')`. Without validating the id params database errors are returned when bad id values are used. It should return `400 Bad Request`.

**To Reproduce**
Create a new entity and controller:

`foal g rest-api widget --register`

There are no @ValidateParams decorators in the controller like there are in the `simple-todo-list` project.

**Expected behavior**
Controllers created by the foal cli should have 

`@ValidateParams({properties: {id: {type: 'number'}}, type: 'object'})` 

just below the method hook like this:

`@Put('/:id')`
`@ValidateParams({properties: {id: {type: 'number'}}, type: 'object'})`
`@ValidateBody(accountSchema)`
` async putById(ctx: Context) {`
	` ... `
`}`

For the four actions that use an id: 

`@Get('/:id')`
`@Put('/:id')`
`@Patch('/:id')`
`@Delete('/:id')` 

I made these changes by hand in my controller and it works, but I will be creating many, many controllers so it would be really great of the foal cli could configure them like this by default.

**Comment by LoicPoullain** [comment]
Thanks for reporting this!

I updated the CLI. The fix should be released this week 👍 

*Note on the database errors:* They would have been only returned in development (`debug` is `true` in `settings.development.json` and `false` in `settings.json`). In production, we would have received an empty 500 error.

**Comment by djbeckett** [comment]
Thank you! And yes I see the config setting for full db error text versus simple 500 error. Thanks for pointing that out.
