### ISSUE TITLE
delete todo in mongodb tutorial deletes the first found todo and not the clicked one

### ISSUE THREAD

**Issue by nihiels** [FoalTS/foal#361]
https://foalts.gitbook.io/docs/tutorials/mongodb-to-do-list/5-the-rest-api

I guess...
await Todo.findOneAndDelete(ctx.request.params.id);
..is not finding the right document. As far as I understood, this method is awaiting an object id and not a string. I'm wondering why TS did not complain.
I changed the line to...
await Todo.findByIdAndRemove(ctx.request.params.id);
...and it's working as expected.

I found the solution here:
https://stackoverflow.com/questions/53046455/mongoose-delete-item-first-one-always-gets-deleted

Cheers

Nils

**Comment by LoicPoullain** [comment]
Hi @nihiels 

Thanks for reporting this issue! Reporting doc's problems is really valuable.

I saw that you created a fork with the fix. Do you want to submit a PR?

Thanks

**Comment by nihiels** [comment]
Sorry, I was getting interrupted.
Cheers

**Comment by LoicPoullain** [comment]
No worries. I merged the PR.

Thanks!
