### ISSUE TITLE
authentication not working with CORS

### ISSUE THREAD

**Issue by madlybong** [FoalTS/foal#371]
ENV
FoalTS as API
IONIC [v3] as frontend

FLOW
1. Api Authentication required (Hook) ---> working
2. Load login page and login with HttpRequestOk ---> working
3. Access Api ---> Not Working

PROBLEM
If I use views like html & vue as showed in example every thing works fine. But when I'm making CORS login it fails to save session

after CORS login ctx.request.session returns
`{cookie: {…}, authentication: {…}}
authentication: {userId: 2}
cookie: {path: "/"}
__proto__: Object`

on the very next request
`{cookie: {…}}
cookie: {path: "/"}
__proto__: Object`

**Comment by LoicPoullain** [comment]
Hi Anuvab,

Thanks for your interest and the details.

It may be related to a cookie issue. CORS requests do not send or set cookies by default.

Could you try to
- add the header `Access-Control-Allow-Credentials: true` in your HTTP responses,
- and add the option `withCredentials: true` to your requests in your frontend? 

Let me know if it changes something.

Thanks!

**Comment by madlybong** [comment]
> Hi Anuvab,
> 
> Thanks for your interest and the details.
> 
> It may be related to a cookie issue. CORS requests do not send or set cookies by default.
> 
> Could you try to
> 
> * add the header `Access-Control-Allow-Credentials: true` in your HTTP responses,
> * and add the option `withCredentials: true` to your requests in your frontend?
> 
> Let me know if it changes something.
> 
> Thanks!

No luck

**Comment by madlybong** [comment]
I've been playning arround with the JWT but when every thing is setup I get this in postman 
'{
    "code": "invalid_token",
    "description": "The token must include a subject which is the id of the user."
}'

while 

'@JWTRequired({ user: fetchUser(User), blackList: isInFile('./blacklist.txt'), cookie: false })'

and 

'{
    "code": "invalid_request",
    "description": "Auth cookie not found."
}'

while

'@JWTRequired({ user: fetchUser(User), blackList: isInFile('./blacklist.txt'), cookie: true })'

**Comment by LoicPoullain** [comment]
> > Hi Anuvab,
> > Thanks for your interest and the details.
> > It may be related to a cookie issue. CORS requests do not send or set cookies by default.
> > Could you try to
> > 
> > * add the header `Access-Control-Allow-Credentials: true` in your HTTP responses,
> > * and add the option `withCredentials: true` to your requests in your frontend?
> > 
> > Let me know if it changes something.
> > Thanks!
> 
> No luck

Would you have some pieces of code to share? In this way, I'll to try to reproduce the bug on my host.

**Comment by LoicPoullain** [comment]
> I've been playning arround with the JWT but when every thing is setup I get this in postman
> `{ "code": "invalid_token", "description": "The token must include a subject which is the id of the user." }`
> 
> while
> 
> `@JWTRequired({ user: fetchUser(User), blackList: isInFile('./blacklist.txt'), cookie: false })`

The problem comes from the claims of the token. Your JWT must include a `sub` property that is the id of your user. This property is only required when specifying the `user` property. It is used to fetch the user from the database.

*Example*
```json
{
  "sub": "1234567890",
  "name": "John Doe",
  "admin": true
}
```

This is probably not well-explained in the documentation, I'll update this.

*Note: The `sub` property must be of type string as required by the [JWT spec](https://tools.ietf.org/html/rfc7519#section-4.1).*

> `{ "code": "invalid_request", "description": "Auth cookie not found." }`
> 
> while
> 
> `@JWTRequired({ user: fetchUser(User), blackList: isInFile('./blacklist.txt'), cookie: true })`

If the `cookie` option is set to `true` then the JWT must be sent in a cookie named `auth`, not in the `Authorization` header. That's probably why it's working in your case.

Let me know if it's not clear.

**Comment by LoicPoullain** [comment]
Hi Anuvab

I completely rewrote the [JWT doc](https://foalts.gitbook.io/docs/topic-guides/authentication-and-access-control/jwt) and added some additional notes to the [CORS page](https://foalts.gitbook.io/docs/topic-guides/api/public-api-and-cors-requests). This should solve the authentication problem with JWT.

Feel free to reopen the issue if you are still having difficulty.
