### ISSUE TITLE
Add a ValidateCookies hook

### ISSUE THREAD

**Issue by LoicPoullain** [FoalTS/foal#375]
# Issue

We currently several validation hooks:
- `ValidateParams`
- `ValidateQuery`
- `ValidateBody`
- `ValidateHeaders`

Validating cookies through the `ValidateHeaders` is not easy and it would be nice to have a custom hook for that. Having a `ValidateCookies` hook would also probably help to generate the OpenAPI spec file when using OpenAPI (see #276).

# Possible Solution

Have a `ValidateCookies` hook.

**Comment by LoicPoullain** [comment]
@swanncastel Do you want to implement this feature in the `@foal/core` package? The feature is very similar to what we have with [`ValidateBody`](https://github.com/FoalTS/foal/blob/master/packages/core/src/common/hooks/validate-body.hook.ts) (except that it uses `req.cookies`).

**Comment by swanncastel** [comment]
Yeah i'd love it !
It seems pretty simple, I'll look at it tonight.

**Comment by LoicPoullain** [comment]
Resolved in v0.8.7
