### ISSUE TITLE
Getting 404 in any case

### ISSUE THREAD

**Issue by tweenietomatoes** [FoalTS/foal#376]
Currently, i created a new app with foal cli.
Then i run it with npm run develop.
Then i deleted public/index.html
I am getting 404 in any case.
I tried adding new routes in ApiController, nothing changed.

**Comment by LoicPoullain** [comment]
Hi @tweenietomatoes ,

Can you give the content of your `ApiController` as well the routes you're trying to access?

Thanks

**Comment by tweenietomatoes** [comment]
import { Get, HttpResponseOK } from '@foal/core';

export class ApiController {

  @Get('/')
  index(ctx) {
    return new HttpResponseOK('Hello world!');
  }

}

**Comment by LoicPoullain** [comment]
Which URL are you typing in the browser? `http://localhost:3001/api` or `http://localhost:3001`?

**Comment by tweenietomatoes** [comment]
Crying... 

 subControllers = [
    controller('/api', ApiController),
  ];

i forgot that i changed there. 😭 

clösing the issue. thx for help. 🍑
