### ISSUE TITLE
Add more comparisons to other frameworks

### ISSUE THREAD

**Issue by chimon2000** [FoalTS/foal#378]
Just to name a few

* [Loopback](https://v4.loopback.io/)
* [Odi](https://odi.gitbook.io) 
* [Adonis](https://github.com/adonisjs/adonis-framework)

**Comment by LoicPoullain** [comment]
Hi Ryan,

Thank you for the suggestion! I will find time to add new comparisons in the documentation

Thanks

**Comment by chimon2000** [comment]
Np, Odi and Foal looked very similar just from a high level, minus the fact that Foal uses Express and Odi uses Fastify.

**Comment by Sharlaan** [comment]
[Nest](https://nestjs.com/)

**Comment by LoicPoullain** [comment]
Thank you for your feedback Raphaël! It really helps me in improving FoalTS in the future.

> Nest is its complexity

Yes, FoalTS intends to be simpler that Nest.

> still missing "Social Auth"

Totally agree with that. I'm currently working on it (reading IETF specifications, defining the components that would be adapted to these scenarios: regular web apps, SPA + API or Mobile + API). I hope to support the common auth providers (Google, Twitter, FB, Github, Linkedin) by the end of June or July. In the meantime, it is still possible to use Foal with other services such as Auth0 or Cognito to manage authentication. 

> 2 full examples with OpenAPI autodoc, login/pw, social auth, and pw reset would be awesome and would definitely put a framework on leading edge, one for REST, other for Graph.

I'm taking note of this. Thanks! Maybe this could be added just after resolving this issue: #423.

> Foal has a few examples right at start of the main Documentation, nice step in this regard 👍

👍 

> and Cypress for e2e ?

Didn't know about Cypress. I'll take a closer look.

> Would be nice to see a table showing fundamental differences between all these frameworks, a bit like Vue did compared to Angular/React on its front page.

Taking note of this as well.

https://foalts.gitbook.io/docs/topic-guides/comparison-with-other-frameworks

**Comment by LoicPoullain** [comment]
@opensas the old page can be found here: https://github.com/FoalTS/foal/blob/v1.x/docs/comparison-with-other-frameworks.md. I removed it back then because I felt it was not as objective as I imagined but, apparently, you prove me wrong 😄.

I'm currently working on re-adding two pages to compare the framework to Express/Fastify and to Nest which are apparently the three big frameworks that people are comparing Foal with when choosing a framework. I'd like to present use cases with code examples to make it as objective as possible.

**Comment by opensas** [comment]
Yes, that would be great, BTW, now that you mentioned it, is there any chance to also have fastify as an underlining library, like nest has?

**Comment by LoicPoullain** [comment]
I'd prefer, for maintenance reasons, to have only one underlying framework (Express or Fastify). Currently, Foal uses Express and I'm not really convinced that Fastify would brind that much: https://github.com/FoalTS/foal/issues/500#issuecomment-558028389. What do you think?

**Comment by warren-gallagher** [comment]
Just found this thread now. I am happy with Express although I have a concern because it is essentially a deprecated project so migrating to something that is supported would provide some comfort…
