### ISSUE TITLE
Some common features that would be awesome

### ISSUE THREAD

**Issue by rick-software** [FoalTS/foal#381]
server-side-render 
sharing via email/social
i18n

This is awesome by the way!

**Comment by LoicPoullain** [comment]
Thanks for the suggestion. I'll put this in the backlog.

Regarding SSR, is this link what you're looking for? https://foalts.gitbook.io/docs/topic-guides/utilities/templating

**Comment by rick-software** [comment]
renderToString is definitely needed... instead of a template engine is it
possible to simply use JSX? Thanks for your timely responses.

**Comment by LoicPoullain** [comment]
Would you have a code example of what you would like to have? What are you trying to accomplish?

**Comment by rick-software** [comment]
I use material ui and nivo charts and want to be able to render react
components on the server for use in shares, emails and embeds.

Here's what I'm doing on the server (App, here is just the Dashboard):

import express from 'express'
import React from 'react'
import ReactDOMServer from 'react-dom/server'
import { SheetsRegistry } from 'jss'
import JssProvider from 'react-jss/lib/JssProvider'
import {
MuiThemeProvider,
createMuiTheme,
createGenerateClassName
} from '@material-ui/core/styles'
import green from '@material-ui/core/colors/green'
import red from '@material-ui/core/colors/red'
import App from './App'

function renderFullPage(html, css) {
return `
<!doctype html>
<html>
<head>
<title>Material-UI</title>
</head>
<body>
<script async src="build/bundle.js"></script>
<div id="root">${html}</div>
<style id="jss-server-side">${css}</style>
</body>
</html>
`
}

function handleRender(req, res) {
// Create a sheetsRegistry instance.
const sheetsRegistry = new SheetsRegistry()

// Create a sheetsManager instance.
const sheetsManager = new Map()

// Create a theme instance.
const theme = createMuiTheme({
palette: {
primary: green,
accent: red,
type: 'light'
},
typography: {
useNextVariants: true
}
})

// Create a new class name generator.
const generateClassName = createGenerateClassName()

// Render the component to a string.
const html = ReactDOMServer.renderToString(
<JssProvider
registry={sheetsRegistry}
generateClassName={generateClassName}
>
<MuiThemeProvider theme={theme} sheetsManager={sheetsManager}>
<App />
</MuiThemeProvider>
</JssProvider>
)

// Grab the CSS from our sheetsRegistry.
const css = sheetsRegistry.toString()

// Send the rendered page back to the client.
res.send(renderFullPage(html, css))
}

const app = express()

app.use('/build', express.static('build'))

// This is fired every time the server-side receives a request.
app.use(handleRender)

app.listen(7000)

**Comment by LoicPoullain** [comment]
```typescript
import express from 'express'
import React from 'react'
import ReactDOMServer from 'react-dom/server'
import { SheetsRegistry } from 'jss'
import JssProvider from 'react-jss/lib/JssProvider'
import { MuiThemeProvider, createMuiTheme, createGenerateClassName } from '@material-ui/core/styles'
import green from '@material-ui/core/colors/green'
import red from '@material-ui/core/colors/red'
import App from './App'

function renderFullPage(html, css) {
  return `
    <!doctype html>
    <html>
    <head>
    <title>Material-UI</title>
    </head>
    <body>
    <script async src="build/bundle.js"></script>
    <div id="root">${html}</div>
    <style id="jss-server-side">${css}</style>
    </body>
    </html>
  `
}

function handleRender(req, res) {
  // Create a sheetsRegistry instance.
  const sheetsRegistry = new SheetsRegistry()

  // Create a sheetsManager instance.
  const sheetsManager = new Map()

  // Create a theme instance.
  const theme = createMuiTheme({
    palette: {
      primary: green,
      accent: red,
      type: 'light'
    },
    typography: {
      useNextVariants: true
    }
  })

  // Create a new class name generator.
  const generateClassName = createGenerateClassName()

  // Render the component to a string.
  const html = ReactDOMServer.renderToString(
    <JssProvider
      registry={sheetsRegistry}
      generateClassName={generateClassName}>
        <MuiThemeProvider theme={theme} sheetsManager={sheetsManager}>
          <App />
        </MuiThemeProvider>
    </JssProvider>
  )

  // Grab the CSS from our sheetsRegistry.
  const css = sheetsRegistry.toString()

  // Send the rendered page back to the client.
  res.send(renderFullPage(html, css))
}

const app = express()

app.use('/build', express.static('build'))

// This is fired every time the server-side receives a request.
app.use(handleRender)

app.listen(7000)
```

**Comment by LoicPoullain** [comment]
@rick-software I came up with this implementation with Foal:

```typescript
import { Context, Get, HttpResponseOK } from '@foal/core';

import React from 'react'
import ReactDOMServer from 'react-dom/server'
import { SheetsRegistry } from 'jss'
import JssProvider from 'react-jss/lib/JssProvider'
import { MuiThemeProvider, createMuiTheme, createGenerateClassName } from '@material-ui/core/styles'
import green from '@material-ui/core/colors/green'
import red from '@material-ui/core/colors/red'
import App from './App'

class AppController {

  private renderFullPage(html, css) {
    return `
      <!doctype html>
      <html>
      <head>
      <title>Material-UI</title>
      </head>
      <body>
      <script async src="build/bundle.js"></script>
      <div id="root">${html}</div>
      <style id="jss-server-side">${css}</style>
      </body>
      </html>
    `
  }

  @Get('*')
  render() {
    // Create a sheetsRegistry instance.
    const sheetsRegistry = new SheetsRegistry()

    // Create a sheetsManager instance.
    const sheetsManager = new Map()

    // Create a theme instance.
    const theme = createMuiTheme({
      palette: {
        primary: green,
        accent: red,
        type: 'light'
      },
      typography: {
        useNextVariants: true
      }
    })

    // Create a new class name generator.
    const generateClassName = createGenerateClassName()

    // Render the component to a string.
    const html = ReactDOMServer.renderToString(
      <JssProvider
        registry={sheetsRegistry}
        generateClassName={generateClassName}>
          <MuiThemeProvider theme={theme} sheetsManager={sheetsManager}>
            <App />
          </MuiThemeProvider>
      </JssProvider>
    )

    // Grab the CSS from our sheetsRegistry.
    const css = sheetsRegistry.toString()

    // Send the rendered page back to the client.
    return new HttpResponseOK(
      this.renderFullPage(html, css)
    );
  }

}
```

If I understand well (tell me if I'm wrong), you currently have two problems:
- You cannot specify in Foal that your static files are served at the path `/build`.
- Your JSX template cannot be compiled and you get a TypeScript error from the compiler.

Regarding the first point, I'm going to open an issue for that as other people may need this too.

Regarding the second point, could it be solved by renaming your file with the `tsx` extension and update your `tsconfig.json` file?

```json
{
  "compilerOptions": {
    ...
    "jsx": "react"
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
  ]
}
```

Let me know if this works.

**Comment by LoicPoullain** [comment]
I added a small tuto on JSX SSR in the docs. With regard to the *sharing via email/social* feature, would [nodemailer](https://nodemailer.com/about/) be what you're looking for?

**Comment by rick-software** [comment]
Yes

**Comment by LoicPoullain** [comment]
Closing this in favor of #447 & #448
