### ISSUE TITLE
Prettify the outputs of the `npm run develop` command

### ISSUE THREAD

**Issue by LoicPoullain** [FoalTS/foal#383]
# Issue

Currently:
1. The outputs of the node process and the compiler are all mixed, making it difficult to know at a glance which error belongs to which step.
1. The colors of the compiler outputs are not displayed.

<img width="800" alt="Capture d’écran 2019-03-19 à 13 02 45" src="https://user-images.githubusercontent.com/13604533/54604725-c339f680-4a47-11e9-98d1-5dd3e0ee7cb6.png">

# Possible solution

Prettify the outputs by splitting the terminal in two boxes.

<img width="1046" alt="Capture d’écran 2019-03-19 à 10 59 19" src="https://user-images.githubusercontent.com/13604533/54604733-c8974100-4a47-11e9-9c35-20289285fdfb.png">

Note that the shortcut `Cmd` + `click` (or `Ctrl` + `click`) should still work in VSCode.

# Resources

- [stmux](https://github.com/rse/stmux), simple Terminal Multiplexer for Node.js Environments.
- [blessed](https://github.com/chjj/blessed), a high-level terminal interface library for node.js.

**Comment by swanncastel** [comment]
Hi Loic,

I was trying to build my own TypeScript config to run with Koa and i had the same issues for the dev mode.

I've found a couple of solutions to have better outputs :

1. Simply execute ts-node with supervisor but doesn't clear on reload and i didn't find a solution to clear the console with supervisor.

2. Use [ts-node-dev](https://github.com/whitecolor/ts-node-dev).

Under the hood, it is based on ts-node and [node-dev](https://github.com/fgnass/node-dev) and you have all of the options of those two libraries.

To clear on reload and to not display a system notification, you just have to add a .node-dev.json file on the project root https://github.com/fgnass/node-dev#settings.

![image](https://user-images.githubusercontent.com/32067200/54940885-ec68f400-4f2b-11e9-9bab-d716197c5250.png)

It is way simpler than splitting the console.

**Comment by LoicPoullain** [comment]
Thanks for your suggestion @swanncastel 

**About the output architecture**

<img width="758" alt="Capture d’écran 2019-03-27 à 09 51 03" src="https://user-images.githubusercontent.com/13604533/55063999-7f637480-5079-11e9-97cb-c45bc8958d6d.png">

I like you approach. I made some tests with `ts-node-dev` and it's true that the output is prettier and less complex than when splitting the console.

For people who would read this issue, here is the behavior when a TS file is changed:
- If a TS error is thrown, the node process is stopped and the error is displayed in the terminal with the proper colors.
- If the compilation succeeds, the node process is restarted.

Going down this path seems like a good idea to me.

**About the technologies to use**

Regarding the way to implement this, I first did a benchmark on `node-dev` and `supervisor` (used independently from anything else) to see what we have.

| Library | Total number of dependencies | `node_modules/` size | Known vulnerabilities (Snyk) | Weekly downloads | Memory usage |
| --- | --- | --- | --- | --- | --- |
| supervisor | 0 | 29 KB | none | 25 183 | 9,9 / 10,4 MB |
| node-dev | 92 | 3,7 MB | [one](https://snyk.io/test/npm/node-dev) | 9 098 | 17,9 / 18 MB |

Used on their own, `supervisor` looks to be a better solution that `node-dev`.

As for our problem, the use of `ts-node-env` has indeed several advantages:
- It directly "implements" the above output specification.
- It consumes less CPU and memory that the current `npm run develop` command.

| | `npm run develop` (supervisor) | `npm run develop` (node-dev) | `ts-node-dev` |
| --- | --- | --- | --- |
| Node memory use (at rest) | 189,9 MB | 204,8 MB | 137,6 MB |
| Node CPU use (at rest) | 2,6 % | 2,6 % | 0,0 % |

- We can get rid of `concurrently` and its 85 direct and indirect dependencies.
- It is increasingly being used (37 057 weekly downloads), so we can suppose that it's becoming a reliable solution.

I have some concerns on the product though:
- There are some [issues](https://github.com/whitecolor/ts-node-dev/issues) on Github about performance problems and incorrect *watching*.
- The latest version of the package is `1.0.0-pre.32` which implies that the solution is not stable yet (cf semantic versioning conventions).
- The process is ran using `ts-node` and not `node` itself. This can be a problem because **the code is not executed in the same way in production or during development**. Here's an example of failing situation:
```typescript
// Directory Structure
// src/
// '- index.ts
// '- schema.graphql

// index.ts
import { readFileSync }  from 'fs';
import { join }  from 'path';

readFileSync(join(__dirname, 'schema.graphql'));
```
This is working using `ts-node-dev` but this may not work with `npm run start` (`node ./build/index.js`) if I forget to copy `*.graphql` files in the `npm run build` command.

Another approach could be also to include a build command in Foal's CLI. The CLI would take care of watching, compiling, copying the files and start and restart the node process in `./build`. This would be a huge work though.

**Comment by LoicPoullain** [comment]
This improvement is not essential and its implementation would be very complicated to maintain and test. Closing this for now.
