### ISSUE TITLE
[Docs][Security] Explain how to limit repeated requests to public APIs (Rate Limit middleware)

### ISSUE THREAD

**Issue by LoicPoullain** [FoalTS/foal#384]

**Comment by squareloop1** [comment]
This one is interesting. Is a rate limiter somehow doable in FoalTS with hooks or is it better to just use `express-rate-limit` and initialize FoalTS with the customized express object?

**Comment by LoicPoullain** [comment]
That's exactly the idea! Currently there is no built-in hook to limit repeated requests to the API but we can use the express middleware `express-rate-limit` with a custom express app.

```typescript
import * as express from 'express';
import * as rateLimit from 'express-rate-limit';

const expressApp = express();
expressApp.use(rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes
  max: 100 // limit each IP to 100 requests per windowMs
}));

const app = createApp(AppController, expressApp); // v1
// For v0.8
// const app = createApp(AppController, { /* ... */ }, expressApp);
```

This issue is a reminder that this example should be added in the documentation (`Cookbook`>`Limit Repeated Requests`). If you feel like you want to submit a PR, I'll be happy to review it!

**Comment by domzgarcia** [comment]
it works now! I don't get any error regarding bson.

Although, I try to check Contex(ctx) in the controller method. It gives me undefined/empty object in these properties.
`console.log('[session]', ctx.session, ctx.user, ctx.state);` // [session] undefined undefined {}
