### ISSUE TITLE
Docs write and example of how to upload file 

### ISSUE THREAD

**Issue by jcpc91** [FoalTS/foal#395]
Please
Could you write and example how to upload a file and how can i write a direct endpoint using de app express what i mean i try to write this code using expressesjs example 

`
async function main() {
  await createConnection();

  const app = createApp(AppController, {
    store: session => new (sqliteStoreFactory(session))({ db: 'db.sqlite3' })
  });
  **app.get('/api/test',  (req, res) => {
    res.send('hello world');
  });**

  const httpServer = http.createServer(app);
  const port = Config.get('settings', 'port', 3000);
  httpServer.listen(port, () => {
    console.log(`Listening on port ${port}...`);
  });
}
` 

im tyring this because i using multer to handle the file but the example from the packege use the app express but this example didn't work i getting 404 not found

  **app.get('/api/test',  (req, res) => {
    res.send('hello world');
  });**

my question is the "app" variable is the expressjs why is not working when i call the end point

thanks for the help!!

**Comment by LoicPoullain** [comment]
Hi @jcpc91 

1. I'm currently working on a new feature to be able to upload files in FoalTS in the future (see #298). I think I would be able to release something within the end of March.
2. In the meantime, if you want to use the express instance (and multer), you can proceed as follow (with your example):

```typescript
import * as express from 'express';
...

const expressApp = express();

expressApp.get('/api/test', (req, res) => {
  res.send('hello world');
});

const app = createApp(AppController, {
  store: session => new (sqliteStoreFactory(session))({ db: 'db.sqlite3' })
}, expressApp);
```
3. If you're saving your uploaded files in a the file system, you also have the option to directly save them using streams:
```typescript
import { createWriteStream } from 'fs';

export class ApiController {

  @Post('/upload')
  upload(ctx: Context) {
    return new Promise((resolve, reject) => {
      req.pipe(createWriteStream('./uploadFile'));
      req.on('end', resolve(new HttpResponseOK()));
    });
  }

}
```

Let me know if this helps.

**Comment by jcpc91** [comment]
hoo! thanks for you help this help me and congratulations

**Comment by jcpc91** [comment]
sorry im testing but didn't work im try to post a file with this code using postman
`POST /api/test/upload HTTP/1.1
Host: localhost:3000
Cache-Control: no-cache
Postman-Token: ac149acd-c16d-156c-f19f-523659adecf4
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="6.pdf"
Content-Type: application/pdf


----WebKitFormBoundary7MA4YWxkTrZu0gW`
 im reviving from the server the status 200 but i don't see the file in the body
`export class TestController {
    @Post('/upload')
    postupload(ctx: Context) {
        console.log(ctx);
        return new HttpResponseOK();
    }
}
`

the previous answer you write but the **req** variable doesn't exist
`@Post('/upload')
  upload(ctx: Context) {
    return new Promise((resolve, reject) => {
      **req.pipe(createWriteStream('./uploadFile'));**
      **req.on('end', resolve(new HttpResponseOK()));**
    });
  }`

thanks for you help

**Comment by LoicPoullain** [comment]
Sorry I meant `ctx.request` which is the request from expressjs

**Comment by LoicPoullain** [comment]
Can you also give me more context on what you're want to trying to do with this file? I will help me define the `upload` coming feature.

- What is the file type?
- Do you plan to save it into database? in the file system?
- Do you need to read it directly in your code?

Thanks!

**Comment by jcpc91** [comment]
hi thanks for you help
im implemented with "multer" d

**Comment by LoicPoullain** [comment]
@jcpc91 if it can help, the last version of the framework now includes support for uploading & downloading files (see [here](https://github.com/FoalTS/foal/blob/master/docs/cookbook/upload-and-download-files.md)).
