### ISSUE TITLE
Why a new framework?

### ISSUE THREAD

**Issue by j209** [FoalTS/foal#402]
Hi
What is different between Foal and [Nest](https://github.com/nestjs/nest),[adonis](https://github.com/adonisjs/adonis-framework) etc?

**Comment by LoicPoullain** [comment]
Hi @j209 

Thanks for your interest!

adding #378 

## Nest

FoalTS and NestJS are both Node.js frameworks that support TypeScript natively. They have some differences though:
- NestJS architecture is greatly inspired by Angular. **Foal's architecture is meant to be simpler and easily approachable from non-Angular developers.** You'll only find three "components" in Foal: controllers, services and hooks. The goal is to give more freedom to developers. They don't spend time trying to understand how the framework wants them doing what they want to do. Instead, the framework lets them build their app in their own way.
- FoalTS is also more than a TypeScript framework. Not only does it bring architecture. But it **also offers many dev tools and utils out-of-the-box useful in many scenario**s. For example, in FoalTS, you have utils to hash passwords, validate and sanitize request bodies, control access through groups and permissions, write and run unit tests, generate database migrations or manage configuration variables between several environments.

## Adonis

I'm less familiar with Adonis but here are some differences:
- Foal is written in TypeScript and Adonis in JavaScript.
- The architecture is pretty different: Adonis defines its routes with functions whereas Foal uses classes and decorators.
- Adonis has its own ORM: [Lucid](https://adonisjs.com/docs/4.0/lucid). Foal uses [TypeORM](http://typeorm.io) or [Mongoose](https://mongoosejs.com/).

**Comment by chiqui3d** [comment]
Wow, I just started to work with Nest and found you trying to do it easier and I got to you and I'm impressed, I love it, I'm going to try it and if any doubt or suggestion come back.

Thanks.

**Comment by chiqui3d** [comment]
Hello @LoicPoullain 
I just started with FoalTS and I love it, but I see some things are missing, and I hope it can help:

Well the first one I just created an issue about template engine here https://github.com/FoalTS/foal/issues/441

1-About structure and directory, I think there is too much 'app' directory,  everything must go into 'src' directory including 'scripts' and the tests folder must go root of the project:

![Image of directory 1](https://image.prntscr.com/image/5_ItIutlRl_HmMDw6Mx78w.png)
![Image of directory 2](https://image.prntscr.com/image/scyrLYLGS-mBZYRSPA4avQ.png)

2- What do you think about automating the controllers based on a option in default file configuration where the controllers will be read and the FolTS  automatically red the paths(Independently of whether you can do it manually if you want to.
)  That's how Symfony framework does it

3- I don't see any cache system.

4- It would be ideal in future now that Node supports Brotli compression, to be able to easily apply it for both gzip and brotli.

5- Hook/Event Listener/ Middlewares: I don't see any option to create a Listener or Hook globally for example for all controllers. Example: Make a Log globally.
I also don't see any way to apply the Hook before or after for a controller or a response.

6-When using CLI I don't have any option to use --mysql to generate the project for mysql

Well this is just an opinion, I hope it's helpful.

Thank you and great work.

**Comment by chiqui3d** [comment]
How do you like this pattern to follow in the events?

MailEvent.ts in src/Event/Mail.ts or your custom **Naming Convention**
```ts

import {EventEmitter} from 'events';

export class MailEvent extends EventEmitter {

    constructor() {
        super();
        this.on("sendMailToUser", this.sendMailToUser);
        this.on("sendMailToCustomer", this.sendMailToCustomer);
        this.on('error', (err) => this.error(err));
    }

    sendMailToUser() {
        console.log('Send Mail To User');
    }

    sendMailToCustomer() {
        console.log('Send Mail To Customer');
    }

    error (err){
        console.error('whoops! there was an error', err);
    }
}
```

ExampleController.ts

```ts
import { Get, HttpResponseNotFound } from '@foal/core';
import { Domain } from '../Entity/Domain';
import { getRepository } from 'typeorm';
import {BaseController} from "../base.controller";
import {MailEvent}  from "../Event/Mail";


export class ExampleController extends BaseController {

  @Get('/')
  async index(ctx) {
    const domain = await getRepository(Domain).findOne( 1);
    if(!domain){
      return new HttpResponseNotFound('Not Domain Found');
    }
    const mailEvent = new MailEvent();
    mailEvent.emit('sendMailToUser');

    return this.render('index.twig',{title: 'Hello Word', domain: domain});
  }

}
```

**Comment by simplenotezy** [comment]
@chiqui3d Curious what you ended up choosing. Currently learning Nest.js, and I really like it so far. But I also stumbled upon FoalTS.
