### ISSUE TITLE
How would you integrate with Cognito or 3rd Party User Service

### ISSUE THREAD

**Issue by phptuts** [FoalTS/foal#405]
Firstly this framework seems awesome, thank you for creating I know that must have been a crap ton of work.  

I am building a project and I would like to use AWS Cognito with FoalTS.  What approach would you recommend?

**Comment by LoicPoullain** [comment]
Hi @phptuts 

Thanks for your interest and for your comment. I really appreciate. 

I need a bit of time to understand what AWS Cognito is made for and what its global architecture is. Do you have any more information to give me? So far, it looks like [Auth0](https://auth0.com/), is it?

Potential related issues: #320, #125

**Comment by phptuts** [comment]
I think it's amazon's version of authentication and user management.  I was able to validate their jwt token using this script though:

```
const jwt = require('jsonwebtoken');
const jwkToPem = require('jwk-to-pem');
import  jwk = require('./public_key.json');
const pem = jwkToPem(jwk);
const token = 'your_token_here';

export const verifyToken = (jwtToken: string): boolean => {
	try {
		const token = jwt.verify(jwtToken, pem);

		const unixTimestampJWTExpires = token.exp;
		const expireDate =  new Date((unixTimestampJWTExpires*1000));

		return expireDate > new Date();
	} catch (e) {
		return false;
	}
};

console.log(verifyToken(token), 'valid token');
```

**Comment by LoicPoullain** [comment]
@phptuts I just merged the PR. The new version should be released this week or the next one! Once published, if you have any difficulties using Cognito with Foal, feel free to reach me out and re-open the issue if needed 👌 Hope this helps!
