### ISSUE TITLE
Cors authorization header

### ISSUE THREAD

**Issue by HaceneCo** [FoalTS/foal#416]
Access to XMLHttpRequest at 'http://localhost:3001/api/projects?archive=false&online=false&q=projet' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by LoicPoullain** [comment]
Hi @HaceneCo 

Thanks for reporting this!

I completed [the docs](https://foalts.gitbook.io/docs/topic-guides/api/public-api-and-cors-requests) to explain how to handle requests with the `Authorization` header when CORS is enabled.

Feel free to reopen the issue if it does not work.

**Comment by AntonioLuisME** [comment]
The docs link to "Page not found". Can't find them by searching the docs either. What are the docs?

**Comment by LoicPoullain** [comment]
Documentation can be found here: https://foalts.org/docs/security/cors
