### ISSUE TITLE
Add calculated column

### ISSUE THREAD

**Issue by lcatania** [FoalTS/foal#418]
Hi,

i was wondering if there is any dedicated way to return a calculated field without adding it to the database with typeorm.

**Example:**

I have the the birthday date in my entity and when i request a user i want to return the user entity with an additional age field which is calculated.

Does someone had this kind of problem and how do u solved it? It looked through the TypeORM documentation but for my Database this feature is not supported.

Best Regards

lcatania

**Comment by LoicPoullain** [comment]
Hi @lcatania 

Would something like this solve your problem?

```typescript
@Entity()
class User {
  get age() {
    // Compute the age based on `this.birthday` and `Date.now()`
  }

  @Column()
  birthday: Date;
}

async function main() {
  const user = await getRepository(User).findOne();
  if (!user) { throw new Error('no user'); }
  console.log(user.birthday);
  console.log(user.age);
}

main();
```

**Comment by lcatania** [comment]
Hi @LoicPoullain 

Yeah i implemented it like this.
My question was more regarding how to return it to the API requester.

**To clarify** : I query the entity from the database and when the entity is found i just returned like this.

`return new HttpResponseOK(user);`

The problem is now that i dont have the calculate age in the model because it isnt part of the database.

One think i was thinking about was to add something like a DTO and split database model from api model. And my question was if there is some proper way to implement it or a complete diffrent way that im missing.

Sorry for my bad explanation im not a native speaker.

Best regards

lcatania

**Comment by LoicPoullain** [comment]
I see. The `age` property is not taken into account during the `JSON.stringify` because it's a getter.

I'm thinking of several ways to do this. Not sure one is better than another.

1. Use a different returned object like this.
```typescript
new HttpResponseOK(Object.assign({}, user, age: user.age));
// or its equivalent:
new HttpResponseOK({ ...user, age: user.age });
```

2. Create a service to return a custom object.
```typescript
class ApiController {
  @dependency
  userService: UserService;

  @Get('/')
  index() {
    // call this.userService.findOne
  }
}

class UserService {
  async findOne() {
    const user = await getRepository(user).findOne();
    return { birthday: user.birthday, age: user.age };
  }
}
```

3. Create a [custom TypeORM repository](https://typeorm.io/#/custom-repository) that overrides the `findOne` method and sets a `age` property.

4. Add a method in the entity and use it to render an object with the date.
```typescript
@Entity()
class User {
  get age() {
    // Compute the age based on `this.birthday` and `Date.now()`
  }

  @Column()
  birthday: Date;

  toObject() {
    return {
      ...this,
      age: this.age
    }
  }
}

new HttpResponseOK(user.toObject());
```

Does it help?

**Comment by LoicPoullain** [comment]
Another approach:

```typescript
@Entity()
class User {
  static async findOneAndComputeAge() {
    const user = await getRepository(user).findOne();
    user.age = // compute age;
    return user;
  }

  age: number;

  @Column()
  birthday: Date;
}

new HttpResponseOK(await User.findOneAndComputeAge());
```

**Comment by lcatania** [comment]
oh yeah that helped me a lot thank you.

btw your doing a great job with this framework keep it up 👌🙌

**Comment by LoicPoullain** [comment]
> oh yeah that helped me a lot thank you.

👍 

> btw your doing a great job with this framework keep it up 👌🙌

Thank you, I appreciate! 

Closing this
