### ISSUE TITLE
Restart server

### ISSUE THREAD

**Issue by Maadtin** [FoalTS/foal#425]
Hello is there anyway to auto restart server everytime a controller is changed? currently I need to restart it manually to see the changes. thanks

**Comment by LoicPoullain** [comment]
Hi Martin,


The server should normally restart every time a controller is changed. Can you provide me more information?
- Do you use `npm run develop`?
- What is your OS?
- What IDE do you use?
- Did your modify your `package.json` file by any chance?

Thanks

**Comment by LoicPoullain** [comment]
Also, what is the path of your controller?

**Comment by Maadtin** [comment]
Hello!
I do use `npm run develop`
Im using Windows 10
My IDE is WebStorm
I generated my controller with the `foal generate controller [controller]`, It was generated in `src/app/controllers`

**Comment by Maadtin** [comment]
Also when I run `npm run develop` the console outputs this message
`Listening on port 3001...
Error: listen EADDRINUSE: address already in use :::3001
     at Server.setupListenHandle [as _listen2] (net.js:1270:14)
 at listenInCluster (net.js:1318:12)
    at Server.listen (net.js:1405:7)
     at main (C:\testing-js\foalts\testing-foalts\src\index.ts:23:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
 Program node ./build/index.js exited with code 1`

But the server still works I can access to `http://localhost:3001`

**Comment by LoicPoullain** [comment]
A previous process (server) might have not be stopped properly. I think the application that you're accessing is actually this old process running and not the one started by the last `npm run develop`.

If you stop `npm run develop`, you should still be able to access `http://localhost:3001` (if it not, let me know).

I'm thinking of two ways to solve this:
- Restart the computer
- Or change the port where the application is served: `PORT=3002 npm run develop`.

Let me know if this works

**Comment by Maadtin** [comment]
It works the first time I run `npm run develop` but after I make a change to the controller it throws the `port already used` message

**Comment by Maadtin** [comment]
I have already restarded my computer and the `PORT=3002 npm run develop` outputs the same message although I'm pretty sure that port is free :s

**Comment by LoicPoullain** [comment]
:/ Looks like `supervisor` does not succeed in killing the old process (that why it worked the first time because there was no process listening on 3002 yet).

Let's try to go with another approach. Can you install nodemon and change the `start:w` script in `package.json` like this?

```
npm install nodemon
```

```json
{
 ...
 "scripts": {
   ...
  "start:w": "nodemon --watch build build/index.js"
   ...
 }
}
```

You will also need to change the port again because 3002 is still used by the old process.

**Comment by Maadtin** [comment]
It doesn't work If I add nodemon pointing to `./build/index.js` but It works If It points to `src/index.ts` It STILLS outputs the busy port message but It does RELOAD to server. Pretty weird to me.

**Comment by Maadtin** [comment]
ah I forgot to say that I added the nodemon command in the `develop` script like this `"develop": "npm run build:app && concurrently \"npm run build:app:w\" \"npm run start:w\" nodemon src/index.ts"` this way is the only way I got it working :S

**Comment by Maadtin** [comment]
forget what I said, It doesn't work anymore XD :/

**Comment by LoicPoullain** [comment]
did you try to add the `nodemon` class in `start:w`?

**Comment by LoicPoullain** [comment]
Can you copy / paste the content of `package.json`?

**Comment by Maadtin** [comment]
No, I added after that, heres my package.json I reverted the changes.
`{
  "name": "testing-foalts",
  "version": "0.0.0",
  "description": "",
  "scripts": {
    "build:app": "copy-cli \"src/**/*.html\" build && tsc -p tsconfig.app.json",
    "build:app:w": "tsc -p tsconfig.app.json -w",
    "start": "node ./build/index.js",
    "start:w": "supervisor -w ./build --no-restart-on error ./build/index.js",
    "develop": "npm run build:app && concurrently \"npm run build:app:w\" \"npm run start:w\" nodemon src/index.ts",
    "build:test": "copy-cli \"src/**/*.html\" build && tsc -p tsconfig.test.json",
    "build:test:w": "tsc -p tsconfig.test.json -w",
    "start:test": "mocha --file \"./build/test.js\" \"./build/**/*.spec.js\"",
    "start:test:w": "mocha --file \"./build/test.js\" -w \"./build/**/*.spec.js\"",
    "test": "npm run build:test && concurrently \"npm run build:test:w\" \"npm run start:test:w\"",
    "build:e2e": "copy-cli \"src/**/*.html\" build && tsc -p tsconfig.e2e.json",
    "build:e2e:w": "tsc -p tsconfig.e2e.json -w",
    "start:e2e": "mocha --file \"./build/e2e.js\" \"./build/e2e/**/*.js\"",
    "start:e2e:w": "mocha --file \"./build/e2e.js\" -w \"./build/e2e/**/*.js\"",
    "e2e": "npm run build:e2e && concurrently \"npm run build:e2e:w\" \"npm run start:e2e:w\"",
    "build:scripts": "tsc -p tsconfig.scripts.json",
    "build:scripts:w": "tsc -p tsconfig.scripts.json -w",
    "lint": "tslint -c tslint.json -p tsconfig.json",
    "build:migrations": "tsc -p tsconfig.migrations.json",
    "migration:generate": "./node_modules/.bin/typeorm migration:generate",
    "migration:run": "./node_modules/.bin/typeorm migration:run",
    "migration:revert": "./node_modules/.bin/typeorm migration:revert"
  },
  "engines": {
    "node": ">=8"
  },
  "dependencies": {
    "@foal/core": "~0.8.0",
    "@foal/ejs": "~0.8.0",
    "@foal/typeorm": "~0.8.0",
    "source-map-support": "^0.5.1",
    "sqlite3": "^4.0.0",
    "connect-sqlite3": "^0.9.11",
    "typeorm": "^0.2.6"
  },
  "devDependencies": {
    "@types/mocha": "^5.2.1",
    "@types/node": "^8.0.47",
    "concurrently": "^3.5.1",
    "copy": "^0.3.2",
    "mocha": "^5.2.0",
    "supertest": "^3.3.0",
    "supervisor": "^0.12.0",
    "tslint": "^5.10.0",
    "typescript": "^3.3.3"
  }
}
`

**Comment by Maadtin** [comment]
yeah that works now. thanks! but why is this?

**Comment by LoicPoullain** [comment]
Great! 👌 

2. Changing the script `start:w` makes the `develop` command use `nodemon` instead `supervisor`. `supervisor` seems to fail to restart the node process on your host. It looks like that, when the compilation restarts, the old process is not killed and so still uses the port making the new process to fail. It seems that `nodemon` is working as expected however.
3. Since old processes were running on the ports 3001, 3002, etc (until you restart your computer), I changed the port to a new one (3004). The syntax `PORT=XXX <command>` only works on Unix system (Mac and Linux) and not on Windows. So in the last attempt, we directly changed the port in the configuration file.

Does that make things clearer?

**Comment by Maadtin** [comment]
Yes that is clear now, thank you very much, closing this!
