### ISSUE TITLE
Port config not working

### ISSUE THREAD

**Issue by iyobo** [FoalTS/foal#428]
The default port is 3000. That currently clashes with something else I'm running.
Port is set in`config/default.json` to "3001" but this does not get respected when I try to launch the server. It still tries to run with port 3000.

This is a brand new project. There are no port settings in either development.json or production.json

**Comment by LoicPoullain** [comment]
Hi Iyobo,

- Which version of the CLI do you use (`foal --version`)?
- Which version of `@foal/core`?
- Can you copy paste all the content of `config/default.json` in the issue?
- Do you run the `npm run develop` command from the root of your directory?

Thanks

**Comment by iyobo** [comment]
To answer these questions I created a brand new project

- 0.8.8
- Whatever version it is with a newly generated project as at right now. This is the pckage.json of a brand new project:
```
{
  "name": "backend",
  "version": "0.0.0",
  "description": "",
  "scripts": {
    "build:app": "copy-cli \"src/**/*.html\" build && tsc -p tsconfig.app.json",
    "build:app:w": "tsc -p tsconfig.app.json -w",
    "start": "node ./build/index.js",
    "start:w": "supervisor -w ./build --no-restart-on error ./build/index.js",
    "develop": "npm run build:app && concurrently \"npm run build:app:w\" \"npm run start:w\"",

    "build:test": "copy-cli \"src/**/*.html\" build && tsc -p tsconfig.test.json",
    "build:test:w": "tsc -p tsconfig.test.json -w",
    "start:test": "mocha --file \"./build/test.js\" \"./build/**/*.spec.js\"",
    "start:test:w": "mocha --file \"./build/test.js\" -w \"./build/**/*.spec.js\"",
    "test": "npm run build:test && concurrently \"npm run build:test:w\" \"npm run start:test:w\"",

    "build:e2e": "copy-cli \"src/**/*.html\" build && tsc -p tsconfig.e2e.json",
    "build:e2e:w": "tsc -p tsconfig.e2e.json -w",
    "start:e2e": "mocha --file \"./build/e2e.js\" \"./build/e2e/**/*.js\"",
    "start:e2e:w": "mocha --file \"./build/e2e.js\" -w \"./build/e2e/**/*.js\"",
    "e2e": "npm run build:e2e && concurrently \"npm run build:e2e:w\" \"npm run start:e2e:w\"",

    "build:scripts": "tsc -p tsconfig.scripts.json",
    "build:scripts:w": "tsc -p tsconfig.scripts.json -w",

    "lint": "tslint -c tslint.json -p tsconfig.json",

    "build:migrations": "tsc -p tsconfig.migrations.json",
    "migration:generate": "./node_modules/.bin/typeorm migration:generate",
    "migration:run": "./node_modules/.bin/typeorm migration:run",
    "migration:revert": "./node_modules/.bin/typeorm migration:revert"
  },
  "engines": {
    "node": ">=8"
  },
  "dependencies": {
    "@foal/core": "~0.8.0",
    "@foal/ejs": "~0.8.0",
    "@foal/typeorm": "~0.8.0",
    "source-map-support": "^0.5.1",
    "sqlite3": "^4.0.0",
    "connect-sqlite3": "^0.9.11",
    "typeorm": "^0.2.6"
  },
  "devDependencies": {
    "@types/mocha": "^5.2.1",
    "@types/node": "^8.0.47",
    "concurrently": "^3.5.1",
    "copy": "^0.3.2",
    "mocha": "^5.2.0",
    "supertest": "^3.3.0",
    "supervisor": "^0.12.0",
    "tslint": "^5.10.0",
    "typescript": "^3.3.3"
  }
}
```

- This is default.json. funny thing is, even here, default port of a new project is set to 3001. But it ignores this and still starts at 3000
```
{
  "port": 3001,
  "settings": {
    "csrf": false,
    "debug": false,
    "loggerFormat": "tiny",
    "staticUrl": "public/",
    "session": {
      "cookie": {
        "path": "/"
      },
      "resave": false,
      "saveUninitialized": false,
      "secret": "e014aeb4eedfe0ad02cd75581e28843d"
    }
  }
}
```

- Yes, I do

**Comment by iyobo** [comment]
So I think the issue is I have a setting in my `~/.bash_profile` for some other application `port=3000`. 
I suggest properly scoping the settings for Foal? Perhaps using `dotenv`

**Comment by LoicPoullain** [comment]
> So I think the issue is I have a setting in my `~/.bash_profile` for some other application `port=3000`.

Yes, the problem probably comes from here. Environment variables override the settings defined in the `config/` files. This way, deployment is facilitated to cloud providers that use a different port.

As you have a `.bash_profile` file, I assume that you are either on Linux or Mac. Running this command should normally fix the issue:
```
PORT=3001 npm run develop
```

Let me know if this works.

**Comment by iyobo** [comment]
But that's just it. What's the point of multi-environment config files if they don't get prioritized over bash pro?

I think this is the issue with using .JSON files for config files as opposed to .JS or .TS files.
It gives better granular config priority control.

for example, I would set `port: 4000` in my config/development.js file and set `port: process.env.PORT || 4000` in my config/production.js file...giving me better control of what config I want the API to prioritize.

**Comment by LoicPoullain** [comment]
Sorry for the late reply.

> What's the point of multi-environment config files if they don't get prioritized over bash pro?

The `Config` class is designed to prioritize environment variables set on the deployed servers. For example, most of cloud providers set a `PORT` variable to tell which port the server should listen on. I may have several environments deployed (development, production, etc) that use a different port on these servers that on my local host.

This choice is arbitrary though and I'm not sure that one choice is better in absolute terms than another.

`dotenv` also prioritizes environment variables (see the section *What happens to environment variables that were already set?*  [here](https://www.npmjs.com/package/dotenv)).

> I think this is the issue with using .JSON files for config files as opposed to .JS or .TS files.
JS/TS gives better granular config priority control.

I see your point. Foal does not allow such thing today. But maybe something could come up in the future, I take note of the proposal.

In the meantime, you can do something on your own in the `src/index.ts` file. This is where `Config.get('port')` is called and so where it can be replaced.

*Note: FoalTS also supports YAML files.*
