### ISSUE TITLE
Question: Custom param validation functions?

### ISSUE THREAD

**Issue by pjo336** [FoalTS/foal#433]
Possibly this is more a question on AJV, but I was curious if there was a way to define your own validation on a body or query parameter coming into a controller request?

A quick and dirty example is something like receiving a date string `2019-05-12`. Rather than just saying `type: 'string'`, i could say "use one of these functions"

```typescript
export function verifyIsDate(dateStr: string) {
  const date = moment(dateStr, 'YYYY-MM-DD', true);
  if (date.isValid()) {
    return date;
  }
  throw new Error('Invalid date entered');
}

export function verifyDateInPast(date: moment.Moment) {
  if (moment().isBefore(date)) return false;
  return true;
}
```

**Comment by LoicPoullain** [comment]
Hi @pjo336 

Thank you for your interest!

- AJV supports additional validations on `string` properties by specifying a `format` such as `date`, `date-time` or `time`. Example: `{ type: 'string', format: 'date' }`. More info here: https://github.com/epoberezkin/ajv#formats.
- It is also possible to build your own hooks in FoalTS. For example in your case, you may end with something like this:

```typescript
function ValidateDate() {
  return Hook((ctx: Context) => {
    const date = moment(ctx.request.body.date, 'YYYY-MM-DD', true);
    if (moment().isBefore(date)) {
      return new HttpResponseBadRequest('Date should be in the past.')
    }
    ctx.request.body.date = date;
  })
}


export class MyController {
  @Post('/something')
  @ValidateBody({
    type: 'object',
    additionalProperties: false,
    properties: {
      date: { type: 'string', format: 'date' }
    },
    required: [ 'date' ]
  })
  @ValidateDate()
  something() {
  }
}
```

Is this what you were looking for?

**Comment by pjo336** [comment]
That looks perfect! Thanks!
