### ISSUE TITLE
Support GraphiQL

### ISSUE THREAD

**Issue by LoicPoullain** [FoalTS/foal#439]
# Issue

[GraphiQL](https://github.com/graphql/graphiql) is in-browser IDE for exploring GraphQL. It would be useful to have it in Foal to explore and test our GraphQL APIs

# Possible solution

Add a new package named `@foal/graphiql`

**Comment by darekaze** [comment]
Instead of iGraphQL, why not [GraphQL Playground](https://github.com/prisma-labs/graphql-playground)? I feel the later will have a better dev experience

**Comment by darekaze** [comment]
Quoted from the `graphql-playground` project:
> ### How is this different from [GraphiQL](https://github.com/graphql/graphiql)?
> GraphQL Playground uses components of GraphiQL under the hood but is meant as a more powerful GraphQL IDE enabling better (local) development workflows. Compared to GraphiQL, the GraphQL Playground ships with the following additional features:
> - Interactive, multi-column schema documentation
> - Automatic schema reloading
> - Support for GraphQL Subscriptions
> - Query history
> - Configuration of HTTP headers
> - Tabs

Yeah, I know it's big, but it is an opt-in dev Dependency so it won't affect building for production.

To list out some features I like it more cause it support subscription out-of-the-box, and get history and tabs features which I found them very useful.

Foal is already good in dev experience imo, and I think `graphql-playground` can make the dev experience in GraphQl even better. If there are any better options, I'm all hear.

**Comment by agustif** [comment]
+1 for GraphQL Playground for me, I guess both are good options if (optional) but, maybe graphiql could come as dfault and playground be an extra command to install (because it's bigger, idk)

**Comment by LoicPoullain** [comment]
According to this issue (https://github.com/graphql/graphql-playground/issues/1143), GraphQL Playground will become a GraphiQL preset in the future and its repo will be archived. This is why Foal will use GraphiQL as default GraphQL viewer.

**Comment by LoicPoullain** [comment]
Feature added in v2.3
