### ISSUE TITLE
Grouping multiple hooks into one custom hook?

### ISSUE THREAD

**Issue by longhungn** [FoalTS/foal#443]
Let's say I have an endpoint that requires many hooks
```javascript
@Post('/products')
  @ValidateBody({...})
  @ValidateHeaders({...})
  @ValidateCookie({...})
  addProduct(ctx) {
    this.products.push(ctx.request.body);
    return new HttpResponseCreated();
  }
```

Is there any way I could create a custom hook `ValidateAll()` that will apply all the 3 validation hooks so I can just specify 1 hook for the endpoint instead?
```javascript
@Post('/products')
  @ValidateAll() 
  addProduct(ctx) {
    this.products.push(ctx.request.body);
    return new HttpResponseCreated();
  }
```

**Comment by LoicPoullain** [comment]
Hi @longhungn 

Thank you for your interest.

Currently there is no built-in function to do it. But I think this would do the trick:

```typescript
import { Hook, getHookFunction }  from '@foal/core';

const hooks = [ ValidateBody({...}), ValidateHeaders({...}), ValidateCookie({...}) ];

export function ValidateAll() {
  return Hook(async (ctx, services) => {
    for (const hook of hooks) {
      const response = await hook(ctx, services);
      if (response) {
        return response;
      }
    }
  });
}
```

Note: This won't work if one of your hooks returns a *hook post function* (https://foalts.gitbook.io/docs/topic-guides/architecture/hooks#architecture) which won't be the case with your `ValidateXXX` hooks.

Does it help?

**Comment by longhungn** [comment]
Feature added in https://github.com/FoalTS/foal/pull/453
Thank you for the great work!
