### ISSUE TITLE
Support Twig template engine and any Express-compatible template engine

### ISSUE THREAD

**Issue by LoicPoullain** [FoalTS/foal#445]
# Issue 

Firstly discussed here: #441.

Twig is a popular template engine in Symfony's ecosystem. Several users requested to be able to use it with FoalTS. Currently we only support EJS templates.

It may be nice to eventually support any Express-compatible template engine without needing to create a new package (`@foal/ejs`, etc) each time (`exports.__express = function(path, options, fn) {}`).

**Comment by chiqui3d** [comment]
Hello @LoicPoullain,

Exactly for anyone Express template engine(Twig, EJS, Handlebars, etc ). It's the easiest and most compatible way.

Please also check this link https://github.com/FoalTS/foal/issues/402#issuecomment-497810358 to have what you think:


Thanks so much.

**Comment by LoicPoullain** [comment]
Feature added in v1.0.0. Should be released at the end of the month.
