### ISSUE TITLE
fetchUser additional columns

### ISSUE THREAD

**Issue by lcatania** [FoalTS/foal#463]
Hi,

im using the jwt authentication in my api. I implemented it like the documentation suggest it.

`@JWTRequired({ user: fetchUser(Users) })`

And it works more or less ,i just got one problem. I have a team relation in my  user and when im trying to access it in my request its always undefined. I guess the fetching of relations in the fetchUser function is not supported. Is this right or am i just missing something obvious  ?  

Here is my Users entity:

```
@Entity()
export class Users extends BaseEntity {

  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @Column()
  email: string;

  @Column()
  password: string;

  @ManyToOne(type => Team, team => team.users)
  team: Team;

  @Column({
    enum: UserType,
    default: UserType.COACH,
    type: 'enum'
  })
  type: string;

  @Column()
  verified: boolean;

  @Column()
  banned: boolean;

  async setPassword(password: string) {
    this.password = await encryptPassword(password);
  }

}
```

Best regards

lcatania

**Comment by lcatania** [comment]
Nevermind i figured out and wrote my own fetch functions.

sorry for bothering you

**Comment by LoicPoullain** [comment]
No worries. Happy that you found out!
