### ISSUE TITLE
Is it possible to call functions in controllers or services from scripts?

### ISSUE THREAD

**Issue by kingdun3284** [FoalTS/foal#468]
The @dependency decorator can only be used in controller or service. So if I want to call a function in the service or controller in the shell script, is it possible?

**Comment by LoicPoullain** [comment]
Yes you can instantiate the service using the `createService` function. It will create the service with all its dependencies:

```typescript
import { createService } from '@foal/core';

class MyService {
  doSomething() {}
}

export function main() {
  const service = createService(MyService);
  service.doSomething();
}
```

There is also `createController` to instantiate a controller, but if one of its methods is shared with a shell script, it's better to move it to a separate service.

Is it what you're looking for?

**Comment by kingdun3284** [comment]
Yes, thank you very much!
