### ISSUE TITLE
ValidateBody behaviour on malformed json

### ISSUE THREAD

**Issue by squareloop1** [FoalTS/foal#470]
The ValidateBody Hook is validating property fields and returns a Http BadRequest when a field is missing.

However, if you send a malformed JSON (e.g. trailing comma) in the request it returns a Internal Server error because it could not JSON.parse the body. Correct behaviour should also be a BadRequest, shouldn't it?

Take this from the docs as example:

```typescript
import { Context, HttpResponseOK, Post, ValidateBody } from '@foal/core';

export class MyController {

  @Post('/user')
  @ValidateBody({
    additionalProperties: false,
    properties: {
      firstName: { type: 'string' },
      lastName: { type: 'string' },
    },
    required: [ 'firstName', 'lastName' ],
    type: 'object'
  })
  postUser(ctx: Context) {
    // In this method we are sure that firstName and lastName
    // are defined thanks to the above hook.
    console.log(ctx.request.body.firstName, ctx.request.body.lastName);
    return new HttpResponseOK();
  }

}
```

If you send a Post Request with a body like 
```json
{
  "firstName": "Test",
  "lastName": "trailing comma",
}
```
you will get a internal server error instead of a bad request.

**Comment by LoicPoullain** [comment]
Hi @squareloop1 

Thanks for reporting this! Yeah, it's inconsistent, the server should return an error 400 instead of a 500. An issue already exists on this: #457. I'm closing this one in favor of the other to keep the issue tracking clean.

I'll fix this when I get extra free time this month 😉
