### ISSUE TITLE
Is it possible to use setCookie() in a SPA?

### ISSUE THREAD

**Issue by wfelipe99** [FoalTS/foal#471]
I'm new to programming and I'm developing a project just for hobby. Also, English is not my native language, so sometimes I can't express myself right.

I was searching for secure ways to use JWT in a SPA project (I'm using Vue) and I found one that split it in two cookies: one with header.payload and another with signature. I'm trying to get it working, but I can't. I searched a lot, I tried a lot and then I'm here.

When I was searching, I found that to a server set cookie successfully it has to be in the same domain as the client, so I did it through nginx. When I use Postman it sets the cookies correctly (even when using mysite.com instead of localhost:3001), but when I try in client, it doesn't. So I think it's not possible or am I setting up something wrong? Thank you.

**hosts**

```
127.0.0.1	mysite.com
127.0.0.1	api.mysite.com
```

**nginx.conf**

```
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    upstream server {
        server localhost:3001;
    }

    upstream client {
        server localhost:8080;
    }

    server {
        listen 80;

        server_name api.mysite.com;
        location / {
            proxy_pass http://server;
        }
    }

    server {
        listen 80;

        server_name mysite.com;
        location / {
            proxy_pass http://client;
        }
    }
}
```

**vue.config.js**

```
module.exports = {
  // configureWebpack: {
  //   devtool: 'source-map'
  // },
  devServer: {
    proxy: {
      '^/api': {
        target: 'http://api.mysite.com',
        ws: true,
        changeOrigin: true
      }
    },
    public: 'localhost:8080',
    disableHostCheck: true
  }
}
```

**loggin.controller.ts** (piece of code, but the most important one)
```
const token = sign(
      { email },
      Config.get<string>('settings.jwt.secretOrPublicKey'),
      { expiresIn: '30min' }
    );

    const tokenExpirationTime = jwtDecode(token).exp;

    const response = new HttpResponseOK();
    const tokenSplit = token.split('.');
    const expiresCookie = new Date();
    expiresCookie.setTime(expiresCookie.getTime() + (30 * 60 * 1000)); // Expirar em 30 minutos

    response.setCookie('header.payload', tokenSplit[0] + '.' + tokenSplit[1], { secure: true, expires: expiresCookie });
    response.setCookie('signature', tokenSplit[2], { secure: true, httpOnly: true });

    return response;

```

**Comment by wfelipe99** [comment]
It was 100% correct. I can't use secure and httpOnly cookies without SSL, so I was getting set-cookie in response headers but not in my web browser. That's it and all my night is gone just trying to solve that...

**Comment by LoicPoullain** [comment]
Glad you found the solution! The are some features that might be interesting in your case:

**The configuration system**

You can use the `Config` class to make the `secure` option varies depending on your environment. For example:

```typescript
import { Config } from '@foal/core';

response.setCookie('my-cookie', 'value', {
  secure: Config.get('jwt.cookie.secure') // The path can be the one you want
});
```

config/default.json
```json
{
  "jwt": {
    "cookie": {
      "secure": false
    }
  }
}
```

config/production.json
```json
{
  "jwt": {
    "cookie": {
      "secure": true
    }
  }
}
```

`npm run start` will not use SSL but `NODE_ENV=production npm run start` will.

**The `@JWTRequired` hook**

If you split your payload and signature into two different cookies you won't be able to use the `@JWTRequired` hook.

```typescript
@JWTRequired({
  cookie: true // The hook expects the token to be sent in a cookie named `auth`
})
export class ApiController {

}
```

I'm not sure why the tutorial suggests to do that, but I think it's intended to prevent the user to have their jwt token stolen in case of XSS (the `httpOnly: true` makes the JS client unable to access the cookie).

If you want to use the above hook, you could include for example the entire jwt in an `httpOnly: true` cookie named `auth`. But in this case, you would not be able to know if the user is authenticated in your SPA. So you could add (in the same idea of the tutorial) the payload in a separate cookie that is not `httpOnly`.

Hope this helps!

**Comment by wfelipe99** [comment]
The configuration idea is great, I didn't think about that, thank you.

Yes, the thing about split the JWT in two cookies is to prevent XSS and prevent the browser to have access to the full JWT. I was thinking and if a user creates a browser extension and convince another user to use that extension, he could easily get the JWT since I was storing it on localStorage, so it would prevent that (I don't know if it's a valid point or if it's 100% correct, but spliting the JWT in two cookie I see a lot of benefits).

About being able to use @JWTRequired(), I made a hook called @AuthHeader() to get the cookies and pass it to the Authorization header, so I just use it before @JWTRequired(). Here it is:

```
import { Hook, HookDecorator, HttpResponseUnauthorized } from '@foal/core';

export function AuthHeader(): HookDecorator {
  return Hook(async (ctx, services) => {
    const cookies = ctx.request.cookies;
    if (!(cookies['header.payload'] || cookies['signature'])) {
      return new HttpResponseUnauthorized();
    }

    ctx.request.headers['authorization'] = `Bearer ${cookies['header.payload']}.${cookies['signature']}`;
  });
}
```

What you think about that? It's working, but is it secure? I don't know, but I hope so.

I have a suggestion, though:

First, thank you for answer me, I really appreciate. I'd like to thank you for this great framework. Before FoalTS, I tried so many frameworks and almost all of them was needed a lot of work to get simple things done. The best I found was AdonisJS, but one day I read a comment from a user in a reddit post, I gave it a try and I got delighted in the first minutes using FoalTS. I don't know if it's because I'm new to programming, but your point "But when it comes to setting up a complete and scalable project, things get harder. You have to put everything in place. The authorization system, database migrations, development tools [...]". Why they just don't do this things like FoalTS does? I know that some projects are very specific and they really need to build it their way, but I think it's quite rare.
Anyway, I would love to contribute to FoalTS by writing code, but I don't have necessary knowledge for that. I really want to contribute because I believe that it needs to get know by everyone. What about translate the main website and the documentation to another language? Do you plan that? My native language is Portuguese (Brazil) and I'd love to translate it and see it in my language.

**Comment by LoicPoullain** [comment]
> I made a hook called @AuthHeader() to get the cookies and pass it to the Authorization header

Nice trick.

> I think that the if inside auth-header.hook.ts is useless, since @ValidateCookies() is already doing that job, right?

Correct.

Maybe the `additionalProperties: false` can be annoying in case you want to add other cookies at some point.

Also in the new version 1, you can have a more concise code with this:
```typescript
@ValidateCookie('header.payload')
@ValidateCookie('signature')
@AuthHeader()
@JWTRequired()
export class WhateverController {}
```

And you can also merge your hooks into a single one if needed:
```typescript
function AuthRequired() {
  return MergeHooks(
    ValidateCookie('header.payload'),
    ValidateCookie('signature'),
    AuthHeader(),
    JWTRequired()
  )
}

@AuthRequired()
export class WhateverController {}
```

> but is it secure?

I don't see a possible issue in this case. Even if your cookies are empty, you will end up with `Authorization: Bearer .`, but this won't be a problem since `@JWTRequired` will check that the JWT format is valid.

> First, thank you for answer me, I really appreciate.

👍 

> I'd like to thank you for this great framework. Before FoalTS, I tried so many frameworks and almost all of them was needed a lot of work to get simple things done. The best I found was AdonisJS, but one day I read a comment from a user in a reddit post, I gave it a try and I got delighted in the first minutes using FoalTS. I don't know if it's because I'm new to programming, but your point "But when it comes to setting up a complete and scalable project, things get harder. You have to put everything in place. The authorization system, database migrations, development tools [...]". Why they just don't do this things like FoalTS does? I know that some projects are very specific and they really need to build it their way, but I think it's quite rare.

Thank you!

>  I would love to contribute to FoalTS by writing code [...] What about translate the main website and the documentation to another language?

The documentation is improved regularly, so translations may quickly get outdated or incomplete. However, the main issue (imo) the framework is having now is to get known by people (as you mentioned). If you feel like to write, feel free to write tutorials/articles/videos on other community websites. They can be inspired from the documentation or completely invented, in English or Portuguese. I don't know if there is a well-known website with tutorials for Portuguese speakers (I know there is one in French), but if it exists, it may be interesting to have tutorials on it.

Other channels that may be interested as well: if you are on twitter, reddit or other forums, you can explain why you like the framework and why you chose it over another. The more people are talking about the framework, the more other people might be interested in taking a look.

Also if you publish something, feel free to send me msg so that I can like and retweet it :wink:

This is probably the best way to help the framework at the moment. Depending on how much time you you want to spend on, it can be three tutorials and a video or just a single comment on reddit. In any case, any contribution, no matter how big or small it is, is helping. 👍
