### ISSUE TITLE
[Sessions] Support MongoDB as session storage

### ISSUE THREAD

**Issue by LoicPoullain** [FoalTS/foal#474]
# Issue

We currently have `TypeORMStore` and `RedisStore` to store sessions in SQL and Redis databases. It is annoying for people using MongoDB with FoalTS. We should also support `MongoDB` session storage.

**Comment by yaaminu** [comment]
@LoicPoullain what's the state of this issue? Is it being worked on?

**Comment by LoicPoullain** [comment]
It can be added to August release. Do you need it?

**Comment by yaaminu** [comment]
By **do I need it**, are you saying **do I want to work on it?**

**Comment by LoicPoullain** [comment]
Oh, thank you for your proposal @yaaminu. I'd rather handle this one myself because it is a critical part of the framework's authentication system. Thanks anyway for your interest !

**Comment by yaaminu** [comment]
Alright, I understand where you're coming from but could you not as well review the code after I submit it?

**Comment by domzgarcia** [comment]
Hi, I just encounter the same issue, integrating mongoose-store on this framework for session support. I'm using windows 10. I found a problem in Windows SDK, Kerberos telling `Cannot find module 'mongodb/node_modules/bson` I don't actually point out the of source the problem. Maybe due to versions of MongoDB? Hope you'll not encounter the same.

Anyways, I am excited for the complete support of MongoDB on this framework.

**Comment by yaaminu** [comment]
@domzgarcia I suspect this is because the `bson` module hasn't been installed due to one or two reasons. Can you share the error messages here? That would be very helpful in diagnosing the issue.

**Comment by domzgarcia** [comment]
```
C:\Users\COMPUTERNAME\Desktop\New folder\node_modules\bson>if not defined npm_config_node_gyp (node "C:\Users\COMPUTERNAME\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\COMPUTERNAME\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\COMPUTERNAME\Desktop\New folder\node_modules\bson\build\bson.vcxproj]
```

**Comment by domzgarcia** [comment]
@yaaminu  here you go.
`
C:\Users\COMPUTERNAME\Desktop\New folder\node_modules\bson>if not defined npm_config_node_gyp (node "C:\Users\COMPUTERNAME\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\COMPUTERNAME\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\COMPUTERNAME\Desktop\New folder\node_modules\bson\build\bson.vcxproj]
`

**Comment by yaaminu** [comment]
@domzgarcia from the error log, you don't have the c++ sdk (aka mvc toolchain) for building node.js native modules on your system. Normally, installing [Visual studio](https://visualstudio.microsoft.com/) should fix this issue. The community edition will work fine.

This [npm module](https://github.com/felixrieseberg/windows-build-tools) purports to install the `mvc toolchain` with a single command without runing the visual studio installer. 
just run `npm install --global windows-build-tools`

I've highlighted the relevant error message from the log:
 _**error MSB8036: The Windows SDK version 8.1 was not found**_

**Comment by domzgarcia** [comment]
it works! I don't get any error regarding bson.

Although, my next concern is, I try to check Contex(ctx) in the controller method. It gives me undefined/empty object in these properties.
`console.log('[session]', ctx.session, ctx.user, ctx.state);` // [session] undefined undefined {}

### setup
```
import 'source-map-support/register';

// std
import * as http from 'http';

// 3p
import { Config, createApp } from '@foal/core';
import * as express from 'express';
import * as session from 'express-session';
import * as mongoose from 'mongoose';

// App
import { AppController } from './app/app.controller';

async function main() {
  // connect database
  const uri = Config.get<string>('mongodb.uri');
  const secret = Config.get<string>('settings.session.secret');

  mongoose.connect(uri, { useNewUrlParser: true, useCreateIndex: true });
  // add mongostore
  const expressApp = express();
  const MongoStore = require('connect-mongo')(session);
  expressApp.use(session({
    secret: secret,
    store: new MongoStore({
      url: uri,
      ttl: 14 * 24 * 60 * 60,
    }),
  }));

  const app = createApp(AppController, expressApp);

  const httpServer = http.createServer(app);
  const port = Config.get('port', 3001);
  httpServer.listen(port, () => {
    console.log(`Listening on port ${port}...`);
  });
}

main();
```

**Comment by yaaminu** [comment]
**Important!**
I'm assuming that your clients are  sending the session token either via the `Authorization` header or cookies as described in the [documentation](https://www.npmjs.com/package/express-session)

You seem to be doing everything correctly regarding the session store setup. You are getting undefined because `foal` doesn't support mongodb session store natively. You have to use the old and manual "express-session" way of managing sessions. This very issue exists to address that.

But while we await its implementation from @LoicPoullain , you can get access to the current request through `context.request` which you can treat as an express request instance so `context.request.session` should give you the current session. 

Let me know if you need more assistance!

**Comment by LoicPoullain** [comment]
@yaaminu Thank you for helping @domzgarcia  on this issue.

As Amin mentioned, Foal's authentication system and session management do not rely on the `express-session` middleware. Express is actually only used as a very low level as primitive base layer of FoalTS.

I'm currently working on MongoDB support and the PR will probably be merged in the August release so as you can use it.

I'm taking some days of vacations in August, that's why I'm not super responsive on Github issues 😉

**Comment by domzgarcia** [comment]
yeah exactly @yaaminu 
https://github.com/domzgarcia/foalts-sql-nosql-implem/blob/master/mongotodos/templates/index.html#L64

thanks, guys! Appreciate the effort. Will be waiting on the MongoDB support!

Thanks, @LoicPoullain your works are awesome!

**Comment by LoicPoullain** [comment]
Feature added in v1.1.0
