### ISSUE TITLE
Prettify the "500 error page" in development

### ISSUE THREAD

**Issue by LoicPoullain** [FoalTS/foal#479]
Currently the 500 error page in development is quite ugly. It would be nice to have something prettier (with a bit of CSS...)

<img width="978" alt="Capture d’écran 2019-07-17 à 15 17 33" src="https://user-images.githubusercontent.com/13604533/61378840-96d3a100-a8a6-11e9-95a5-3a7d29ad90a1.png">

If someone wants to take care of this, feel free to add a comment below and submit a PR!

*Note: In order to keep the `@foal/core` package small, the page cannot rely on a 3rd CSS framework (such as Bootstrap for example)*

**Comment by amylily1011** [comment]
Hi @LoicPoullain

I'd like to contribute to foal development and since this is labelled 'good first issue', I think this could be a good issue for me. May I take it on?

Also, Is there any design document or brand like bible that would give me an idea of how to design the page?

**Comment by LoicPoullain** [comment]
Hi @amylily1011 

Thank you for your interest!

> May I take it on?

Yes, sure.

The idea would to add a *smooth* layer of css to make the page more presentable. Maybe a bit of colors, some divs, some font changes.

> Also, Is there any design document or brand like bible that would give me an idea of how to design the page?

To get an idea, here what we have in other frameworks.

*rails*
<img width="922" alt="rails" src="https://user-images.githubusercontent.com/13604533/61444475-c7b9e180-a94b-11e9-8a01-719650f060eb.png">

*flask*
![flask](https://user-images.githubusercontent.com/13604533/61444501-cbe5ff00-a94b-11e9-968d-cd8f576e64ed.png)

*sqlalchemy*
![sql](https://user-images.githubusercontent.com/13604533/61444504-cc7e9580-a94b-11e9-8c98-4c3b3884f4c3.png)

*Yii2*
![Yii2](https://user-images.githubusercontent.com/13604533/61444513-cee0ef80-a94b-11e9-8345-8b05ac1e2746.jpg)

*Symfony*
![symfony](https://user-images.githubusercontent.com/13604533/61444520-d0aab300-a94b-11e9-9bef-efa9345278bd.png)

*Django*
![image](https://user-images.githubusercontent.com/13604533/61444721-3dbe4880-a94c-11e9-9c43-749da83de5ef.png)

**We won't be able/won't need to add so much details in the page.** The above pages are a bit overloaded IMO. A simple page if ok. We only have this data: the error message, the error name, the error stack and the content of the request.

The page to update is located in `packages/core/src/express/500.debug.html` from the `july-august-release` branch. If you need to add information on the request in the page, you can specify some data in `handle-errors.ts`

If needed, the colors of the logo are #176edb and #3887e7.

Is this more clear? Should I assign the issue to you?

**Comment by kingdun3284** [comment]
I want to do it , can you assign the task to me?

**Comment by amylily1011** [comment]
I was planning to sketch out something but @kingdun3284, you can take this one :)

**Comment by LoicPoullain** [comment]
> May I take it on?

@amylily1011  asked first to take this task. So if you still want it, you will have priority over this one. In the other case, I'll assign it to @kingdun3284 . Both are fine with me.

**Comment by amylily1011** [comment]
@LoicPoullain Thank for your reply. In that case, I'd like to take on this issue. I'll sketch out something based on your current color scheme with a UX message that differentiates the tone of language and you (or your team members) can review it and pick the one that makes the most sense to the product. 

After that I'll submit a pull request for this page 👍

**Comment by LoicPoullain** [comment]
@amylily1011 sounds great!

@kingdun3284 I'll open other "good first" issues in the next weeks if you want to take some 😉

**Comment by amylily1011** [comment]
@LoicPoullain I just started setting up the dev environment with an example project. However, although I replaced `HttpResponseOK` calls with `HttpResponseInternalServerError` it still yields a normal HTTP page without any debug errors.

What would you do to reproduce the dev 500 error page? I'm starting the app with `npm run development`

**Comment by LoicPoullain** [comment]
Why do you mean by *setting up the dev environment*? Did you create a new project with `foal createapp` or are you working on FoalTS' repository?

If you are on a new project, you can make the 500 error page show by throwing an error in the controller:

```typescript
export class AppController {
  @Get('/something')
  a() {
   throw new Error('An error');
  }
}
```

**Comment by amylily1011** [comment]
Hey @LoicPoullain ,

I just got the environment set up and played around with Foal. Below are some sketches I've made based on the resources I've found. 

Take a look at the language, view components, and the placement of the logo and pick the one that fits with your preference the most. Then I'll create a PR for it :). 

Version 1
![Type 1](https://user-images.githubusercontent.com/18423198/61580130-8f163580-ab0e-11e9-82d2-9421830d4007.png)

Version 2
![Type 2](https://user-images.githubusercontent.com/18423198/61580131-8f163580-ab0e-11e9-9719-52491aaa49c8.png)

Version 3
![Type 3](https://user-images.githubusercontent.com/18423198/61580132-8f163580-ab0e-11e9-8a4a-db8d0e106a7f.png)

**Comment by amylily1011** [comment]
@LoicPoullain 
Let me know which one you (and your team) decide to go with from the 3 versions above. I'll start working on it in the evening :-)

**Comment by LoicPoullain** [comment]
Thank you for your proposals @amylily1011! They look better than the current page! I have a preference for version 3. :+1:

Regarding the content, the page that we are working on is only intended to be used in development (only developers will be able to see it). On production (`NODE_ENV=production`), end users will only see for now a message `500 - Internal Server Error` that gives no information about the backend framework that the application uses.

With this mind, we can change the first title with the `err.name` and the second with the `err.description`. The third one "Try refreshing in a few minutes" should be removed as only developers will see this page.

Thank you for working on this! This will improve the developer experience 👍

**Comment by amylily1011** [comment]
I merged it into branch `july-august` but there seems to be a problem not passing the test, which I don't think it has much to do with my modification since it's only in css and html, because the script tests something else. 

Let me know if there is anything that I might have overlooked.

**Comment by LoicPoullain** [comment]
Feature added in v1.1.0 (August Release). Thanks @amylily1011 ! Closing this.
