### ISSUE TITLE
express-rate-limit problem with CORS headers on API endpoints

### ISSUE THREAD

**Issue by squareloop1** [FoalTS/foal#485]
I came across some problems while using the rate limiter on API endpoints with CORS.

Basically you have to use the `express-rate-limit`'s  `handler` [function](https://github.com/nfriedly/express-rate-limit#handler) to set the headers, otherwise they don't get set at all because the response from the rate limiter doesn't get handled by FoalTS.

I am setting the headers FoalTS sets in its `createApp`-function manually in the handler. Currently my rate limiter setup looks like this:

```typescript
expressApp.use(rateLimit({
      windowMs: 15 * 60 * 1000,
      max: 50,
      skip: req => req.method.toUpperCase() === 'OPTIONS',
      message: {
        status: 'error',
        description: 'Too many requests. Please try again later.'
      },
      handler: function (req, res, next) {
        // FoalTS Headers
        res.removeHeader('X-Powered-By');
        res.setHeader('X-Content-Type-Options', 'nosniff');
        res.setHeader('X-DNS-Prefetch-Control', 'off');
        res.setHeader('X-Download-Options', 'noopen');
        res.setHeader('X-Frame-Options', 'SAMEORIGIN');
        res.setHeader('X-XSS-Protection', '1; mode=block');
        res.setHeader('Strict-Transport-Security', 'max-age=15552000; includeSubDomains');
        res.setHeader('Access-Control-Allow-Headers', 'Content-Type,Authorization,X-Requested-With');

        // CORS
        res.setHeader('Access-Control-Allow-Methods', 'GET,POST,PUT,PATCH,DELETE,OPTIONS');
        res.setHeader('Access-Control-Allow-Origin', '*');

        // Send this response for rate limited requests
        res.status(this.statusCode!).send(this.message);
      }
    }));
```

Is this maybe related to #384 and #472 and we should update the docs accordingly or can this be handled somehow with FoalTS CORS hooks?

Which response headers should be set on the rate limiter response?

**Comment by LoicPoullain** [comment]
We won't be able to use FoalTS CORS hooks in this case. I'll take a look on Monday at which headers are needed  😉

**Comment by LoicPoullain** [comment]
Ok so, first, thank you for reporting this! We can assume that all FoalTS headers are required by default (even if some might be useless in this case: for example `X-XSS-Protection`). Do you want to submit a PR to update the doc?

If so:
- Could the CORS lines simply be replaced with this?
    ```typescript
    // CORS (optional)
    res.setHeader('Access-Control-Allow-Origin', '*')
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization')
    ```
- Is there any particular reason why the `skip` option was added for `OPTIONS` requests?

In August release, FoalTS could also export a new function `foalHeaders(res)` to set the security headers for us. What do you think?

**Comment by squareloop1** [comment]
Yes I can submit a PR to update the docs.

I am skipping Options requests to not count them into the rate limiter max requests. It made some problems on a API project with some low max request values. Should I add this to the Docs also?

Also you need the `Access-Control-Allow-Headers` of `GET,POST,PUT,PATCH,DELETE,OPTIONS` if you build a REST API to allow those methods in the preflight requests.

In my API root controller I have this to send a working preflight response:

```typescript
@Options('*')
  @ApiResponse(201, { description: 'No content response with options headers.' })
  options(ctx: Context) {
    const response = new HttpResponseNoContent();
    response.setHeader('Access-Control-Allow-Headers', 'Content-Type,Authorization,X-Requested-With');
    response.setHeader('Access-Control-Allow-Methods', 'GET,POST,PUT,PATCH,DELETE,OPTIONS');
    return response;
  }
```

**Comment by LoicPoullain** [comment]
Sorry for the late reply. I wanted to [read again](https://www.html5rocks.com/en/tutorials/cors/) on CORS and make some tests on different browsers (Firefox, Chrome, Edge, Safari) before replying back. I continue the conversion on the PR you opened.

> I think the status response of your API description is 204 in this case :wink:

**Comment by Bishnupandey22** [comment]
> I came across some problems while using the rate limiter on API endpoints with CORS.
> 
> Basically you have to use the `express-rate-limit`'s `handler` [function](https://github.com/nfriedly/express-rate-limit#handler) to set the headers, otherwise they don't get set at all because the response from the rate limiter doesn't get handled by FoalTS.
> 
> I am setting the headers FoalTS sets in its `createApp`-function manually in the handler. Currently my rate limiter setup looks like this:
> 
> ```ts
> expressApp.use(rateLimit({
>       windowMs: 15 * 60 * 1000,
>       max: 50,
>       skip: req => req.method.toUpperCase() === 'OPTIONS',
>       message: {
>         status: 'error',
>         description: 'Too many requests. Please try again later.'
>       },
>       handler: function (req, res, next) {
>         // FoalTS Headers
>         res.removeHeader('X-Powered-By');
>         res.setHeader('X-Content-Type-Options', 'nosniff');
>         res.setHeader('X-DNS-Prefetch-Control', 'off');
>         res.setHeader('X-Download-Options', 'noopen');
>         res.setHeader('X-Frame-Options', 'SAMEORIGIN');
>         res.setHeader('X-XSS-Protection', '1; mode=block');
>         res.setHeader('Strict-Transport-Security', 'max-age=15552000; includeSubDomains');
>         res.setHeader('Access-Control-Allow-Headers', 'Content-Type,Authorization,X-Requested-With');
> 
>         // CORS
>         res.setHeader('Access-Control-Allow-Methods', 'GET,POST,PUT,PATCH,DELETE,OPTIONS');
>         res.setHeader('Access-Control-Allow-Origin', '*');
> 
>         // Send this response for rate limited requests
>         res.status(this.statusCode!).send(this.message);
>       }
>     }));
> ```
> 
> Is this maybe related to #384 and #472 and we should update the docs accordingly or can this be handled somehow with FoalTS CORS hooks?
> 
> Which response headers should be set on the rate limiter response?

align like this 
const limiter = rateLimit({
        windowMs: 1 * 60 * 1000, // 1 minutes
        max: 100, // Limit each IP to 100 requests per windowMs
        message: 'Too many requests from this IP, please try again after 3 minutes',
        statusCode: 429,
        onLimitReached: (req, res, options) => {
            res.status(429).json({
                error: 'Rate limit exceeded'
            });
        }

    });
app.use(cors())
app.use(limitor())
first write the cors and then the limitor
