### ISSUE TITLE
Swagger UI Dist Config

### ISSUE THREAD

**Issue by kingdun3284** [FoalTS/foal#486]
Temporary solution:
...open-api.controller.ts
```
 @Get('/')
  async index(ctx: Context) {
    ...
    const template = await promisify(readFile)(join('your_custom_index_template_path/index.tpl.html'), 'utf8');
    ...
}
```
...your_custom_index_template/index.tpl.html
```
...
const ui = SwaggerUIBundle({
        {{ urls }},{{ primaryName }}
        dom_id: '#swagger-ui',
        deepLinking: true,
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset
        ],
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ],
        layout: "StandaloneLayout",
        ...more config here
      })
...
```
I think this is quite inconvenience now. Maybe we should add swaggerui option in the option of opneapi if we are still using swagger-ui-dist? Or maybe adding this tutorial to cookbook if nothing is gonna change in short time?

**Comment by LoicPoullain** [comment]
Thank you for reporting this!

If I understand well, you'd like to pass more options to `SwaggerUIBundle`. Can you give an example of the options you're adding?

**Comment by kingdun3284** [comment]
I added docExpansion:"none" only. Currently I override the get method of openapi controller that extends from swaggercontroller(from @foal/swagger) to render a custom index.tpl.html with different SwaggerUIBundle config. I think those configs of swaggeruibundle can be added to the options of swaggercontroller and dynamically render the index.tpl.html if we are still using swagger-ui-dist.

**Comment by LoicPoullain** [comment]
Ok, I see. I took a look at the [Swagger documentation](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/) as well, most of the options can be "stringified".

Here how I see how to update to the `SwaggerController`:
```typescript
export abstract class SwaggerController {
  // ...

  abstract options: ... // Current options that are used both to render the templates and determine the route behaviors.

  uiOptions: object = {} // Additional swagger UI options that can be override.

  // ...
}

// Example
class DocumentationController extends SwaggerController {
  options = { controller: ApiController };

  uiOptions = { docExpansion: 'none' };
}
```

To implement this, we need to:
- Update `index.tpl.html`.

    ```javascript
    const ui = SwaggerUIBundle(Object.assign({
       // Current content
    }, {{ uiOptions }}));
    ```

- Update the files `index.*.spec.html` (that test template renders for each scenario) to end with:

    ```javascript
    }, {}));
    ```

- Add two new tests to `swagger-controller.spec.ts`:

  `SwaggerController` > `has a "index" method that` > `should properly render the template given options are { url: "xxx" } and uiOptions are { docExpansion:"none" }.`. Spec file to add: `index.url.ui-options.spec.html`.

  `SwaggerController` > `has a "index" method that` > `should properly render the template given options are [{ url: "v1.json", name: "v1" }] and uiOptions are { docExpansion:"none" }.` Spec file to add: `index.no-primary.ui-options.spec.html`.

- Finally update `swagger-controller.ts` to use the `uiOptions` with `JSON.strifigify` (lines 94 & 109)

**Comment by LoicPoullain** [comment]
@kingdun3284 do you want to submit a PR or do you want me to do it? Both are fine with me.

**Comment by kingdun3284** [comment]
@LoicPoullain 
I can try if you have no time. I don't want to pollute your code, haha :)

**Comment by LoicPoullain** [comment]
Don't worry! The PR does not require to add too much code. The two new tests are pretty much a copy-past of old ones as well as the new template specs. If you feel like to take it, I'll assign it to you.

`should properly render the template given options are { url: "xxx" } and uiOptions are { docExpansion:"none" }` inspired from `should properly render the template given options are { url: "xxx" }`

`should properly render the template given options are [{ url: "v1.json", name: "v1" }] and uiOptions are { docExpansion:"none" }` inspired from `should properly render the template given options are [{ url: "v1.json", name: "v1" } ...]`

`index.url.ui-options.spec.html` inspired from `index.url.spec.html`

`index.no-primary.ui-options.spec.html` inspired from `index.no-primary.spec.html`
