### ISSUE TITLE
Problem with circular dependencies in services - Cannot read property 'isServiceManager' of undefined

### ISSUE THREAD

**Issue by squareloop1** [FoalTS/foal#488]
If we have two services which depend on each other, the `@dependencies` decorator doesn't seem to initialize the dependencies correctly:

```typescript
class AService {
  @dependency bService: BService;
}

class BService {
  @dependency aService: AService;
}
```

It throws a runtime error: `TypeError: Cannot read property 'isServiceManager' of undefined`

Is this a bug or do I get the concept wrong somehow? If I do get it wrong, what could a workaround look like?

**Comment by LoicPoullain** [comment]
I assume that the two services are located in different files that import each other. If so, one the references to `BService` or `AService` is undefined in one of the files. This is why there is an error at runtime.

The service manager is not designed to support circular dependencies. A workaround is to create a third service and move to this service the functions/attributes that are used both by A and B:

```typescript
class CService {
  // Some code that was previously in AService and BService.
}

class AService {
  @dependency cService: CService;
}

class BService {
  @dependency cService: CService;
}
```

**Comment by squareloop1** [comment]
Yes, I guess that makes sense. Thank you!
