### ISSUE TITLE
Improve developper experience with scripts and migrations

### ISSUE THREAD

**Issue by LoicPoullain** [FoalTS/foal#494]
**Previous issue name**: Make "foal run" build and run the script

# Issue

As mentioned in #467, in development, it is tedious to always have to run `npm run build:scripts` before `foal run xxx`.

# ~~Solution~~

~~Add a configuration key `settings.scripts.autoBuild` which, when set to true, tells the `foal run` command to build the script before.~~

~~This behavior could be override with the flag `--no-build` (note: update the three `foal run create-user` in the tutorial).~~
```
foal run --no-build my-script
```

~~Each new project will have a `.env` file with the configuration set to true.~~
```
SETTINGS_SCRIPTS_AUTO_BUILD=true
```

~~Since this file is not commited, the command `foal run` won't try to build the scripts on deployed servers.~~

**Comment by LoicPoullain** [comment]
Actually we have the same problem with the migrations.

**Comment by LoicPoullain** [comment]
Maybe the simpler solution could be to just extend the `npm run develop` command to the directory `scripts` and `migrations`. So the scripts and migrations will be compiled each time a file is changed.

This would also remove `tsconfig` files (`tsconfig.migrations.json` and `tsconfig.scripts.json`).

**Comment by opensas** [comment]
Yeap, I agree, I can't think about a case in which I would NOT want the compiled js files to be overwritten. build folder should sctrictly be the product of the rest of the files, so it should always be ok to prune it and regenerate it from sources.
Do you have different tsconfig.xxx.json files just to make it faster? In that case you might consider (and benchmark) using tsc incremental option.

**Comment by LoicPoullain** [comment]
> Do you have different tsconfig.xxx.json files just to make it faster? In that case you might consider (and benchmark) using tsc incremental option.

Yes the first idea of having three separate tsconfig for the migrations, scripts and application was to make the compilation faster. But I'm not sure this is really true since `scripts` and `migrations` do not contain a ton of files. I have in mind to merge these three config files into a single one in Foal version 2 (this year) and so have a single command `npm run develop` to build the app, scripts and migrations in watch mode.

**Comment by opensas** [comment]
I would be great to have an out of the box solution for recompiling a ts app as fast as possible in dev mode, there are many options available
On the other hand, it's great to know a version 2 is on the way. I hope you can find some time to tell us your experience developing version1 and your plans for the next version. FInding a way to get feedback from the community about what features they would like to have in foal 2 would be great too
keep up the good work!

**Comment by LoicPoullain** [comment]
@opensas yes I have a draft that describes version 2.  I'll open an issue on this when I'll get a chance. The main idea of v2 will be to remove some hacky solutions and technical debts that require some breaking changes.

**Comment by LoicPoullain** [comment]
Feature added in v2 (version will be released in the summer).
