### ISSUE TITLE
Config: support .env.testing and .env.e2e files

### ISSUE THREAD

**Issue by LoicPoullain** [FoalTS/foal#497]
# Issue

Currently, Foal's configuration system supports environment variables, the `.env` file and JSON and YAML files in the `config/` directory. In some situations, we may also want to have another uncommitted file `.env.testing` to store db credentials during testing.

# Solution

Support `.env.{NODE_ENV}` files

**Comment by yaaminu** [comment]
@LoicPoullain I'm struggling to understand the utility of this since there's already a comprehensive way for adding configruations to a foal app. I suggest we stick to the existing approach and add a new `test.{yml|json}` file for test environments.

**Comment by LoicPoullain** [comment]
This will allow us to split sensitive information and simple settings in two different files if we want to (one committed and the other not). There is no obligation to use this approach and we will still be able to only use `test.{yml|json}` files if we prefer.

Another use case can be to start the app with our production DB. For example, by adding a `.env.production` file with the credentials and running the command `NODE_ENV=production npm run start`.

This is not a priority though. I'll remove it from August release to focus on social auth.

**Comment by LoicPoullain** [comment]
Resolved in v2
