### ISSUE TITLE
any plan of support fastify

### ISSUE THREAD

**Issue by cocodrino** [FoalTS/foal#500]
foalTs seems great but something that I'd miss from nestjs is the support for fastify, fastify provides a great performance improve over express, do you have plan support this in a future?...maybe like an alternative framework base similar to nestjs?

thank you.

**Comment by LoicPoullain** [comment]
Hi Carlos,

Thank you for your interest! 

In which situation do you find FoalTS/Express too slow? Do you have something in mind?

Thanks!

**Comment by digitalit** [comment]
Also interested in Fastify with FoalTS.

Any chance you will implement this?

Have some customers that want Fastify and i would like to use FoalTS instead of NestJS.

Thank you.

**Comment by cocodrino** [comment]
@LoicPoullain if you can get a performance improve without any code change almost every developer will choose the fast option and fastify has show a not despreciable performance improvement over express

https://blog.logrocket.com/forget-express-js-opt-for-these-alternatives-instead/
https://medium.com/sharenowtech/there-are-expressjs-alternatives-590d14c58c1c
https://medium.com/@onufrienkos/express-vs-fastify-performance-4dd5d73e08e2

**Comment by LoicPoullain** [comment]
A first glance, I'm not convinced that Fastify will provide more advantages than it adds constraints / complexity to the framework.

When I looked at Fastify more closely a few months ago, there were some incompatibilities with Express that could make several built-in hooks not work with Fastify.

Also, I'm not sure than using it will really increase performance:
- All benchmarks that I could read on *Fastify vs Express* didn't actually test a *real* application in production. They all use a simple *Hello world* example with a simple route that returns static content. The gain in a production environment may be negligible compared to other parts of the application that consume more time (database requests, etc). The 20% of gain may be reduced to just a few percentage in that case.
- Compared to other frameworks such as Nest, FoalTS only uses Express as a thin underlay of the framework core. Foal does not allow developers to use Express middlewares but _hooks_.   The framework resolves and manages the routing and execution of controllers and hooks itself without using Express routers. I _feel_ like Fastify only improves the performance of routing management and middlewares execution.

**Comment by LoicPoullain** [comment]
Following the previous comment, I’m closing this issue.
