### ISSUE TITLE
【Nuxt】Does Foal support Nuxt middleware?

### ISSUE THREAD

**Issue by Fnxxxxo** [FoalTS/foal#502]
I try integrating Nuxt with Foal, using Foal starter like
```typescript
import 'source-map-support/register'

// std
import * as http from 'http'

// 3p
import { Config, createApp } from '@foal/core'
import { connect } from 'mongoose'

// App
import { AppController } from './app/app.controller'
import express from 'express'
import Consola from 'consola'
import { Nuxt, Builder } from 'nuxt'
import config from '../nuxt.config'

const app = express()

// Import and Set Nuxt.js options
config.dev = process.env.NODE_ENV !== 'production'

async function main() {
  // Init Nuxt.js
  const nuxt = new Nuxt(config)
  const { host, port } = nuxt.options.server

  // Build only in dev mode
  if (config.dev) {
    const builder = new Builder(nuxt)
    await builder.build()
  } else {
    await nuxt.ready()
  }

  // Connect DB
  const uri = Config.get<string>('mongodb.uri')
  connect(uri, { useNewUrlParser: true, useCreateIndex: true })

  let server = createApp(AppController, app)
  server = http.createServer(server)

  // Give nuxt middleware to express
  app.use(nuxt.render)

  const serverPort = Config.get('port', port)
  server.listen(serverPort, host, () => {
    Consola.ready({
      message: `Server listening on http://${host}:${port}`,
      badge: true
    })
  })
}

main()
```
But it results in 404 for the index route. It seems the controller close the stream if no method is matched. Only /api is available. Are any suggestion or demo ?

**Comment by LoicPoullain** [comment]
Hi @Fnxxxxo 

Sorry for the late reply. This is not working because `createApp` takes care of returning 404 and 500 errors before `app.use(nuxt.render)` gets called.

> It seems the controller close the stream if no method is matched.

Correct.

Currently, there is no quick solution to make it work. Nuxt.js seems a great framework, as well as Next, and we should definitively have an easy way to integrate them with Foal.

I'll think how to have a clean and straightforward solution to use them in the next few weeks. We should probably have something for this in August or September releases. :+1:

**Comment by Fnxxxxo** [comment]
@LoicPoullain That would be a great enterprise SSR solution for the Vue community.

**Comment by elshazer** [comment]
I have always generated static sites with nuxt js
I recommend using `$ nuxt generate`

In the file frontend `nuxt.config.js` add
```
   generate: {
     dir: '../backend/public'
   },
```

Also I suggest you using axios
https://axios.nuxtjs.org/options#proxy

**Comment by Fnxxxxo** [comment]
@elshazer I am developing a CMS client which use dynamic routes. So static generating is hard to implement for me.

**Comment by LoicPoullain** [comment]
Feature added in v1.1.0
