### ISSUE TITLE
validate-params hook, open api spec auto generation problem

### ISSUE THREAD

**Issue by kingdun3284** [FoalTS/foal#503]
```typescript
@ValidateQuery({
    properties: {
      'select': { type: 'array', items: {type: 'string'}},
    },
    type: 'object'
  },{openapi:true})
```
<img width="268" alt="Capture" src="https://user-images.githubusercontent.com/6995317/62687206-dfd7ca80-b9f8-11e9-8e27-2897c92ccd40.PNG">
<img width="376" alt="Capture2" src="https://user-images.githubusercontent.com/6995317/62687210-e1a18e00-b9f8-11e9-940e-baba2a8b7181.PNG">

If only one item is added, it will not pass the validation and treat it not as an array.

**Comment by LoicPoullain** [comment]
It may be related to how Express parses query params or to how OpenAPI spec may differ from JSON schema spec. I'll need more information on this.

Can you give me another example (which is working) with several items and take a screenshot as well of what you specify in Swagger?

Also, for both examples (one vs many), can you copy the actual URLs that the server receives?

**Comment by kingdun3284** [comment]
> It may be related to how Express parses query params or to how OpenAPI spec may differ from JSON schema spec. I'll need more information on this.
> 
> Can you give me another example (which is working) with several items and take a screenshot as well of what you specify in Swagger?
> 
> Also, for both examples (one vs many), can you copy the actual URLs that the server receives?
```
@ValidateQuery({
    properties: {
      'select': { type: 'array', items: {type: 'string'}},
    },
    type: 'object'
  },{openapi:true})
```
![Capture3](https://user-images.githubusercontent.com/6995317/62753539-b40f2000-ba9e-11e9-8d48-e112eaa02b76.PNG)
![Capture4](https://user-images.githubusercontent.com/6995317/62753541-b5d8e380-ba9e-11e9-80dd-f7a444a22b47.PNG)

I agree, it should be how OpenAPI spec may differ from JSON schema spec.

**Comment by LoicPoullain** [comment]
In this case, the problem comes from how Express creates the `query` object:

- `?a=3` => `query === { a: '3' }`
- `?a=3&a=2` => `query === { a: ['3', '2'] }`

The `@ValidateQuery` hook just validates the created `query` object against the given schema.

One way to get around this could be to add another hook before:
```typescript
@Hook(ctx => {
  if (typeof ctx.request.query.select === 'string') {
    ctx.request.query.select = [ ctx.request.query.select ];
  }
})
@ValidateQuery(...)
```
