### ISSUE TITLE
Please default response to `HttpResponseOK`.

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [FoalTS/foal#505]
It's only 10 mins that I am wandering around this framework. Everything seems solid as I wanted. But one thing is pretty ugly. It's so ugly that I feel forced to create an issue. Please wrap returned value in `HttpResponseOK` if it (the returned value) is not instance of root response class (whatever `HttpResponseOK` ultimately inherits from)

Instead of 
```ts
return new HttpResponseOK('Hello world!');
```
I'd like to write simply: 
```ts
return 'Hello world!';
```

**Comment by TekinGomes37** [comment]
I do not find ugly, everything, because like that, it's clear as "bonjour", if we want to return a HttpResponseOk (), HttpResponseCreated (), HttpResponseBadRequest ({"message": "best ^^"]).

**Comment by OrkhanAlikhanov** [comment]
Yeah, to add some syntactic sugar to the framework, one of the responses should be default, and I think mostly `HttpResponseOk` is returned from an endpoint.

**Comment by LoicPoullain** [comment]
I need to think about this and see all the implications this might involve. In the meantime, if it is relevant, you can also use the function below to reduce the length of the code.

```typescript
function ok(content) {
  return new HttpResponseOK(content);
}

...

return ok('Hello world!');
```

**Comment by OrkhanAlikhanov** [comment]
Again laravel does that :]. See https://laravel.com/docs/5.8/responses

<sup>You might've already fed up hearing laravel from me lol</sup>

**Comment by LoicPoullain** [comment]
I'm closing this issue. I believe that this feature would make it more difficult to maintain the overall framework, as it would introduce a special case to be dealt with in many situations.
