### ISSUE TITLE
No way to configure express.static

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [FoalTS/foal#509]
I'd like to disable default index.html serving on route `/` and serve html through rendering. This is possible by passing `{ index: false }` to `options` of `express.static(path, options)`. There seems to be no way to do that:

https://github.com/FoalTS/foal/blob/647ea2da8d8f8176710215c691647e302f346b55/packages/core/src/express/create-app.ts#L47

**Comment by LoicPoullain** [comment]
Why not simply delete the `index.html` file?

**Comment by OrkhanAlikhanov** [comment]
Well, I was rendering on top of it like `return render('./public/index/html', { payload })`. Never thought about renaming `index.html` file 🤔 Sounds like it would work. Thank you!

<sup>You can close this if you want</sup>

**Comment by LoicPoullain** [comment]
👍 

Usually, templates would be placed in a separate directory `templates/` at the root of your project or next to your controllers. `public/` should only contain static files.

*Example 1 (root directory)*
```
|- public/
|- src/
'- templates/
  '- index.html
```

```typescript
render('./templates/index.html', { payload })
```

*Example 2 (`controllers/` directory)*
```
|- public/
'- src/
  '- app/
    '- controllers/
      |- templates/
      |  '- index.html
      '- my.controller.ts
```

```typescript
render('./templates/index.html', { payload }, __dirname)
```
