### ISSUE TITLE
DI service not available in constructor

### ISSUE THREAD

**Issue by squareloop1** [FoalTS/foal#516]
I need to initialize a websocket listener and want to do it in the constructor of the main AppController:

```typescript
export class AppController {
  @dependency websocketService!: WebsocketService;

  constructor() {
    this.websocketService.listen();
  }
}
```

It seems like the service is not yet injected at the time I call it in the constructor. Is there a common approach on how to handle this with DI in FoalTS?

**Comment by LoicPoullain** [comment]
> It seems like the service is not yet injected at the time I call it in the constructor.

Correct.

> Is there a common approach on how to handle this with DI in FoalTS?

For now, you can do it in `src/index.ts` by retrieving the service like this:

```typescript
const app = createApp(AppController);
app.foal.services.get(WebsocketService).listen();
```

This is pretty ugly, but may it solve your issue in this case?

For the future, I was thinking of adding an `init` method in the `AppController` (or even in each service) that would be called after instantiations and DI. If the method does not exist, no error would be thrown. This way, it would also make it easier to test the *initialization* during unit testing. What do you think?

**Comment by squareloop1** [comment]
Yes, the approach in `src/index.ts` seems to work for now. I am using the services in other parts of the application too with the standard dependency injection approach. Will FoalTS handle the created services in `src/index.ts` as singletons anyway?

The init method would be nice to be able to do some stuff outside of the normal controller routing.

**Comment by LoicPoullain** [comment]
> Will FoalTS handle the created services in src/index.ts as singletons anyway?

Yes. `services.get` does not re-instanciate the services. It fetches the singletons in the same way as you would do with `@dependency`.

**Comment by LoicPoullain** [comment]
Even if a controller is not a service, you can also still retrieve the same way.

```typescript
const app = createApp(AppController);
app.foal.services.get(AppController).init();
```

```typescript
export class AppController {
  @dependency a: A;
  @dependency b: B;

  init() {
    this.a.doSomething();
    this.b.doSomething();
  }
}
```

**Comment by squareloop1** [comment]
Ok, great! Thanks alot, this seems to work for now.
