### ISSUE TITLE
How to test a post hook function?

### ISSUE THREAD

**Issue by squareloop1** [FoalTS/foal#526]
How can post-hook functions be tested? I have a hook transforming my response. I would like to test the transformed response and its contents.

Maybe this is a good addition for the docs?

**Comment by LoicPoullain** [comment]
Yes, the documentation is missing an example on this one. Here is how to do that:

```typescript
const postHookFunction = await hook(ctx, services);
if (postHookFunction === undefined || isHttpResponse(postHookFunction)) {
  throw new Error('The hook should return a post hook function');
}

const response = new HttpResponseOK();
await postHookFunction(response);

strictEqual(response.getHeader('XXX'), 'YYY');
```
