### ISSUE TITLE
Community/chat channel for this project

### ISSUE THREAD

**Issue by sgronblo** [FoalTS/foal#527]
Is there some gitter, slack, irc channel, etc for this project?

**Comment by squareloop1** [comment]
Afaik there is none yet. But it would be very nice.

**Comment by sgronblo** [comment]
Wouldn't it be super trivial to set up a gitter room?

**Comment by LoicPoullain** [comment]
Sounds like a good idea. Any preference on the channel to use? I feel like Slack is much more simpler to understand and use (especially on small screen) than Gitter.

**Comment by rustamwin** [comment]
Slack is good choice

**Comment by OrkhanAlikhanov** [comment]
Slack is great, you'll have to set up an auto-inviter though. Like this: https://github.com/outsideris/slack-invite-automation

**Comment by sgronblo** [comment]
I usually prefer Gitter. It’s frustrating to have to add yet another slack just to get in touch with a projects maintainers.

**Comment by silentworks** [comment]
I am fine with Slack or Discord.

**Comment by squareloop1** [comment]
Discord would be a nice alternative to Slack too. Many other libraries and frameworks use it too.

**Comment by sgronblo** [comment]
I would prefer Discord to Slack, since you can at least join that freely.

**Comment by kingdun3284** [comment]
Prefer discord more than slack.

**Comment by sgronblo** [comment]
Anyway, I think this project seems promising but it would be great if there was any kind of chat channel for now to ask questions about the project directly.

**Comment by sgronblo** [comment]
My preference would be:

1. Gitter
2. Discord
3. IRC
4. Slack

Seems like Discord has the most votes so far. Could some maintainer make this happen?

**Comment by LoicPoullain** [comment]
Ok so I took a look at the different solutions to choose one. The idea would be to have something that is easy to join, to use/read and where syntax highlighting is handled nicely (for sharing code).

1. **Gitter** lets us read conversions publicly and its signup/login system with Github makes things really simple to join the chat. However, IMO the interface is not really user-friendly and I find it hard to understand how the application works and how to use channels. The application does not really display well on small screens.
2. **Slack**. *Pros*: very popular, everyone knows it and most people know how to use it, many features. *Cons*: No inline syntax highlighting and the way to manage several workspaces is not really user-friendly. *Really annoying*: the invitation system. Slack is not designed for public community and having to maintain an external server/app to support auto-invitation is extra work and time wasted.
3. **Discord**. *Cons*: Not really known (at least in developer communities) and dedicated to gaming (which may seem weird to people that want to join the chat). *Pros*: seems to be the preferred choice in this issue, similar to Slack and really easy to use, inline syntax highlighting, permanent invite link.

So, I created a new *server* (= *Slack workspace*) using **Discord** app. Here is the permanent link to get access to it: https://discord.gg/QUrJv98. Please, could you confirm that:
- you have to enter an email to access the room (to avoid spam),
- there is no French word (all is in English or in your native language),
- you can write messages,
- you cannot write messages in the #annoucements channels (only react using emoticons)?

Thank you for your involvement!

**Comment by squareloop1** [comment]
Nice. Thank you.

Can't say anything about the other options, but I know there are a lot of dev communites and libraries on Discord. Some of them even switched to Discord from Slack (i think because of the user limits, its free and unlimited chat history).

For example some channels that may be interesting:
Vue Land
Vuetify / Buefy
SpeakJS
Devcord

**Comment by LoicPoullain** [comment]
Thanks @squareloop1!

**Comment by LoicPoullain** [comment]
The invitation link is on the README page. Closing this.
