### ISSUE TITLE
Is there a router file?

### ISSUE THREAD

**Issue by webcoderkz** [FoalTS/foal#530]
For example, if i want to use SSR templates (render views from backend), do i use decorators in a controller to create a routes?, there's not a single place with all routes?

**Comment by OrkhanAlikhanov** [comment]
If you want to capture all get routes, just use '*': 
```ts
class SSRController {
  @Get('*')
  allRoutes(ctx) {

  }
}
```

**Comment by LoicPoullain** [comment]
There is no "router file" but you can organize your controllers as follows for SSR:

```typescript
export class AppController {
  subControllers = [
    ...,
    controller('', ViewController)
  ];
}
```

```typescript
export class ViewController {
  @Get('/')
  index() {
     return render(...);
  }

  @Get('/admin')
  admin() {
     return render(...);
  }

  ...
}
```

If you want to specify all your routes in one place (the `app.controller.ts` file), then you'll have to create a controller for each of your route.

```typescript
export class AppController {
  subControllers = [
    controller('/', IndexController)
    controller('/admin', AdminController)
  ];
}
```

```typescript
export class IndexController {

  @Get()
  index() {
     return render(...);
  }

}
```

**Comment by LoicPoullain** [comment]
I'm closing this issue since it seems to have been answered. Feel free to reopen it if it is not the case.
