### ISSUE TITLE
Please update the ajv version of @foal/core

### ISSUE THREAD

**Issue by kingdun3284** [FoalTS/foal#532]
I want to use the feature of "nullable:true" from ajv and I found that it is not supported in version 6.5.0 which foal/core is using now.

**Comment by LoicPoullain** [comment]
Foal uses version 6.5 or greater (6.6, 6.7, etc). Can you try `npm install ajv`? It should install version 6.10. If this does not work, delete your `node_modules/` directory and your `package-lock.json` and reinstall them with `npm install`

**Comment by kingdun3284** [comment]
I have found the problem, it's because of foal's config not reading the extra setting of ajv. This is my setting. How to solve it then?
```
{
  "settings": {
    "ajv":{
      "coerceTypes":false,
      "removeAdditional":"all",
      "useDefaults":false,
      "nullable":true
    }
}

```

**Comment by LoicPoullain** [comment]
I opened a PR to fix that. Version 1.1.0 will be released this week.

**Comment by LoicPoullain** [comment]
Feature added in v1.1.0
