### ISSUE TITLE
Injecting repository instances into services

### ISSUE THREAD

**Issue by sam-gronblom-rj** [FoalTS/foal#538]
If this is already possible it would be nice to have a mention of it in the docs.

I am currently trying out Foal and trying to set up integration testing that would rely on a database. I want to run the database in Docker so that I don't need to worry about how to clear out the database. I will just spin up a completely new db container for each test case. This would also allow for running tests concurrently since the DBs are separate for each test.

However since the documentation currently recommends using either the global `typeorm.getRepository` or `connection.manager.getRepository` it's a bit unclear how to specify for which connection the requested repository will be created.

I would prefer to be able to pass in the connection to the functions `createApp`/`createController`/`createService` and be able to just say `@dependency SomeEntityRepository: Repository<SomeEntity>` in my service.

Is something like this possible?

**Comment by OrkhanAlikhanov** [comment]
You can try following:

_**index.ts**_
```ts
const app = createApp(AppController);
app.foal.services.set(Repository<SomeEntity>, getRepository(SomeEntity));
```

**Comment by LoicPoullain** [comment]
With version 1.2.0 and its new `AppController.init` method, you will be able to create a service to inject TypeORM connection. This way, it will be possible to use DI for the connection during testing.

```typescript
class ConnectionService {
  connection: Connection;

  getRepository<Entity>(target: ObjectType<Entity> | EntitySchema<Entity> | string): Repository<Entity> {
   return this.connection.getRepository<Entity>(target);
  }
}
```

```typescript
class AppController {
  @dependency
  connection: ConnectionService;

  async init() {
    // This method will be available only starting from v1.2.0.
    this.connection = await createConnection();
  }
}
```

```typescript
class MyController {
  @dependency
  connection: ConnectionService;

  @Get('/products')
  readProducts() {
    return this.connection.getRepository(Product).find();
  }
}
```

```typescript
// Testing
const connection = await createConnection();
const controller = createController(MyController, {
  connection: { connection }
});
```

**Comment by LoicPoullain** [comment]
I'm closing this issue since v1.2.0 has been released. Feel free reopen it if this is still a problem for you.

**Comment by LoicPoullain** [comment]
Injecting `@Dependency() SomeEntityRepository: Repository<SomeEntity>` in a service is now possible in v1.8 onwards.
