### ISSUE TITLE
Feature Request: hashPassword and verifyPassword should offer support for salting

### ISSUE THREAD

**Issue by ibnIrshad** [FoalTS/foal#549]
Passwords should not just be hashed, but ideally also salted. The built-in password auth scheme in FoalTS should support it with an additional saltString parameter.

**Comment by LoicPoullain** [comment]
Hi @ibnIrshad 

The documentation is incomplete. The `hashPassword` function does both hash and salt passwords. A random salt is generated for each password and is saved with the hash in the database.

Password hashing and salting are managed in a similar way as [Django framework](https://www.djangoproject.com/) does.
