### ISSUE TITLE
[FEATURE REQUEST] Allow custom templates for code generation

### ISSUE THREAD

**Issue by yosbelms** [FoalTS/foal#550]
Default code generation should be simple, just a starting point. But, if I want the generated code to be more domain specific, I would like to have the flexibility of:

- To create my own templates.
- To publish and reuse community templates.

Example: `create-react-app`

It should be either passed through CLI params, or live in some config entry, or both

**Comment by LoicPoullain** [comment]
Thank you for your suggestion @yosbelms and sorry for the late reply.

Why do you mean by mentioning `create-react-app` as an example?

**Comment by LoicPoullain** [comment]
@yosbelms Thank you for your suggestion. I've thought about it and I don't think it's a priority at the moment. I prefer to focus on other things. That's why I'm going to close this issue. Thank you for your interest!
