### ISSUE TITLE
MongoDB connection timeout - Remote server with username/password

### ISSUE THREAD

**Issue by crossinghoods** [FoalTS/foal#556]
While trying to do the MongoDB ToDo List example - (https://foalts.gitbook.io/docs/tutorials/mongodb-to-do-list)

The project would not connect to my remote mongodb server.

Console error message
-------------------------
(node:87245) UnhandledPromiseRejectionWarning: MongoTimeoutError: Server selection timed out after 30000 ms
    at Timeout.setTimeout (/Users/test-user/Desktop/testapp/node_modules/mongodb/lib/core/sdam/topology.js:878:9)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:87245) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:87245) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Config/default.json
------------
{
  "port": 3001,
  "settings": {
    "csrf": false,
    "debug": false,
    "loggerFormat": "tiny",
    "staticPath": "public/"
  },
  "mongodb": {
    "uri": "mongodb://root:password@db.servername.com:27017/testdb"
  }
}

Environment
-------------
MacOS
Node v10.16.3

**Comment by crossinghoods** [comment]
1) I haven't tried it with a local MongoDB database, but the remote MongoDB server is definitely working.  I've successfully to connect to it with Robo 3T (3rd party software) and have tested it with other frameworks whilst testing out FoalTS.

>2.  Could it be related to this issue: Automattic/mongoose#8180? Can you try to remove the useUnifiedTopology option?

I'm not too sure how to set this option with FoalTS - documentation is a bit lacking on possible configurations in FoalTS atm.  

Not sure if the following debug logs will be helpful
----------------------------------------
Debugged _node_modules/mongodb/ module_ 

console.log output from > /node_modules/mongodb/lib/core/sdam/server.js (line 143) > connect() > poolOptions (Note: servername / password etc. have been changed to dummy names here for privacy purposes) - details seemed to have been passed down successfully.

[1]   monitorCommands: false,
[1]   servers: [ { host: 'db.servername.com', port: 27017 } ],
[1]   caseTranslate: true,
[1]   useNewUrlParser: true,
[1]   useUnifiedTopology: true,
[1]   promiseLibrary: [Function: Promise],
[1]   auth:
[1]    { username: 'root',
[1]      password: 'xxxpasswordxxx',
[1]      db: 'DATABASENAME',
[1]      user: 'root' },
[1]   authSource: 'DATABASENAME',
[1]   dbName: 'DATABASENAME',

**Comment by crossinghoods** [comment]
I figured out what was the issue!

It just needed an extra parameters to work - telling mongodb which database table does the authentication
"mongodb://root:password@db.servername.com:27017/testdb?authMechanism=SCRAM-SHA-1&**authSource=admin**"

authMechanism is just in case if other people want to update the auth mechanism - but SCRAM-SHA-1 is the default

**Comment by LoicPoullain** [comment]
For those who come across this issue when doing their research, timeout problems may come from the new version of the mongodb package: https://github.com/mongodb/node-mongodb-native/releases/tag/v3.3.4
