### ISSUE TITLE
Thoughts on imporving workflow in using MongoDB with typescript

### ISSUE THREAD

**Issue by darekaze** [FoalTS/foal#559]
This is just a suggestion of improving the workflow when working with MongoDB and typescript.

Currently, Foal uses `mongoose` to define modals and we need to define the types two times: one in mongoose and one using typescript interface. As well as we need to maintain both of them.

An example can be shown in the current [MongoDB Todo-list tutorial](https://foalts.gitbook.io/docs/tutorials/mongodb-to-do-list/3-the-todo-model):
```javascript
import { Document, model, Model, models, Schema } from 'mongoose';

const todoSchema: Schema = new Schema({
  text: {
    required: true,
    type: String // String with a capital letter
  }
});

export interface ITodo extends Document {
  text: string; // string a lowercase letter
}

export const Todo: Model<ITodo> = models.Todo || model<ITodo>('Todo', todoSchema);
``` 

Also in this case, if we want to add GraphQL to a project, it would be hell cause we need to define another types in gql schema while also maintaining it (i.e. in total we need to handle three same types..)

So I thought why not replace mongoose with something like TypeORM but with fully-support of MongoDB?

Doing some research and I found two solutions that could probably make Foal dev experience better:

1. [Typegoose](https://github.com/typegoose/typegoose) - This is basically the TS version of `mongoose` which is similar to TypeORM but for MongoDB, and it plays well with TypeGraphQL, so you will define all your types in one place using decorators.

2. [Mikro-ORM](https://github.com/mikro-orm/mikro-orm) - I found this by opportunity while searching for ORM solutions in different communities. Tried it while I was attempting to write my private graphql backend with MongoDB behind it. I would say it works so smoothly and it fully supports MongoDB and SQL databases as well as integrates well with TypeGraphQL. Also, it claims to be better than TypeORM as it is based on Data Mapper. Learn more in the [author's post](https://medium.com/dailyjs/introducing-mikro-orm-typescript-data-mapper-orm-with-identity-map-9ba58d049e02) and also its well-written [docs](https://mikro-orm.io/).

And I think if Foal can leverage Mikro-ORM, it would be easier to maintain as the team only needs to maintain one extension instead of two (TypeORM and mongoose). And basically doing this would be a bit opinionated just like `Adonis` did for their ORM solution.

And again, this is just my idea trying to make Foal better, and I would like to hear from others about this topic.

**Comment by LoicPoullain** [comment]
Version 2 will use TypeORM as default ODM for MongoDB (see PR).
