### ISSUE TITLE
`foal connect`: projects "connected" on Windows do not build on unix systems

### ISSUE THREAD

**Issue by LoicPoullain** [FoalTS/foal#562]
# Issue

When running the tests on the CLI on Windows, I noticed that some of them failed because `connect vue` and `connect angular` update the frontend configuration files with back slashes:

```
"outputPath": "..\\backend\\public"
instead of:
"outputPath": "../backend/public"
```

For people using Windows and the `connect` feature, does the command `npm run build` work on the frontend project?

**Comment by LoicPoullain** [comment]
**Update**: projects generated on Windows do not build on unix system because of the backslashes.

**Comment by LoicPoullain** [comment]
Fixed in v1.9

**Comment by JuanVqz** [comment]
I just saw PR #703 and the change was for `angular` and `vue`, shouldn't change the react build to the public folder too?

I said this because today I run the command and it adds the proxy key pointed up to `http://localhost:3001`

**Comment by LoicPoullain** [comment]
At that time, React didn't have a configuration file to specify the path of the `build` directory (unlike Angular and Vue). Is there any now?

**Comment by JuanVqz** [comment]
I thought it because the documentation says this and I thought it applies to all of them (Angular/Vue/React), sorry.

```
The connect command also modifies the build output path of your front so that its bundles are saved in the public/ directory.
This way, you can run the frontend and the backend build commands and directly ship the application to production.
```

[Build Outpath](https://foalts.gitbook.io/docs/topic-guides/frontend-integration/angular-react-vue#build-outpath)
