### ISSUE TITLE
OpenApi swagger generate yaml error

### ISSUE THREAD

**Issue by huykn** [FoalTS/foal#565]
Hi guys,
I have a new issue in this great fw Foal.
I have a config :

> @ApiDefineParameter('page_id', {
    description: 'page_id to fetch',
    in: 'path',
    name: 'page_id',
    required: true,
    schema: {
          type: 'string'
    }
  })

and after run swagger i can't see parameter has defined.
and  i have used foal cli to gen file yaml: 

> info:
    contact: {email: huykn0710@gmail.com}
    version: 0.0.1
openapi: 3.0.0
paths:
    '/pages/{page_id}': {get: {responses: {'200': {content: {application/json: {schema: ...
    '/*': {options: {responses: {}}}
servers:
    - {url: 'http://127.0.0.1:3001/api'}
externalDocs:
    description: 'Find out more about Swagger'
    url: 'http://swagger.io'
components:
    schemas: ...
    parameters: {'- page_id': {description: 'page_id to fetch', in: path, name: page_id, required: true}}

You can see tag 'parameters' generate incorrect location.
And i edit file yaml to:

> paths:
  '/pages/{page_id}':
    get:
      parameters:
        - name: "petId"
          description: "page_id to fetch"
          in: "path"
          required: true
          type: "string"

And it's work :))
Btw please help me fix this issue!
Thank so much 🥇

**Comment by LoicPoullain** [comment]
Hi @huykn 

I think the decorator you're looking for is `@ApiParameter`. `@ApiDefineParameter` is used to define globally a schema and reuse-it in several places.

Does it help?

**Comment by huykn** [comment]
Dear @LoicPoullain 
Thanks for your support
It is worked for me. it's amazing.
