### ISSUE TITLE
full open-api example with swagger-ui

### ISSUE THREAD

**Issue by brcarey** [FoalTS/foal#566]
Hi,
I am trying to follow the docs to get open-api / swagger UI setup, but am hitting the following error:

Type 'ApiController' is not assignable to type 'Class<any>

Was wondering if there was an example repo somewhere with all this stuff working? Or is there something I am missing?

Great framework by the way, really liking it.

**Comment by LoicPoullain** [comment]
> Hi,
> I am trying to follow the docs to get open-api / swagger UI setup, but am hitting the following error:
> 
> Type 'ApiController' is not assignable to type 'Class

Hi @brcarey 

We'll need more information here. Can you share your code?

> Was wondering if there was an example repo somewhere with all this stuff working? Or is there something I am missing?

There is currently no example repo (but PRs are welcome!). This might help: https://github.com/FoalTS/foal/blob/master/packages/acceptance-tests/src/openapi.spec.ts

> Great framework by the way, really liking it.

Thanks!

**Comment by LoicPoullain** [comment]
I'm closing old issues. Feel free to reopen it if you still need help on this.
