### ISSUE TITLE
Unexpected testing behaviour

### ISSUE THREAD

**Issue by Edo78** [FoalTS/foal#567]
Hi,
I'm looking at the _simple-todo_ tutorial but running the unit test I found a discrepancy in the output of the `npm run test`. I even downloaded the zip with the source code to be sure but I still have a different output.
```
[1] 8:22:18 PM - Starting compilation in watch mode...
[0] 
[1] 
[1] 
[1]   ApiController
[1]     has a "getTodos" method that
[1]       ✓ should handle requests at GET /.
[1]       ✓ should return an HttpResponseOK.
[1] 
[1] 
[1]   2 passing (154ms)
[1] 
[0] 
[0] 8:22:23 PM - Found 0 errors. Watching for file changes.

[1] 
[1] 
[1]   0 passing (0ms)
[1] 

[1] 
[1]   ApiController
[1]     has a "getTodos" method that
[1]       ✓ should handle requests at GET /.
[1]       ✓ should return an HttpResponseOK.
[1] 
[1] 
[1]   2 passing (35ms)
[1] 
```

Beside this discrepancy I found puzzling that the test keep hanging forever. Usually the test are executed in git hook to prevent a broken commit.

Can you explain me the reason behind this choice?

**Comment by LoicPoullain** [comment]
Hi @Edo78 

>  I found a discrepancy in the output of the `npm run test`.

You're probably running the tests on Mac OS. This is a small bug that appears while running `supervisor` and the compiler watcher together. Haven't found how to solve it yet.

> Beside this discrepancy I found puzzling that the test keep hanging forever. Usually the test are executed in git hook to prevent a broken commit.

The default command `npm run test` compiles and runs the tests in watch mode to make development easier.

If you need to run the tests in a Git hook or in a CI, you can run the following commands:
```
npm run build:test
npm run start:test
```

Does it help?

**Comment by Edo78** [comment]
Hi @LoicPoullain 
> You're probably running the tests on Mac OS.

Actually I'm on Debian

> This is a small bug that appears while running `supervisor` and the compiler watcher together. Haven't found how to solve it yet.

> ```
> npm run build:test
> npm run start:test
> ```
> 
> Does it help?

Yes and no.
If I ran those two commands I actually get the behaviour I was looking for so I can use them in a git hook BUT I got just 2 tests instead of the 4 showed in the [tutorial page](https://foalts.gitbook.io/docs/tutorials/simple-to-do-list/7-unit-testing)
```
  ApiController
    has a "index" method that
      ✓ should handle requests at Get /.
      ✓ should return a HttpResponseOK.


  2 passing (9ms)
```

By the way I was thinking about renaming the actual `test` script to `test:w` and to create a new `test` with the suggested commands. This way I should have each _watching_ script marked by a suffix `:w`
What do you think about?

**Comment by LoicPoullain** [comment]
> If I ran those two commands I actually get the behaviour I was looking for so I can use them in a git hook BUT I got just 2 tests instead of the 4 showed in the tutorial page

The image in the tutorial was out of date. Thank you for pointing this out. I made a PR.

> By the way I was thinking about renaming the actual test script to test:w and to create a new test with the suggested commands. This way I should have each watching script marked by a suffix :w
What do you think about?

You can modify the script names in your `package.json` as you wish. Foal makes no assumption about them.

I would prefer not to modify the `package.json` generated by default though as this would introduce an inconsistency between different versions (and the documentation). Angular projects use `npm run test` to run tests in watch mode whereas other frameworks don't. I'm not sure one of the solutions is better than the other.
