### ISSUE TITLE
[QUESTION] about sending mail

### ISSUE THREAD

**Issue by digitalit** [FoalTS/foal#568]
Hi,
Is it possible to send mail from FoalTS?

**Comment by kingdun3284** [comment]
Literally any node program can send mail

**Comment by digitalit** [comment]
I guess so but i was wondering if there were any best practice FoalTS solutions

**Comment by LoicPoullain** [comment]
Hi @digitalit 

I would recommend to go with [nodemailer](https://nodemailer.com/about/) and to use the [`Config` class](https://foalts.gitbook.io/docs/topic-guides/deployment-and-environments/configuration) to store the configuration.

Documentation on this is definitely missing. I opened an issue for this: #448 .

**Comment by LoicPoullain** [comment]
Feel free to continue this conversation on the other issue if you need more help. I'm closing this one to avoid having duplicates.

**Comment by andrianina4** [comment]
Hello @LoicPoullain  , I install nodemailer with Handlebars , probleme is i dont have file .hbs in build
