### ISSUE TITLE
Typegraphql Integration

### ISSUE THREAD

**Issue by GavinRay97** [FoalTS/foal#569]
Is it possible to integrate Typegraphql with FoalTS?
https://typegraphql.ml/

When using GraphQL in Typescript, it makes a lot of sense to essentially share a single definition between your GraphQL schemas, ORM schemas, and validators, since they are all type-driven.

Here is an example from the Typegraphql page:
```ts
@InputType()
export class RecipeInput {
  @Field()
  @MaxLength(30)
  title: string;

  @Field({ nullable: true })     
  @Length(30, 255)
  description?: string;

  @Field(type => [String])
  @MaxArraySize(25)
  ingredients: string[];
}

@Entity()
@ObjectType()
export class Rate {
  @PrimaryGeneratedColumn()
  readonly id: number;

  @Field(type => Int)
  @Column({ type: "int" })
  value: number;

  @Field(type => User)
  @ManyToOne(type => User)
  user: Promise<User>;

  @Field()
  @CreateDateColumn()
  date: Date;

  @ManyToOne(type => Recipe)     
  recipe: Promise<Recipe>;
}
```

This is a super helpful tool that saves a lot of boilerplate and time.

**Comment by LoicPoullain** [comment]
Hi @GavinRay97 

Yes, it is possible to use TypeGraphQL with Foal. You just need to call its `buildSchema` function with your resolvers:

```typescript
export class ApiController extends GraphQLController {
  schema = buildSchema({
    resolvers: [ MyResolverClass ]
  });
}
```

**Comment by LoicPoullain** [comment]
Feel free to reopen the issue if you need more help.

**Comment by GavinRay97** [comment]
Saw the example you put in the docs -- amazing, thank you!
