### ISSUE TITLE
Recommendations on unit testing with databases

### ISSUE THREAD

**Issue by fer22f** [FoalTS/foal#573]
One of the things that immediately jumped at me was that I wanted to use the database for testing in multiple unit tests. So I added this code in `src/test.ts`:

```js
import 'source-map-support/register';
import { Connection, createConnection } from 'typeorm';

let connection: Connection;
before(async () => {
  connection = await createConnection();
});

after(() => connection.close());

process.env.NODE_ENV = 'test';
```
Is this a technique we should recommend? Or are there better solutions?

**Comment by LoicPoullain** [comment]
It looks good. I don't have another solution in mind (expect adding these lines in each unit test)

**Comment by sgronblo** [comment]
Isn't one problem with this approach that you become responsible for manually restoring the state after each test?

**Comment by LoicPoullain** [comment]
> Isn't one problem with this approach that you become responsible for manually restoring the state after each test?

Oh yes, that's true! I didn't think of that.

> You also lose the possibility of running your tests in parallel?

Mocha only allows to run tests in series AFAIK.

**Comment by sgronblo** [comment]
Oh that's true. I've replaced Mocha with Jest in my project and am trying to speed up the test runs by running tests in parallel.

**Comment by Edo78** [comment]
If you do tests with a db then they are no more unit tests but integration tests.

BTW in loopback you can create "in-menory" db that are the way to go when testing.

You should use TypeORM (or your preferred ORM or ODM) to create an "in-memory" db for testing purpouse

Just my 2 cents

**Comment by fer22f** [comment]
> If you do tests with a db then they are no more unit tests but integration tests.
> 
> BTW in loopback you can create "in-memory" db that are the way to go when testing.
> 
> You should use TypeORM (or your preferred ORM or ODM) to create an "in-memory" db for testing purpouse
> 
> Just my 2 cents

You're not wrong. I'm currently doing testing using SQLite and a file, but it also offers a in-memory option. The problem is more related to the global state that Typeorm requires, because even if you use SQLite with in-memory, you need to setup `createConnection` and `close` after.

**Comment by Edo78** [comment]
@fer22f with mocha you can use its [hooks](https://mochajs.org/#hooks) `before each` and `after each` to create a connection and to close it

**Comment by LoicPoullain** [comment]
I'm closing old issues. Feel free to re-open it if you still need help on this 👍 .
