### ISSUE TITLE
Improve Social Auth Documentation

### ISSUE THREAD

**Issue by LoicPoullain** [FoalTS/foal#581]
The *social authentication* page of the documentation (released with v1.3) could be improved on several points:

- [ ] Give an example on how to save an access or a refresh token in a session to retrieve information later.
- [ ] Give examples of tokens returned by providers.
- [ ] Give examples of user information returned by providers.
- [ ] Better explain the `secure` option.
- [ ] Better explain the `userInfoEndpoint` as a convention name when implementing one’s own provider.
- [ ] Better explain what are redirect URI, why we do have several of them and how they work.
- [x] Better explain the difference between the scopes and the fields in FB provider and how to override them.
- [ ] Mention the errors that can be thrown and what they contain.
- [ ] Mention `UserInfoError `.
- [ ] Add documentation on all variables exported in `packages/social/index.ts`

Related issue: #125 

Possible plan:
```
Installation
## OAuth2 protocol
-> Redirect URIs
### Scopes
## Configuration
-> Register an application
-> Create config files
-> Explain the `secure` option in a `>` comment (CSRF protection must use SSL).
## Basic usage
## Techniques
### Sign In & Sign Up Example
-> explain user info
### Use the provider API
-> how to save an access token in the session
### Refresh tokens
## Social providers
### Common behavior
-> Methods and errors
### Facebook
### Github
### Google
### LinkedIn
### Custom provider
```

**Comment by AminTaghikhani** [comment]
Hi there
For oAuth2 implementation
I use [oauth2-server](https://oauth2-server.readthedocs.io/en/latest/) for my personal project

library supports:
 - refresh/access token
 - client
 - scope
 - grants
