### ISSUE TITLE
Issue/Question regarding test database

### ISSUE THREAD

**Issue by sinclairnick** [FoalTS/foal#590]
I'm trying to test my controllers using a mockDB which aims to connect to the (test) database and run some queries using TypeORM. The file contains this code to intialize the DB:

```typescript
  const connection = await createConnection(Config.get("database"));

```

With `config/test.json` containing
```json
{
  "database": {
    "database": "./testdb.pgsql",
    "dropSchema": true,
    "synchronize": true,
    "type": "postgres"
  }
}

```

I have additionally created the file `app/testdb.pgsql`.

When running my test (which runs the `mockDb.ts` script in the `before()` method), I get the error
```shell
error: database "./testdb.pgsql" does not exist
```

Firstly, how do I fix this issue?
And secondly, what role do files like `db.pgsql` (or `db.sqlite3` if using defaults) and `testdb.pgsql` play in the whole framework if (in my case, at least) they are both empty?

Thanks in advance.

**Comment by LoicPoullain** [comment]
You do not need to use the `Config` class when calling `createConnection()`. It will directly look at your `ormconfig.json` which uses the `Config` class.

Your database configuration is also incorrect. Only SQLite uses files as database (`db.sqlite3`) which is not the case with Postgres. This point is not related to Foal though. You may need to learn first how to connect to a postgres database with an ORM (in this case TypeORM) before going any further with Foal. Maybe this link will help: https://typeorm.io/#/using-ormconfig.

**Comment by sinclairnick** [comment]
I've used postgres a fair amount before, I wasn't aware that sqlite operated using files. I've also modified the redundant `Config` code in `createConnection`. I'm not sure if the file usage for sqlite is common knowledge or not, but perhaps information about changing from the default sqlite configuration should be expanded on in the docs. I might make a pull request on this in the near future.

**Comment by LoicPoullain** [comment]
Thanks for pointing this out.

I'll add something in the next few days for MySQL and Postgres. I'm closing the issue in favor of #522 to avoid duplication.
