### ISSUE TITLE
CSRF Protection : setCsrfCookie() and getCsrfToken() not working

### ISSUE THREAD

**Issue by sinclairnick** [FoalTS/foal#603]
Copying the example used in [the csrf documentation](https://foalts.gitbook.io/docs/topic-guides/security/csrf-protection#spa-api), the code,

```ts
    const response = new HttpResponseOK({ user });
    setSessionCookie(response, session.getToken());         //<-- does not cause errors
    setCsrfCookie(response, await getCsrfToken(session));   //<-- causes errors
```
causes the following errors,
```
Argument of type 'HttpResponseOK' is not assignable to parameter of type 'HttpResponse'.
  Types have separate declarations of a private property 'cookies'.ts(2345)
```
and 

```
Argument of type 'import("/<root_dir>/app/node_modules/@foal/core/lib/sessions/session").Session' is not assignable to parameter of type 'import("<root_dir>/app/node_modules/@foal/csrf/node_modules/@foal/core/lib/sessions/session").Session'.
  Types have separate declarations of a private property 'sessionContent'.ts(2345)
```

Interestingly, `setSessionCookie()`, which has the same signature, does not produce the error, even when changing execution order.

**Comment by LoicPoullain** [comment]
Hi @sinclairnick 

I couldn't reproduce the error on my host. Which versions of `@foal/core` and `@foal/csrf` do you have in your `package-lock.json`?

**Comment by LoicPoullain** [comment]
Also, what is your TypeScript version?

**Comment by sinclairnick** [comment]
Hey Loic, sorry for the delay.

I've just updated my TS and @foal/... packages to 3.7.4 and 1.3.1, respectively. This seems to have fixed the `HTTPResponseOK`-related error. However, the second error remains and another error has been introduced.

```ts
error TS2322: Type 'typeof TypeORMStore' is not assignable to type 'Class<SessionStore>'.
```
