### ISSUE TITLE
foal generate --register warning

### ISSUE THREAD

**Issue by anonimusprogramus** [FoalTS/foal#606]
I did this:
`foal g controller upload --register`

It showed a warning:
`(node:32942) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'index' of undefined`

But the result is **OK**

![Screenshot_20191226_163628](https://user-images.githubusercontent.com/7464749/71470052-99df9f80-27fd-11ea-8cfc-5992dc0828a1.png)

**Comment by LoicPoullain** [comment]
Thank you for reporting this bug @anonimusprogramus and sorry for the delay.

A fix is on its way: #619

**Comment by LoicPoullain** [comment]
PR merged. The fix will be released with v1.6.0
