### ISSUE TITLE
Catch errors from nasted services and return HttpResponse

### ISSUE THREAD

**Issue by qubiack** [FoalTS/foal#618]
I look for a way to handle `HttpResponse` errors from services. In this framework exist something like a catcher?

I can use `return new HttpResponseBadRequest()` in any place, but in this construction, my service should return object or response as a type so I have a service like `: Promise<Task | HttpResponse>`. It's really ugly and messy when I use multiple services in together.

If I throw an error in nested services it always returns `Error 500`.

It's anyway to do it in a simple way as annotation or catch `throw new Error()` from any application place into one handler?

**Comment by kingdun3284** [comment]
You should only return a httpresponse in a controller. Throw an error from service, catch the error in controller and return a http response.

**Comment by LoicPoullain** [comment]
As @kingdun3284 mentioned, `HttpResponse` should only be instantiated and returned in a controller.

If you wish, you can also globally catch errors thrown in hooks/controllers/services with the "handleError" method in "AppController" and transform these errors into "HttpResponse" here: https://foalts.gitbook.io/docs/topic-guides/cookbook/error-handling

**Comment by LoicPoullain** [comment]
I'm closing old issues. Feel free to re-open it if you still need help on this 👍 .

**Comment by anonimusprogramus** [comment]
Hi all, sorry to re-open this, still need help on HttpResponse placement.

Similar to @qubiack's,  I have this AuthController, supposed to return HttpResponse, but I delegated all details to AuthService. So controller just implisitly returns what service returns.

Is this a not-recommended practise in FoalTS?
Suggestion is welcome. Thank you!

Here's my code,

`auth.controller.ts`

```typescript
import { Context, dependency, Post } from '@foal/core'

import { AuthService } from '../services'
import { AuthLoginValidator } from '../validators'
import { BodyCheck, JwtCheck, RefreshJwt } from '../hooks'

@JwtCheck({ isOptional: true })
@RefreshJwt()
export class AuthController {
  @dependency
  private authService: AuthService

  @Post('/login')
  @BodyCheck({ val: AuthLoginValidator })
  async login(ctx: Context) {
    return await this.authService.login(ctx)
  }
}
```

`auth.service.ts`

```typescript
import {
  Context,
  dependency,
  HttpResponseBadRequest,
  HttpResponseOK,
  HttpResponseUnauthorized,
  verifyPassword
} from '@foal/core'

import { UserService } from './user.service'
import { generateJwt, msg, getUserWithPassword } from '../utils'
import { err, state } from '../enum'

export class AuthService {
  @dependency
  private userService: UserService

  async login(ctx: Context) {
    const body = ctx.state[state.BODY_CHECKED]
    if (!body) return new HttpResponseBadRequest(msg(err.AUTH_ABNORMAL))

    const { email, password } = body

    const user = await getUserWithPassword({ email })
    if (!user) return new HttpResponseUnauthorized(msg(err.LOGIN_FAILED))

    const verified = await verifyPassword(password, user.password)
    if (!verified) return new HttpResponseUnauthorized(msg(err.LOGIN_FAILED))

    const token = generateJwt(user)
    return new HttpResponseOK(token)
  }

  async signup(ctx: Context) {
    return await this.userService.create(ctx)
  }

  async logout(ctx: Context) {}
}
```
