### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [FoalTS/foal#63]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature.

It's  55 times faster than EJS, and it also use less CPU and RAM ressources, so it may be a good idea to use it instead of EJS 😀

**Comment by LoicPoullain** [comment]
Hi @Drulac,

It looks like an interesting project you have there. In our case, `FoalTS` has already a package for rendering templates (`@foal/ejs`) and we're not experimenting performance issues for now. Moreover, I find the way ejs handles `if-condition` more intuitive that we would do with template literals.

I'm going to close this issue, but feel free to create your own `foal-generator-literal` package if you want ! :) It will be tagged as a community package on the `README.md`.
