### ISSUE TITLE
How to use multiple ORM connections?

### ISSUE THREAD

**Issue by diegodurrod** [FoalTS/foal#631]
Is there any way to use multiple ORM connections at the same time?

Sometimes it needs to use different connections to other databases for many reasons: synchronize, make differents actions... 

I was reading the official documentation but I didn't find anything about

**Comment by LoicPoullain** [comment]
Hi @diegodurrod 

You can create multiple connections with TypeORM:
- https://typeorm.io/#/multiple-connections
- https://typeorm.io/#/using-ormconfig

To use multiple connections with Foal, you will probably need to update `src/index.ts` and your `ormconfig.json` for this.

> Note: Foal's stores will use the `default` connection

**Comment by LoicPoullain** [comment]
Hi @diegodurrod 

I'm closing old issues. Feel free to re-open it if you still need help.
