### ISSUE TITLE
[Proposal] Custom non-English error messages

### ISSUE THREAD

**Issue by anonimusprogramus** [FoalTS/foal#639]
I like built-in Hooks like `ValidateBody`.

But having trouble with the error message, since the app users would be non-English.

I did peek on the [source](https://github.com/FoalTS/foal/blob/master/packages/typestack/src/validate-body.hook.ts) and saw that ValidateBody already threw `HttpResponseBadRequest`.

Temporarily, I came up with solution by copying and modifying ValidateBody as custom Hook. Yes, reinventing the wheel (sad icon).

So I'd love to propose:

1. ValidateBody @param can include custom message object (_as addition to those options for class-validator & class-tranformer_)

ie. message like
```javascript
{ error: { message: 'Password tidak boleh kosong' }}
```  

2. A way to disable internal warning/error that would be output to user.

ie. error in English such us
```javascript
return new HttpResponseBadRequest({
  message: 'The request body should be a valid JSON object or array.'
});
```

Thank you.

**Comment by LoicPoullain** [comment]
Hi @anonimusprogramus 

Thank you for your proposal. I think the best way to achieve this would be to add a "translate" post-hook on your method. Something like this:

```typescript
class Controller {

  @Hook(() => response => {
    if (isHttpResponseBadRequest(response)) {
      // Modify response.body to customize the response message
    }
  })
  @ValidateBody({ ... })
  something() { ... }

}
```

This way, you can customize the response returned by ValidateBody as you wish.

**Comment by anonimusprogramus** [comment]
That easy? Ouch.

Gonna explore that. Looks like I have to rewrite... again :smile: 

Thank you!
