### ISSUE TITLE
Schema validator in shell script using class-validator

### ISSUE THREAD

**Issue by anonimusprogramus** [FoalTS/foal#640]
Hi Loic.

In shell script, is that possible to use class-validator as alternative to AJV?
This way, I keep DRY, using already made validator in app itself.

Thank you.

**Comment by LoicPoullain** [comment]
Currently it is not possible, you have to manually validate it yourself with class-validator.

Maybe something like:
```typescript
import { plainToClass } from 'class-transformer';
import { validateOrReject } from 'class-validator';

// ...

export async function main(args) {
  await validateOrReject(plainToClass(User, args));
}
```

**Comment by anonimusprogramus** [comment]
Didn't imagine it would be that simple. Thank you!
