### ISSUE TITLE
Closing connection in shell script

### ISSUE THREAD

**Issue by anonimusprogramus** [FoalTS/foal#645]
In this [create-user script](https://foalts.gitbook.io/docs/tutorials/multi-user-to-do-list/3-the-shell-scripts#the-create-user-script), we have conditional checking:

```typescript
await createConnection();

/* ... redacted */

if (await isCommon(args.password)) {
  console.log('This password is too common. Please choose another one.');
  return;
}
```

If the condition is met (too common password), then exit the script.

**Question:**

Did that `return;` statement automatically close the connection, so we don't need `await getConnection().close();` ?

Thank you

**Comment by LoicPoullain** [comment]
Actually it does not, which is bad.

We should have something like this instead (with a try/catch/finally):
```typescript
// imports (modified)

export async function main(args: { email: string, password: string }) {
  const connection = await createConnection();
  try {
    const user = new User();
    user.email = args.email;

    if (await isCommon(args.password)) {
      console.log('This password is too common. Please choose another one.');
      return;
    }
    await user.setPassword(args.password);

    console.log(
      await getManager().save(user)
    );
  } catch (error) {
    console.log(error.message);
  } finally {
    await connection.close();
  }
}
```

The same applies for the `create-todo` script (for the first and second tutorials) and the script described here: https://foalts.gitbook.io/docs/topic-guides/authentication-and-access-control/groups-and-permissions#creating-groups-with-a-shell-script-cli

If you feel like to open a PR to surround these codes with a try/catch/finally, feel free to do it. I'll be happy to review. No need to add new comments or add explanation, just the code can be updated. The files to update would be:
- docs/tutorials/multi-user-todo-list/3-the-shell-scripts.md (two scripts)
- docs/tutorials/simple-todo-list/4-the-shell-script-create-todo.md
- docs/authentication-and-access-control/groups-and-permissions.md (creating groups with a shell scripts)
- the files in samples/tutorials/1-simple-todo-list and 2-multi-user-todo-list-mpa

**Comment by anonimusprogramus** [comment]
I'm gonna take this good opportunity, one by one. Thank you.
