### ISSUE TITLE
handleError: true not working

### ISSUE THREAD

**Issue by sinclairnick** [FoalTS/foal#649]
I've tried to implement a custom error handler, as per [the docs](https://foalts.gitbook.io/docs/topic-guides/cookbook/error-handling) but providing anything other than an express app as the second argument to the `createApp` function raises a TS error.

Thus, custom global error handling cant be implemented.

e.g.
```ts
const app = createApp(AppController, {
    methods: {
      handleError: true
    }
  });
```
raises
```tserror
Argument of type '{ methods: { handleError: boolean; }; }' is not assignable to parameter of type 'ExpressApplication | ExpressOptions | undefined'.
```

**Comment by anonimusprogramus** [comment]
Hi @sinclairnick 

What foal cli version do you use?

I just retried what you did, and it works, no problem.

Here's the screnshot.

![Screenshot_20200221_153426-1](https://user-images.githubusercontent.com/7464749/75017458-a01d8f80-54bf-11ea-8198-17ff18ae42ee.png)

**Comment by sinclairnick** [comment]
@anonimusprogramus I've updated foal, which fixed the issue, thanks. However, I can no longer use the express instance I created as a second option.

@LoicPoullain is there a way to override default error handling while also using an express app instance (e.g. for rate limiting)?

**Comment by LoicPoullain** [comment]
@sinclairnick You can still use the express instance but you have to pass it this way:
```typescript
const app = createApp(AppController, {
  expressInstance: expressApp,
  methods: {
      handleError: true
    }
});
```

If you want to override default error handling for express middlewares, you can create an error middleware like in a regular Express application.

```typescript
const expressInstance = express();
expressInstance.use(myMiddleware);
expressInstance.use((err, req, res, next) => {
  // handle errors of myMiddleware (see Express docs)
});
const app = createApp(AppController, { expressInstance });
```

**Comment by sinclairnick** [comment]
Thanks @LoicPoullain and @anonimusprogramus , I figured that may be the case - apologies. I ended up using the `preMiddleware` option instead and managed to use `handleError` that way.
