### ISSUE TITLE
Groups and permissions with postgres

### ISSUE THREAD

**Issue by sebibigbob8** [FoalTS/foal#650]
Hi everyone,

I'm currently implementing the Groups & Permissions by following the official documentation : 
[official website](https://foalts.gitbook.io/docs/topic-guides/authentication-and-access-control/groups-and-permissions#creating-groups-with-a-shell-script-cli)

The issue when I'm running the script to create a group `UnhandledPromiseRejectionWarning: DataTypeNotSupportedError: Data type "Array" in "Group.permissions" is not supported by "postgres" database.` TypeOrm's forums talk about how to resolve it in entities.
```typescript
@Column("text", {array: true})
  permissions: Permission[];
```
But this solution does not resolve my problem and I didn't find another one in the documentation.

Anyone here has an example of this implementation postgres friendly?

**Comment by anonimusprogramus** [comment]
Hi Sebastien.

I'm using MySQL, no problem with tutorial.

So just installed PostgreSQL and modified ormconfig.js. And it just works!

Sometimes you got it right but the compiled .js is still there, so we might have to clear them and rebuild scripts:

```
foal rmdir build/ && npm run build:scripts
foal run create-perm ...
foal run create-group ...
```

**Comment by LoicPoullain** [comment]
@sebibigbob8 your TypeORM property is incorrect (https://typeorm.io/#/many-to-one-one-to-many-relations and https://typeorm.io/#/many-to-many-relations).

```typescript
@ManyToMany(type => Permission)
@JoinTable()
permissions: Permission[];
```

But normally you wouldn't have to define the permission property yourself. The `Group` and `UserWithPermissions` already do it for you. What are you trying to achieve?

**Comment by sebibigbob8** [comment]
Hi,

Thanks @anonimusprogramus for the answer.

@LoicPoullain you are right, it's me, I've just missunderstood the tutorial and re-create Permission and Group entities!

Thanks a lot
