### ISSUE TITLE
Why foal does not have HttpResponseTooManyRequests method?

### ISSUE THREAD

**Issue by nguyendlp** [FoalTS/foal#664]
Hi author,

When using foal, in some cases I want to return HTTP code 429 - Too many requests but foal does not implement this method. Why?

Thanks!

**Comment by LoicPoullain** [comment]
No particular reason.

Do you want to submit a PR and add `HttpResponseTooManyRequests` and `isHttpResponseTooManyRequests` in `packages/core/src/core/http/http-responses.ts`?

**Comment by LoicPoullain** [comment]
Fixed in v1.9.0
