### ISSUE TITLE
using dependency injection with TypeGraphQl

### ISSUE THREAD

**Issue by karimsqualli** [FoalTS/foal#665]
Hello  guys, i want to know how is it possible to add classes that are not in the services folder to the dependency injection system, for my example i'm using graphql + TypeGraphQL, but i can't inject any dependency inside my Resolver class, so i can't accesss any of my services class

```typescript
@Resolver(Recipe)
class RecipeResolver {
  
// can this class be added someway to the dependency injection 
// im coming from nestjs normally i would have added @Injectable decorator 
// but i think foalts automaticly load dependency from services folder whithout any decorator needed

 // @dependency
 // private recipeService: RecipeService;

  constructor(private recipeService: RecipeService) {}

  @Query(returns => [Recipe])
  recipes() {
    return this.recipeService.findAll();
  }

  @Mutation()
  @Authorized(Roles.Admin) // auth guard
  removeRecipe(@Arg("id") id: string): boolean {
    return this.recipeService.removeById(id);
  }

  @FieldResolver()
  averageRating(@Root() recipe: Recipe) {
    return recipe.ratings.reduce((a, b) => a + b, 0) / recipe.ratings.length;
  }
}
```

**Comment by LoicPoullain** [comment]
hello @karimsqualli. Sorry for the late reply. FoalTS dependency injection is not designed to be integrated in TypeGraphQL. The solution suggested [here](https://github.com/FoalTS/foal/pull/647/files) might work but the framework does not provide official support for this.
