### ISSUE TITLE
@ApiOperation - responses not taken into account

### ISSUE THREAD

**Issue by FredericLatour** [FoalTS/foal#666]
When using @ApiOperation decorator, responses do not seem to be taken into account:

```typescript
 @ApiOperation({
    operationId: 'FindActivity',
    summary: 'Find Activity(s)!',
    responses: {
      '200': { description: 'Returns a Activity or a list of Activitys.' },
      '400': { description: 'Invalid Query parameters.' }
    }
  })
```

Instead I get a default single 400 Bad Request in Swagger UI as shown in the following screenshot :  

![image](https://user-images.githubusercontent.com/1407847/78414462-69897780-761c-11ea-8bba-d352a3b2c905.png)

**Comment by LoicPoullain** [comment]
@FredericLatour do you use a `@Validate` hook somewhere with the configuration ``setting.openapi.useHooks` enabled?

**Comment by LoicPoullain** [comment]
Also, does using `@ApiResponse(400, { description: 'Invalid Query parameters.' })` override the behavior?

**Comment by FredericLatour** [comment]
@LoicPoullain 
Good catch. Yes I'm using:
`    "openapi": { "useHooks": true}`

It works when I'm not using it.

When `useHooks `is set to `true`:
Using `@ApiResponse(400, { description: 'Invalid Query parameters.' })` does not really override the behavior but rather overrides '400' description.  
If I'm using `@ApiResponse(201, { description: 'Invalid Query parameters.' })` , I will get both the '400' Bad request and '201' responses displayed.

**Comment by LoicPoullain** [comment]
Ok thank you for the information.

This is the intended behavior. Responses defined in `@ApiOperation` are all overridden when using `@ApiResponse`. `@Validate`, when it is used with `useHooks`, calls `@ApiResponse` under the hood, this is way you're getting this behavior.

Two possible solutions:
1. Use the `@ApiResponse` decorators to define the responses:
```typescript
@ValidateXXX(...)
@ApiOperation({
    operationId: 'FindActivity',
    summary: 'Find Activity(s)!',
})
@ApiResponse('200', { description: 'Returns a Activity or a list of Activitys.' })
@ApiResponse('400', { description: 'Invalid Query parameters.' })
```

2. Disable the OpenAPI generation of this `@Validate`. This will however also remove the request body definition from the OpenAPI spec 
```typescript
@ValidateXXX(..., { openapi: false })
@ApiOperation({
  operationId: 'FindActivity',
  summary: 'Find Activity(s)!',
  responses: {
    '200': { description: 'Returns a Activity or a list of Activitys.' },
    '400': { description: 'Invalid Query parameters.' }
  }
})
```

**Comment by LoicPoullain** [comment]
I am closing the issue because there has been no response to the last comment in the last three weeks. Please feel free to reopen it if you still need help @FredericLatour .
