### ISSUE TITLE
Inconsistencies in formatting of generated files

### ISSUE THREAD

**Issue by matt-harvey** [FoalTS/foal#693]
As can be seen in the docs [here](https://foalts.gitbook.io/docs/tutorials/simple-to-do-list/3-the-todo-model) the generated migration files do not conform to the same formatting conventions as, for example, the generated model files.The migration files have 4-space indents and do not have a space separating the braces used for imports from their contents; whereas the generated model files and 2-space indents and have a space between the braces used for imports and their contents.

**Comment by matt-harvey** [comment]
OK, looks like this is TypeORM's doing, not Foal's.

It seems TypeORM does not have a way to configure the formatting of the files it generates. See [this issue](https://github.com/typeorm/typeorm/issues/2521). However, as suggested there, the generated files could be passed through [prettier](https://prettier.io/) to reformat them.

I'm also wondering whether in the long term the plan is for the `foal` executable to provide the migration generation command (i.e. `foal generate migration`)? In which case it might make more sense to do the formatting programatically within the `foal` generator (even if TypeORM is still delegated the substantive code generation work).

I'd be happy to help fix this if provided some guidance on the preferred solution.

**Comment by LoicPoullain** [comment]
Thank you for your suggestion and investigation @matt-harvey 

Yes, migration files are generated by TypeORM with different formatting conventions. This is why the `migrations/` directory is excluded in the linting configuration. I’m not sure that reformatting the files would bring enough value compared to the complexity involved by adding new code (that needs to be maintained and tested). Also we try to [avoid adding new dependencies](https://github.com/FoalTS/foal/blob/master/.github/CONTRIBUTING.MD#dependency-policy) in the framework. This is why I’m closing the issue.

There will be probably a `foal makemigrations` command in the future but this will require some parts of the CLI to be refactored (#577) which is not a priority at the moment.

**Comment by matt-harvey** [comment]
OK, fair decision&mdash;makes sense. Thanks for explanation :+1:
