### ISSUE TITLE
Error after upgrading from 1.6.0 to 1.8.1

### ISSUE THREAD

**Issue by Majunko** [FoalTS/foal#700]
Hello, i'm getting the next error after to put `npm update` into my foal project. This error appear in the sign() method.

```typescript
Argument of type '(err: Error | null, value: string) => void' is not assignable to parameter of type 'SignCallback'.
  Types of parameters 'value' and 'encoded' are incompatible.
    Type 'string | undefined' is not assignable to type 'string'.
      Type 'undefined' is not assignable to type 'string'.
```

This is my actual code to login:
```typescript
import {
  Post, ValidateBody, verifyPassword,
  HttpResponseUnauthorized, HttpResponseOK, Config, Context
} from '@foal/core';
import { User } from '../entities';

import { sign } from 'jsonwebtoken';
import { getRepository } from 'typeorm';

const credentialsSchema = {
  additionalProperties: false,
  properties: {
    email: { type: 'string', format: 'email' },
    password: { type: 'string' }
  },
  required: ['email', 'password'],
  type: 'object',
};

export class AuthController {

  @Post('/login')
  @ValidateBody(credentialsSchema)
  async login(ctx: Context) {
    const user = await getRepository(User).findOne({ email: ctx.request.body.email });

    if (!user) {
      return new HttpResponseUnauthorized();
    }

    if (!await verifyPassword(ctx.request.body.password, user.password)) {
      return new HttpResponseUnauthorized();
    }

    return this.generateLoginResponse(user);
  }

  private async generateLoginResponse(user: User): Promise<HttpResponseOK> {
    const payload = { };
    const secret = Config.get<string>('settings.jwt.secretOrPublicKey');

    const token = await new Promise<string>((resolve, reject) => {
      sign(payload, secret, { subject: user.id.toString(), expiresIn: '1h' }, (err, value: string) => {
        if (err) {
          return reject(err);
        }
        resolve(value);
      });

    });

    return new HttpResponseOK({
      token: token
    });
  }

}
```
I tried to create a new project, but the error still appears.
Is there something that i missed?
Thanks.

**Comment by LoicPoullain** [comment]
It looks like it is related to `@types/jsonwebtoken`. Do you have it installed ? Does your error appear near the line `const token = await new Promise<string>((resolve, reject) => {`? `npm update` would have updated both the framework and this package.

Would `(err, value: string|undefined)` and `resolve(value as string)` solve the problem?

**Comment by Majunko** [comment]
> It looks like it is related to `@types/jsonwebtoken`. Do you have it installed ? Does your error appear near the line `const token = await new Promise<string>((resolve, reject) => {`?

I had installed `@types/jsonwebtoken`. The error was in this part: `(err, value: string) => {`

> `npm update` would have probably updated both the framework and this package.

The `npm update` command, update the next packages:
`@foal/core` from 1.6.0 to 1.8.1
`@foal/jwt` from 1.6.0 to 1.8.1
`@foal/typeorm` from 1.6.0 to 1.8.1
`@types/jsonwebtoken` from 8.3.8 to 8.3.9 
and other third packages.

> Would `(err, value: string|undefined)` and `resolve(value as string)` solve the problem?

I resolved it with `(err, value: string | undefined)`

Thank you so much for the soon reply and for your help.
Keep going with this awesome framework, really easy to use and with a complete documentation.
