### ISSUE TITLE
Combine custom and default service manager.

### ISSUE THREAD

**Issue by kingdun3284** [FoalTS/foal#713]
It is cumbersome that I must create every single instance of services just because some of it (such as custom repository) can't be create automatically by the default service manager.

**Comment by LoicPoullain** [comment]
Hmm, this shouldn't happen. Can you share your code?

**Comment by kingdun3284** [comment]
> Hmm, this shouldn't happen. Can you share your code?

Sorry, my mistake. I try to inject something into the custom repository and find that the service in it can't be called by setting 
```
serviceManager.set(SomeClassRepository,connection.getCustomRepository(SomeClassRepository));
```

example custom repository:
```
@EntityRepository(SomeClass)
export class SomeClassRepository extends Repository<SomeClass> {
    @dependency
    someService: SomeService;
}
```
After that, I try to print app.foal.services.map and found that SomeService is created actually, but it can't be injected to SomeClassRepository automatically. I think this isn't the problem of the framework. Anyway, I gave up data mapper pattern and try to use active record pattern + service.
