### ISSUE TITLE
Eslint errors result from following the tutorial

### ISSUE THREAD

**Issue by matt-harvey** [FoalTS/foal#720]
After following the tutorial [here](https://foalts.gitbook.io/docs/tutorials/multi-user-to-do-list/3-the-shell-scripts), the resulting code causes `npm run lint` to produce the following error in both `src/scripts/create-todo.ts` and `src/scripts/create-user.ts`:

```
error  Expected a semicolon  @typescript-eslint/member-delimiter-style
```

The error goes away if the comma in the `main` function's signature is replaced with a semicolon, i.e. if

```js
export async function main(args: { email: string, password: string }) {
```

is changed to

```js
export async function main(args: { email: string; password: string }) {
```

(And similarly for the `create-todo.ts` script.)

I've applied this fix in PR #721.

---

An alternative fix would be to add the following line to the `.eslintrc.js` that is generated by `foal create-app`:

```js
'@typescript-eslint/member-delimiter-style': 'comma',
```

Happy to change my PR to this second solution if that's your preference. (Personally my preference would be to stick with the existing, default setting for this linter setting; but it's your call.)

**Comment by LoicPoullain** [comment]
Thks for reporting the issue. The first solution looks good!
