### ISSUE TITLE
generate database in production

### ISSUE THREAD

**Issue by jcpc91** [FoalTS/foal#724]
i'm trying to set in production the application i run this commands
npm install
npm run build
npm run build:migrations
npm run migration:run
NODE_ENV=production npm run start

but the database is not generated and i'm getting error when i run
 "npm run migration:run
QueryFailedError: SQLITE_ERROR: no such table: user
i know when i am developing the database is auto-generate bu in production mode is not generate

thanks for help
package.json
"dependencies": {
    "@foal/core": "~0.7.0",
    "@foal/ejs": "~0.7.0",
    "@foal/jwt": "^0.8.5",
    "@foal/typeorm": "~0.7.0",
    "@types/amqplib": "^0.5.7",
    "@types/socket.io": "^1.4.33",
    "@types/xmlbuilder": "0.0.32",
    "adm-zip": "^0.4.14",
    "amqplib": "^0.5.3",
    "connect-sqlite3": "^0.9.11",
    "cors": "^2.8.5",
    "got": "^9.6.0",
    "jsonwebtoken": "^8.5.0",
    "multer": "^1.4.1",
    "soap": "^0.27.1",
    "socket.io": "^2.2.0",
    "source-map-support": "^0.5.1",
    "sqlite3": "^4.0.0",
    "tmp": "^0.1.0",
    "tmp-promise": "^1.0.5",
    "typeorm": "^0.2.6",
    "uuid": "^3.3.2"
  },

**Comment by kingdun3284** [comment]
You have to generate the migration first.

**Comment by LoicPoullain** [comment]
@jcpc91 it looks like you made a mixture of the `synchronize` option and the use of migrations. Or perhaps, you removed some migration files.

One of your migration files assumes that you already created the user table.

If you haven't added data to your *production* database yet (which seems to be the case), I would personally delete the production db, remove the migrations files and regenerate them from the production db (which will be re-created when running the migrations).

**Comment by jcpc91** [comment]
thanks for the help 
the database was not auto generate in production i run the command to run the aplication

**pm2 start "NODE_ENV=production npm run start" --name app --log app.log**

but not database generate but i found the "solution" with this command from typeorm 

**typeorm schema:sync**

this generate the database from the entity model
thanks
