### ISSUE TITLE
Moving default config folder to config/environments?

### ISSUE THREAD

**Issue by jondot** [FoalTS/foal#735]
Hi, I'd like to suggest moving or adding the default config lookup folder from just 

```
   config/
      development.json
      ...
```

to 

```
   config/
      environments/
           development.json
```

Which is similar to Rails, and also encourages a central place for other kinds of configuration (orm, emails, and other libraries).

I'm currently hacking it out by using `NODE_ENV=environments/development`

**Comment by TheFuriousSnail** [comment]
Coming from Symfony I really appreciate the standardized folder structure. I fully support the idea that we need a better way to structure FoalTS projects.

**Comment by LoicPoullain** [comment]
Thank you for your suggestion.

What would be the purpose of adding an `environments/` directory? Is it to organize the `config/` directory?

**Comment by jondot** [comment]
```
❯ tree config
config
├── boot.ts
├── database.js
├── db
│   └── database.sqlite
├── environments
│   ├── default.json
│   ├── development.json
│   ├── production.json
│   └── test.json
└── initializers
    └── jwt.ts

3 directories, 8 files
```


After I tweaked and bended Foal, this is how my backend project config looks like. it is _very_ similar to Rails and reflects more opinionated organization




Reference: here is a Rails breakdown of a large SaaS app:

```
config
├── application.rb
├── boot.rb
├── cable.yml
├── database.yml
├── environment.rb
├── environments
│   ├── development.rb
│   ├── production.rb
│   ├── staging.rb
│   └── test.rb
├── initializers
│   ├── admin_access.rb
│   ├── application_controller_renderer.rb
│   ├── assets.rb
│   ├── backtrace_silencers.rb
│   ├── constants.rb
│   ├── content_security_policy.rb
│   ├── cookies_serializer.rb
│   ├── devise.rb
│   ├── filter_parameter_logging.rb
│   ├── flipper.rb
│   ├── inflections.rb
│   ├── loggers
│   │   └── stripe_logger.rb
│   ├── mime_types.rb
│   ├── pundit.rb
│   ├── sidekiq.rb
│   ├── simple_form_bootstrap.rb
│   ├── stripe.rb
│   ├── timeout.rb
│   └── wrap_parameters.rb
├── locales
│   ├── devise.en.yml
│   ├── en.yml
│   └── simple_form.en.yml
├── puma.rb
├── routes.rb
├── sidekiq.yml.erb
├── spring.rb
├── storage.yml
├── webpack
│   ├── development.js
│   ├── environment.js
│   ├── loaders
│   │   └── coffee.js
│   ├── production.js
│   └── test.js
└── webpacker.yml
```

**Comment by LoicPoullain** [comment]
Hi @jondot . Thank you for sharing this config example. Version 2 of FoalTS will support JS config files allowing users to customize the configuration directory at will.

**Comment by LoicPoullain** [comment]
See #805 and #806.
