### ISSUE TITLE
postMiddlewares not run [bug or by design?]

### ISSUE THREAD

**Issue by tomer-refundit** [FoalTS/foal#744]
Hi,
I have controller that return HttpResponseOK
postMiddlewares not called

preMiddlewares work as expected

looking at the code i see that createMiddleware dont call next when exception is not thrown.
is this by design?

**Comment by LoicPoullain** [comment]
Yes this is by design. What are you trying to achieve? May the post hook functions be useful in your case: https://foalts.gitbook.io/docs/topic-guides/architecture/hooks#executing-logic-after-the-controller-method ?

**Comment by tomer-refundit** [comment]
Hi, yes i did what you suggested. I suggest it should be clear what the behavior of postMiddlewares .
so postMiddlewares  useful for for route not found right? i cant thing of something else it will be good for
