### ISSUE TITLE
Implement `npm run format` with prettier

### ISSUE THREAD

**Issue by opensas** [FoalTS/foal#749]
I know it's not rocket science to include prettier with a .prettierrc file, but provinding it out of the box, like nestjs does, would encourage people to adopt such technique.

Moreover, by provinding a foalts default prettierrc file, it would also encourage a common coding style for every foalts app, while allowing everyone to customize it to its taste.

**Comment by LoicPoullain** [comment]
Thank you for your suggestion.

I think this is opinionated. Some people may want to use it, other won't. Let's let users add it themselves if they wish.

Including prettier in the generated application would also add an extra dependency to the framework which we do not want (see https://github.com/FoalTS/foal/blob/master/.github/CONTRIBUTING.MD#dependency-policy). It would also add an extra file to understand to users which would go against the philosophy of the framework which aims to be simple and progressive. This is why I'm closing the issue 👍

**Comment by opensas** [comment]
Ok, I like the dependency policy, good point.
