### ISSUE TITLE
Cant verify token signed by sign function

### ISSUE THREAD

**Issue by viniciusgati** [FoalTS/foal#751]
Hi, thanks for your time,

i have a function that generate a token and returns like:

```typescript
    return sign(
        { sub: sub },
        Config.get<string>('settings.jwt.secretRefreshKey'),
        { expiresIn: '6d' }
    );
```
then the same token when i verify with:

```typescript
    const secret = Config.get<string>('settings.jwt.secretRefreshKey');
    return verifySignedToken(token, secret);
```

the verifySignedToken returns false, what im done wrong?

**Comment by LoicPoullain** [comment]
The proper function to use is the `verify` function from `jsonwebtoken`.

```typescript
import { verify } from 'jsonwebtoken';

    const secret = Config.get<string>('settings.jwt.secretRefreshKey');
    return verifySignedToken(token, secret);
```

**Comment by viniciusgati** [comment]
Ok thanks, i followed this page https://github.com/FoalTS/foal/issues/464 thats why im using that way.

Thanks again.
