### ISSUE TITLE
Is it possible to use NextJS with FoalTS?

### ISSUE THREAD

**Issue by CodingCreate101** [FoalTS/foal#756]
I've no idea where to ask questions about FoalTS.

I was wondering if it's possible to use FoalTS with [NextJS](https://nextjs.org/). I am asking because of the `connect` step that other frontend frameworks have. I didn't find any information about this elsewhere. 

Also a discord server would help a lot to just be able to ask questions or share solutions to common problems. I am not aware of any such place for FoalTS yet.

**Comment by kingdun3284** [comment]
You can always use any frontend framework by enableing CORS request. The connect function is just creating a proxy, so that the application dev server will be considered as same domain.

**Comment by CodingCreate101** [comment]
Okay, thanks! :)

Is there a place where FoalTS discussions happen? Like discord, gitter, etc?
