### ISSUE TITLE
All in one package

### ISSUE THREAD

**Issue by jonathanroze** [FoalTS/foal#765]
Hi, 

I'm using FoalTS for building my API and it works very great. But I need to produce a single output file with all requirements (node_modules, etc...) because I can't run a 'npm install' on my production server (Not enough of disk space) so, is there a way to do this ? 

I try to use Webpack but I've an issue with pg-native 

```
ERROR in ./node_modules/pg/lib/native/client.js
Module not found: Error: Can't resolve 'pg-native' in '/Users/client/Documents/Projets/dashboard/backend/node_modules/pg/lib/native'
 @ ./node_modules/pg/lib/native/client.js 11:13-33
 @ ./node_modules/pg/lib/native/index.js
 @ ./node_modules/pg/lib/index.js
 @ ./node_modules/typeorm/platform/PlatformTools.js
 @ ./node_modules/typeorm/index.js
 @ ./src/index.ts
```

Thanks :-)

**Comment by LoicPoullain** [comment]
FoalTS is not designed to be bundled into a single output. Could `npm install --production` reduce the size of `node_modules`?

**Comment by jonathanroze** [comment]
Hi Loic, thank you for your prompt response :-).

I just try to add this flag and yes, it reduce by twice the node_modules's size thanks ! I guess that I can't do anything more to reduce that?

**Comment by LoicPoullain** [comment]
> I guess that I can't do anything more to reduce that?

The only thing that I see would be to remove the dependencies that are too heavy (mostly because they have many sub-dependencies). When I create a new project with `foal createapp`, the `node_modules` is 38M in production (26M because of TypeORM). What is your `node_modules` size? What is your size limit?

**Comment by jonathanroze** [comment]
That's okay! I just remove aws-sdk and mongo driver :-) ! Thanks for the production flag, pretty good discovery!
