### ISSUE TITLE
@foal/cli v2

### ISSUE THREAD

**Issue by anonimusprogramus** [FoalTS/foal#768]
This is not a real issue though, but is it possible to have **@foal/cli branch v2-0-0** right now with `npm install -g` ?

I'd love to try it, if possible.

Thank you.

**Comment by LoicPoullain** [comment]
The only way I see to achieve this is the one I use when I code the framework:
- Git clone the repository.
- Install the dependencies and build the package `packages/cli`.
- Then call `npm run link` in the package directory (this can be undone with `npm run unlink`).
- The command `foal` now refers to this local package directory.

**Comment by anonimusprogramus** [comment]
Oh I see. I thought it was like `npm install -g @foal/cli@v2-0-0` something. My bad. :smile: 

Thank you.
