### ISSUE TITLE
Translating FoalTS docs to Bahasa Indonesia

### ISSUE THREAD

**Issue by anonimusprogramus** [FoalTS/foal#776]
FoalTS documentation is awesome. It helps me building a good grasp of how a framework takes care of auth, orm, cli, etc. step by step thru Tutorials and Topic Guides.

If it's possible, I'd love to translate it — to Bahasa Indonesia. Hope v2 is a good starting point.

What do you think?

**Comment by LoicPoullain** [comment]
Thank you for your proposal.

> Hope v2 is a good starting point.

Yes, I think that starting from v2 would be better as many parts of the documentation will be upgraded.

> If it's possible, I'd love to translate it — to Bahasa Indonesia.

Adding translations to the documentation will require some work. There are questions that we have to answer:
- Currently the documentation uses Gitbook which AFAIK does not support translations. We would have to use another documentation framework and so another hosting. I heard of [docusaurus v2](https://v2.docusaurus.io/) and [vuepress](https://vuepress.vuejs.org/) which seem to be leading solutions at the moment, but I haven't really dug into the details to know what they're worth. Any experiences with them?
- The translated documentation may become outdated compared to the "official" one in English. How will we manage this? Do the solutions above can have smooth features to handle this.

**Comment by anonimusprogramus** [comment]
> * Currently the documentation uses Gitbook which AFAIK does not support translations. We would have to use another documentation framework and so another hosting. I heard of [docusaurus v2](https://v2.docusaurus.io/) and [vuepress](https://vuepress.vuejs.org/) which seem to be leading solutions at the moment, but I haven't really dug into the details to know what they're worth. Any experiences with them?

I have no idea, this would be my first attempt



> * The translated documentation may become outdated compared to the "official" one in English. How will we manage this? Do the solutions above have smooth features to handle this?

This too, can't say much.

But here is my own perspective that motivates me to do a translation.

I have some experiences with younger developers, they tend to gather informations as much as they can, just to get a good understanding about how one framework works. And they would prefer any languages, the less barrier the better. So a translated documentation could be a way to help them and I'm confident with FoalTS docs.

**Comment by LoicPoullain** [comment]
Ok, let's make an attempt after v2 is published (many parts of the documentation will me updated).

Looking at [docusaurus v2](https://v2.docusaurus.io/) and [vuepress](https://vuepress.vuejs.org/) and see if and how they solve the concerns mentioned above would help 👍

**Comment by LoicPoullain** [comment]
| Feature | Gitbook | Vuepress | Docusaurus 2 | Hexo |
| --- | :---: | :---: | :---: | :---: |
| Markdown integration | :white_check_mark: | :white_check_mark:  | :white_check_mark: | :white_check_mark: |
| Sync with Github (repo or Github Pages) | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| Possibility to add a sponsor's logo or a small ad | :x: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| Custom domain | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| Google Analytics (or equivalent) | :white_check_mark: | :white_check_mark: | :white_check_mark: | :expressionless: |
| Advanced search | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| SEO-friendly | :white_check_mark: | :white_check_mark: | :white_check_mark: | :grey_question: |
| Multi-language | :x: | :white_check_mark: | WIP | :white_check_mark: |
| Versions stable | :white_check_mark: | :white_check_mark: | :x: | :white_check_mark: |
| Design theme customizable | :x: | :white_check_mark: | :white_check_mark: | :grey_question: |
| Blog support | :x: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| Tabs support | :white_check_mark: | :expressionless: | :white_check_mark: | :x: |

 :expressionless: = to implement manually
:grey_question: = the docs say nothing

**Comment by anonimusprogramus** [comment]
Vuepress looks promising. Have you checked Saber?

https://saber.land/docs#comparisons

**Comment by LoicPoullain** [comment]
@anonimusprogramus saber's version is unstable (v0.11.7) and it hasn't been updated for 6 months. It is also unused (200 downloads/month). Let's use a more "mature" solution.

**Comment by LoicPoullain** [comment]
I'm working on the new doc website. Once it is published, the documentation will be ready to be translated by the community.

**Comment by LoicPoullain** [comment]
Docusaurus translation feature is on its way: https://github.com/facebook/docusaurus/issues/3317#issuecomment-742589241

**Comment by LoicPoullain** [comment]
Hey @anonimusprogramus , are you still interested in translating the docs to Bahasa Indonesia? If so, this is now possible and the website has a new French version. I wrote some [guidelines](https://github.com/FoalTS/foal/blob/master/.github/CONTRIBUTING.MD#translations) to get started. Feel free to let me know if you need any help.

First translations would mainly focus on the navbar, the docs sidebar and the tutorials as they are the most stable parts of the whole documentation.

**Comment by anonimusprogramus** [comment]
Yes I am, been waiting for guidelines. Thank you

**Comment by LoicPoullain** [comment]
@anonimusprogramus I don't know if you're already working on the translation, but here are a few things I've changed:
- At the end of the file `7-unit-testing` the zip link was outdated. It's `***-v2.zip` and not `***-v1.zip`.
- In the files `1-introduction` of both tutorials, the link to the version 1 of the documentation has been changed to https://foalts.org/docs/1.x/.
- Some other tiny changes here: https://github.com/FoalTS/foal/pull/888/commits/a7d9a71c044e53081545a0765d9fbbb5246e8369

**Comment by LoicPoullain** [comment]
I will try to upgrade docusaurus to the latest version to see how it goes. If it doesn't work, I guess we will be able to do it manually.

> PS: docker and lerna are not required to change the documentation.

**Comment by LoicPoullain** [comment]
I had trouble upgrading Docusaurus to alpha.75, so I ended up creating the json and markdown files directly to translate them into Bahasia Indonesia. I followed steps 1 to 6 [here](https://github.com/FoalTS/foal/blob/master/.github/CONTRIBUTING.MD#translations).

@anonimusprogramus you should now be able to translate the files directly but unfortunately you won't be able to see the "results" on you host. Please let me know if you need additional help.

I'm also working on a *React & Foal* tutorial that will probably be better than the current *Multi-User To-Do List*. So it might be better not to translate the second tutorial for now.

**Comment by anonimusprogramus** [comment]
Alright, cool. Let me try translating directly on github, looks fun to me.
Gonna check it out after fasting time.

**Comment by LoicPoullain** [comment]
Added some additional notes to translation guidelines: https://github.com/FoalTS/foal/commit/9eef05b8232b46f17cda50474a0f341032e79eef

**Comment by LoicPoullain** [comment]
First pages have been translated in #928 and #929 so I'm closing the issue. 👍
