### ISSUE TITLE
@foal/password 1.11.0 is missing

### ISSUE THREAD

**Issue by AleksandrSl** [FoalTS/foal#777]
All other packages we use in our project (`@foal/core`, `@foal/jwt`, `foal/swagger`, `@foal/typeorm`, `@foal/typestack`) have 1.11.0 version, but for `@foal/password` only 1.9.0 exists. Is it expected?

**Comment by LoicPoullain** [comment]
Thank you for reporting the issue. This was not expected. It looks like the deploy failed silently for `@foal/password`, `@foal/mongoose` and `@foal/cli`. Version 1.10.0 does not exist.

I'll try to deploy a version 1.11.1 and see how it goes.

**Comment by LoicPoullain** [comment]
Fixed with v1.11.1
