### ISSUE TITLE
error "The command line arguments should be array." when running a script

### ISSUE THREAD

**Issue by zeigo** [FoalTS/foal#783]
I got an error when I ran a script following the guide from [Groups & Permissions](https://foalts.gitbook.io/docs/topic-guides/authentication-and-access-control/groups-and-permissions)
```shell
foal run create-group name="Administrators" codeName="admin" permissions='[ "delete-users" ]'
```

**Comment by LoicPoullain** [comment]
On which OS are you?

**Comment by zeigo** [comment]
> On which OS are you?

windows

**Comment by zeigo** [comment]
Seems like when I input `permissions='[ "delete-users" ]'`, it is parsed to `permissions=[ delete-users ]` by Windows shell. And `'permissions=[ \"delete-users\" ]'` can be parsed to ` permissions=[ "delete-users" ]`.
To conclude, if someone uses Linux or git bash, just follow the guide. If Windows command line is used, input `'permissions=[ \"delete-users\" ]'`

**Comment by LoicPoullain** [comment]
Thank your for reporting and investing the problem 👍  Documentation has been changed.
