### ISSUE TITLE
How to get the raw request body?

### ISSUE THREAD

**Issue by rolandvar** [FoalTS/foal#791]
Hello everyone,

I need it to check the webhook signature of stripe like documented [here](https://stripe.com/docs/webhooks/signatures).

To perform this check I need the raw request body, how can I retrieve it only in this endpoint ?

In the stripe example they use `bodyParser.raw({type: 'application/json'})` how can i apply it to a single endpoint?

Greetings to all,
RV

**Comment by yoagauthier** [comment]
Hi ! 

On one hand, Foal converts the [request body](https://foalts.gitbook.io/docs/topic-guides/architecture/controllers#http-requests) to make it easier to deal with.

On the other hand, Stripe SDK [needs the raw body](https://github.com/stripe/stripe-node/issues/341) to verify the signature.

So you probably need to handle that webhook route yourself before Foal does it (and thus outside a controller). Hopefully, as Foal uses express underneath, you can pass middlewares to handle those webhooks [as preMiddlewares](https://foalts.gitbook.io/docs/topic-guides/cookbook/expressjs#pre-and-post-express-middlewares), and use `bodyParser.raw` as highlighted in the Stripe doc for that route.

**Comment by LoicPoullain** [comment]
Seems that the issue as been answered. As @yoagauthier mentioned, you can use this piece of code in `src/index.ts`:
```typescript
const app = createApp({
  preMiddlewares: [ bodyParser.raw({type: 'application/json'}) ]
})
```
I'm closing the issue. Feel free to re-open it if you still need help on this.
