### ISSUE TITLE
Add option for Config.get() functions to read directly from environment variable

### ISSUE THREAD

**Issue by GavinRay97** [FoalTS/foal#803]
Absolutely love this framework, I only have one small request to make -- for people who lean heavily on environment variables and use capitalized + underscored names, the fact that `readConfigValue` automatically calls the `dotToUnderscore` function (which replaces capital letters with an underscore) makes it impossible to read values like this directly: `MY_ENV_VAR_HERE`.

For example: `HASURA_GRAPHQL_JWT_SECRET -> hasura.graphql.jwtSecret`

```ts
  export function dotToUnderscore(str: string): string {
    return str
      .replace(/([A-Z])/g, letter => `_${letter}`)
      .replace(/\./g, '_')
      .toUpperCase();
  }

  private static readConfigValue(key: string): any {
    const underscoreName = dotToUnderscore(key);

    const envValue = process.env[underscoreName];
    if (envValue !== undefined) {
      return envValue;
    }

    const dotEnvValue = this.readDotEnvValue(underscoreName);
    if (dotEnvValue !== undefined) {
      return dotEnvValue;
    }
```

I have had to write a custom function for this:
```ts
import { Config as DefaultConfig } from '@foal/core'

type ValueStringType =
  | 'string'
  | 'number'
  | 'boolean'
  | 'boolean|string'
  | 'number|string'
  | 'any'

export class Config extends DefaultConfig {
  static find<T extends ValueStringType>(key: string, type?: T, defaultVal?: any) {
    const convertedKey = key.replace(/_/g, '.').toLowerCase()
    if (type && defaultVal) return Config.get2(convertedKey, type, defaultVal)
    if (type) return Config.get2(convertedKey, type)
    else return Config.get2(convertedKey)
  }

  static findOrThrow<T extends ValueStringType>(
    key: string,
    type?: T,
    message?: string
  ) {
    const convertedKey = key.replace(/_/g, '.').toLowerCase()
    if (type && message) return Config.getOrThrow(convertedKey, type, message)
    if (type) return Config.getOrThrow(convertedKey, type)
    else return Config.getOrThrow(convertedKey)
  }
}
```

Maybe `readDotEnvValue` could be `public`, or the `Config.get()` functions have an alternative which doesn't alter the env var value?

Thank you =D

**Comment by LoicPoullain** [comment]
Hi @GavinRay97  

Thank you for submitting your proposal.

The configuration system will be improved and, starting from version 2, the framework will have a `Env.get` to access directly environment and `.env` variables.

I'm closing the issue in favor of #805 to avoid duplicates.
