### ISSUE TITLE
[AJV] Custom validation errors

### ISSUE THREAD

**Issue by Sharlaan** [FoalTS/foal#809]
I'm trying to implement custom error messages for AJV validation objects in `@ValidateBody`, using plugin `ajv-errors` (as suggested in AJV docs)

but FoalTS seems to ignore any `errorMessage` ?

**Comment by LoicPoullain** [comment]
The framework needs to be updated to support the `settings.ajv.jsonPointers` configuration. This can be done just after the release of v2.

**Comment by LoicPoullain** [comment]
It seems that `ajv-errors` do not require anymore the `jsonPointers` option: https://github.com/ajv-validator/ajv-errors#usage.

So settings `allErrors: true` in the configuration and calling `require("ajv-errors")(getAjvInstance())` before `createApp` should work.

`getAjvInstance` can be imported from `@foal/core`.

Let me know if this works.

**Comment by LoicPoullain** [comment]
@Sharlaan I added some documentation on this. Feel free to re-open the issue if you still need help on this.
