### ISSUE TITLE
sqlite build upon foal createapp

### ISSUE THREAD

**Issue by anonimusprogramus** [FoalTS/foal#814]
`foal createapp my-app` took 2+ minutes, output 2500+ lines on console. It was log of **sqlite3** build.

I'm using
[x] Node v14.9.0
[x] FoalTS v1.11.1 
[x] Arch Linux 64bit

I don't remember having this happened before with FoalTS.

Any relation with this #586?

Thank you 

![Screenshot_20201011_104549](https://user-images.githubusercontent.com/7464749/95670074-91502e00-0bb1-11eb-8636-6cb448511564.png)

![Screenshot_20201011_104703](https://user-images.githubusercontent.com/7464749/95670095-b9d82800-0bb1-11eb-8531-d2602664d2d7.png)

![Screenshot_20201011_105925](https://user-images.githubusercontent.com/7464749/95670099-be044580-0bb1-11eb-9b9a-c30ad4cd5b01.png)

**Comment by LoicPoullain** [comment]
The `createapp` seems to work on Windows and MacOS. Could be related to one of your installations/configurations on your host (permission, compiler, etc)?

**Comment by anonimusprogramus** [comment]
Well, it might be. I'll look into it.

Meanwhile, closing this. Thank you.
