### ISSUE TITLE
GraphQL Resolvers in separate files

### ISSUE THREAD

**Issue by anonimusprogramus** [FoalTS/foal#815]
Referring to [this](https://foalts.gitbook.io/docs/topic-guides/api/graphql#using-a-service-for-the-root-resolvers) section, I understand that to specify **type definitions** in separate files, I can use the `schemaFromTypeGlob` function. What about **resolvers** in separate files? Is there any similar function for loading files all at once?

I tried this but failed,
```typescript
@dependency
resolvers: [TodoResolverService, AuthResolverService]
```

Thank you

**Comment by LoicPoullain** [comment]
The property type must be a service class, it cannot be an array of classes.

However, `TodoResolverService` and  `AuthResolverService` can both in be injected in a centralized service:
```typescript
class Resolvers {
  @dependency
  Todo: TodoResolverService;

  @dependency
  Auth: AuthResolverService;

  @dependency
  Query: QueryResolver;
}

class GraphQLCtrl {
  @dependency
  resolvers: Resolvers;
}
```

**Comment by anonimusprogramus** [comment]
Following yours, I finally get it working by importing this `Resolvers`:

```typescript
export class Resolvers {
  // injecting Services
  @dependency
  Todo: TodoResolverService

  @dependency
  Auth: AuthResolverService

  // listing two props (listTodo and login)
  listTodo = async (args, ctx) => {
    return await this.Todo.list(args, ctx)
  }

  login = async (args, ctx) => {
    return await this.Auth.login(args, ctx)
  }
}
```

And here's the `Controller`:

```typescript
export class ApiController extends GraphQLController {
  schema = schemaFromTypeGlob(join(__dirname, '../graphql/**/*.graphql'))

  @dependency
  resolvers: Resolvers
}
```

That leaves me wondering, though. I mean, when it was still single Service, ie:

```typescript
export class ApiController extends GraphQLController {
  schema = schemaFromTypeGlob(join(__dirname, '../graphql/**/*.graphql'))

  @dependency
  resolvers: AuthResolverService
}
```

I didn't have to list props, I just works.

I wonder if I missed something here, but is it possible to not relist all props when using centralized service?

Thank you.

**Comment by LoicPoullain** [comment]
It looks like I missed this. @anonimusprogramus do you still have problems with this?
