### ISSUE TITLE
Name of the framework : FoalTS vs Cryos

### ISSUE THREAD

**Issue by LoicPoullain** [FoalTS/foal#817]
Hi all!

*Update: see also comment https://github.com/FoalTS/foal/issues/817#issuecomment-725543325.*

Over the past few months I have been working hard to find a new name for the framework.

The reason for this is that the name *FoalTS* had several drawbacks:
- It is difficult to pronounce or read for non-English speakers.
- Many people have trouble remembering it.
- Many people don't know how to write it when they hear it.
- In fact, we are dealing with two names: *Foal* and *FoalTS*.
- As mentioned [here](https://github.com/FoalTS/foal/issues/490#issuecomment-592118058), for English speakers, *Foal* sounds like *fool* or *foul*, which is bad for the brand image.

It took a lot of time (finding 30 to 40 names, testing them orally and in writing with many people, checking their availability, registering the name to be protected, etc) but now it's here: the framework will be named **Cryos** in the future.

It will require some work to update the name and, starting with version 2, the packages will be named `@cryos/core`, `@cryos/typeorm`, etc. We will make sure (in documentation, articles, etc.) that in the next 12 months it will be easy to understand that FoalTS and Cryos are the same product.

**Comment by anonimusprogramus** [comment]
Oh wow, how come I missed this important issue.

FoalTS is Foal + TS. What about Cryos?

Coming from linux world, I'm familiar with OS-suffix. EasyOS, KaOS, PureOS, ClearOS, VyOS. And googling Cryos brought me result related with a bank.

Nevertheless, I :heart: FoalTS/Cryos

**Comment by changke** [comment]
I bet "Foal" is the English translation of your last name "Poullain"?

I personally like this name, and as mentioned above, "Cryos", from a first look doesn't seem to be anything related to a TypeScript framework.

And if I google for "cryos", the first result is a sperm bank...

Anyway, I like this framework no matter what it is called. :-)

Looking forward to v2.0, stay healthy too!

**Comment by LoicPoullain** [comment]
Thank you for sharing your feedback on this. If anyone wants to share their, feel to free to do so!

> I bet "Foal" is the English translation of your last name "Poullain"?

Yes it is.

**Comment by anonimusprogramus** [comment]
> Yes it is.

Undocumented :smile:

**Comment by josephfinlayson** [comment]
Also I see the sperm bank as being the first result. Why not rename FoalTS as Foal? I am a native English speaker and I just think of a baby deer

https://akns-images.eonline.com/eol_images/Entire_Site/2015712/rs_1024x759-150812103434-1024.bambi.cm.81215.jpg?fit=around|1024:auto&output-quality=90&crop=1024:auto;center,top

**Comment by LoicPoullain** [comment]
I add this comment in addition to the qualitative answers for those who don't feel like adding a comment.

If you prefer to keep FoalTS (or Foal), you can add the emoticon ❤️ .
If you prefer to change the name to Cryos, you can add the emoticon 🎉 .

(And if you like both, you can add both emoticons).

**Comment by LoicPoullain** [comment]
From your feedback, it seems that _Foal_ wins. Based on the previous comment, most voters either prefer Foal/FoalTS or agree with both names, so let's keep Foal.

Other native English speakers also said that it just made them think of a baby deer and not of `foul`, so I think that should be fine.

Maybe the framework will be more designated as *Foal* is the future rather than *Foal TS* to be more *warm* and easier to pronounce / remember. What do you think about that?
