### ISSUE TITLE
Detach Permission/Group logic from Foal Auth Implementation  

### ISSUE THREAD

**Issue by JarekToro** [FoalTS/foal#825]
Hello LoicPoullain I so far really appreciate this framework. Though admittedly I am early into my evaluation. 

I use Auth0 for authenticating. And I was glad to see the token validation for auth0 in the docs.

However it seems that all other aspects of authentication / authorization are tied to a Foal setup. 

As a small example the @HasPermission is tied to the ORM user object.

Now I have made a custom hook to achieve my own permission check in auth0 which works fine.

However I see benefit to allow the authentication and authorization aspects to be more generic as many times in companies existing auth infra already exist and it would be easier to adapt this new tool if it was not tied so directly to foal implementation.

*disclaimer
I have read into the docs but have not seen all the docs. If I am missing something please let me know 

Also really this is a great framework. Just wanted to highlight a potential improvement.

**Comment by LoicPoullain** [comment]
> Hello LoicPoullain I so far really appreciate this framework.

Glad to hear it!

> Now I have made a custom hook to achieve my own permission check in auth0 which works fine.

Can you share your code on this? It will be easier to discuss this aspect on a concrete example. Thanks!

**Comment by JarekToro** [comment]
Sure so when you authenticate with Auth0 the jwt can container a permissions array like so 
```ts 
  export interface UserInfo {
        iss: string;
        sub: string;
        aud: string[];
        iat: number;
        exp: number;
        azp: string;
        scope: string;
        permissions: string[]; // Here
    }
```
so the hook is as simple as
```ts
export function HasPerm(perm:string): HookDecorator {
  return Hook(async (ctx, services) => {

    if (!ctx.user.permissions.includes(perm)){
      return new HttpResponseForbidden()
    }

  });
}

```

**Comment by LoicPoullain** [comment]
Thank you for the details and sorry for the late reply.

The permission utilities (`Permission`, `Group`, `UserWithPermissions`) are provided in case the application does not use an external auth provider that has such features. In the case of Auth0, it already provides a permission system on its own and it looks like adding a hook to use their system seems pretty straightforward.

I'd rather not to go to implement a more generic permission system (which would add more maintenance to the framework) and leave the liberty to users to implement custom hooks when using 3p auth providers. This is why I'm closing this issue.
