### ISSUE TITLE
How to exclude some methods when hooks decorate a controller

### ISSUE THREAD

**Issue by zeigo** [FoalTS/foal#826]
for example, I have a `UserController` needing JWT support, so I add `@JWTRequired()`. But one of the method doesn't need JWT, how to exclude this method?

**Comment by JarekToro** [comment]
I imagine you only add it to the routes that need it. Perhaps create a subcontroller for unprotected routes and a controller for protected routes and only and the decorator to the protected controller.

**Comment by LoicPoullain** [comment]
It's not possible. As @JarekToro mentioned you have to apply the hook separately on each method that requires authentication.

**Comment by zeigo** [comment]
Thanks. I create two subcontrollers, one with JWT, the other not. It works now
