### ISSUE TITLE
Interested in a newsletter?

### ISSUE THREAD

**Issue by LoicPoullain** [FoalTS/foal#839]
Hi everyone,

Would you be interested in a newsletter? I was thinking of having two:
- A security list (security@foalts.org) to be informed when a security patch is released.
- A monthly or quarterly (every 3 months) newsletter (hello@foalts.org) for practical tips and the latest news on the framework. It would also present the new features of the latest releases.

**Comment by LoicPoullain** [comment]
Add a 👍  if you'd be interested in a security newsletter.

**Comment by LoicPoullain** [comment]
Add a 👍  if you're interested in the monthly or quarterly newsletter.

**Comment by LoicPoullain** [comment]
Also feel free to share a comment if you have any tips or ideas about what you would like to see. 😉

**Comment by haikyuu** [comment]
First of all, thanks for building this great library.

I was thinking of adding a contributors section to the newsletter that would discuss:
- Roadmap of foal
- Good issues for First time contributors
- How foal was built to facilitate contributions

**Comment by LoicPoullain** [comment]
The newsletter has been created (one mail every two months). More details will be given on Discord.
