### ISSUE TITLE
foal run script error

### ISSUE THREAD

**Issue by JuanVqz** [FoalTS/foal#842]
I just update my project to v2 which is super useful because now we don't need to remember the order and a bunch of commands.

The `npm run makemigrations` command generated a new migration named `date-migration.ts` and I had conflicts with my old migrations when I ran `npm run migrations` command, in order, to solve this problem I removed my previous migrations.
Would we use a custom name per migration with this new approach?

and I saw this error too, the weird thing here is that I have connection to my DB.
I don't know if this is a real error but I wanted to report it,
regards!
![screenshot_2020-12-06_16:57:17](https://user-images.githubusercontent.com/7331511/101295598-42ef9200-37e4-11eb-8d21-51fca1205175.png)

**Comment by JuanVqz** [comment]
I had another problem running this test, can you help me, please?
I don't know what is the table reference
QueryFailedError: cannot truncate a table referenced in a foreign key constraint

```typescript
import { ok, strictEqual } from 'assert';

import { Context, createController, getHttpMethod, getPath, hashPassword } from '@foal/core';

import { createConnection, getConnection, getRepository } from 'typeorm';

import { User } from '../entities';
import { AuthController } from './auth.controller';

describe('AuthController', () => {

  let controller: AuthController;
  let user: User;

  before(() => createConnection());

  after(() => getConnection().close());

  beforeEach(async () => {
    controller = createController(AuthController);

    const repository = getRepository(User);
    const password = await hashPassword('chapulines123');
    await repository.clear();
    user = await repository.save({
      name: 'Valid1',
      email: 'valid1@domain.com',
      password: password,
      code: 'A1'
    });
  });

  describe('#login', () => {

    xit('responses at POST /login', () => {
      strictEqual(getHttpMethod(AuthController, 'login'), 'POST');
      strictEqual(getPath(AuthController, 'index'), '/login');
    });

    describe('with valid user', () => {

      xit('returns a token authentication', async () => {
        const ctx = new Context({
          body: { email: user.email, password: 'chapulines123' }
        });
        const response = await controller.login(ctx);

        console.log(response);
        ok(response.body);
      });

    });

  });
});

```


```typescript
[1]   1) AuthController
[1]        "before each" hook for "responses at POST /login":
[1]      QueryFailedError: cannot truncate a table referenced in a foreign key constraint
[1]       at new QueryFailedError (src/error/QueryFailedError.ts:9:9)
[1]       at Query.callback (src/driver/postgres/PostgresQueryRunner.ts:178:30)
[1]       at Query.handleError (node_modules/pg/lib/query.js:128:19)
[1]       at Client._handleErrorMessage (node_modules/pg/lib/client.js:335:17)
[1]       at /home/itox/Code/me/time_clock/backend/node_modules/pg/lib/connection.js:115:12
[1]       at Parser.parse (node_modules/pg-protocol/src/parser.ts:102:9)
[1]       at Socket.<anonymous> (node_modules/pg-protocol/src/index.ts:7:48)
[1]       at addChunk (_stream_readable.js:309:12)
[1]       at readableAddChunk (_stream_readable.js:284:9)
[1]       at Socket.Readable.push (_stream_readable.js:223:10)
[1]       at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by LoicPoullain** [comment]
> I had another problem running this test, can you help me, please?
> I don't know what is the table reference
> QueryFailedError: cannot truncate a table referenced in a foreign key constraint

`await repository.delete({})`?

**Comment by LoicPoullain** [comment]
> The `npm run makemigrations` command generated a new migration named `date-migration.ts` and I had conflicts with my old migrations when I ran `npm run migrations` command, in order, to solve this problem I removed my previous migrations.

Old migrations must not be removed (unless you fully delete and recreate the database). The `migrations/` directory needs to keep track of the migration history to have a replicable environment everywhere. Removing the old ones may also potentially make TypeORM migration command fail.

Sometimes, it happens that an auto-generated migration does not work. For example, if you add a NOT NULL column but you already have data in your data, running the migration will not work. You will have to modify the content of the migration file yourself.

> Would we use a custom name per migration with this new approach?

The command does not allow that at the moment because it's in bash and they were some incompatibilities between Windows and Mac to make it work everywhere. However you can rename the file and its content before building and running the migrations.

> and I saw this error too, the weird thing here is that I have connection to my DB.

Are you sure to have a `await createConnection()` in your script?

**Comment by JuanVqz** [comment]
you are right, 
1. the `await repository.delete({})` works.
2. the migrations yes I had my DB without tables when I ran the new command I don't care about the info I still in development, just wanted to report it.
3. Yes, I had the `await createConnection()` but after finding something in the DB, that was the issue

Thank you for all!
