### ISSUE TITLE
First makemigrations and postgres fails

### ISSUE THREAD

**Issue by Sharlaan** [FoalTS/foal#860]
I just created a bare new project using `createapp -G -I`, then modified my env file and configs to use posgtres instead of sqlite.

Problem occurs when i try to create migrations: `yarn makemigrations`

> yarn run v1.22.5
$ foal rmdir build && tsc -p tsconfig.app.json && npx typeorm migration:generate --name migration && tsc -p tsconfig.app.json
**Error during migration generation:
error: la base de donn�es � vuetube � n'existe pas**
    at Parser.parseErrorMessage (C:\Projets\Vuetube\api\node_modules\pg-protocol\dist\parser.js:278:15)
    at Parser.handlePacket (C:\Projets\Vuetube\api\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (C:\Projets\Vuetube\api\node_modules\pg-protocol\dist\parser.js:39:38)
    at Socket.<anonymous> (C:\Projets\Vuetube\api\node_modules\pg-protocol\dist\index.js:10:42)
    at Socket.emit (node:events:379:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at Socket.Readable.push (node:internal/streams/readable:227:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 169,
  severity: 'FATAL',
  code: '3D000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'd:\\pginstaller_13.auto\\postgres.windows-x64\\src\\backend\\utils\\init\\postinit.c',  
  line: '888',
  routine: 'InitPostgres'
}
npm ERR! code 1
npm ERR! path C:\Projets\Vuetube\api
npm ERR! command failed
npm ERR! command C:\tools\Cmder\vendor\git-for-windows\bin\bash.exe -c typeorm "migration:generate" "--name" "migration"

Versions used :
- Windows 10 + Cmder
- PostgreSQL 13.1
- @foal/core & @foal/typeorm 2.0.0
- Node 15.6.0
- npm 7.4.0
- TS 4.1.3
- typeorm 0.2.30
- pg 8.5.1

Question: Does this script supposed to create the database ?? the error sound like i have to create it manually ?

Note: script works perfectly after i created the db manually using `createdb -U postgres my-database-name`

Suggestion: might be interesting to expand the makemigrations script so it covers some common edge cases like this (here with a `CREATE DATABASE IF EXIST`)
... and add some warning in the [Databases > Inittial Configuration](https://foalts.org/docs/databases/typeorm#initial-configuration) section in docs.

**Comment by LoicPoullain** [comment]
Yes the database is not supposed to be auto-created. It only works with SQLite because SQLite auto-creates the db if none already exists.

I took a look a while ago and it seemed that, in order to create a db, I needed first to connect to an existing db to create a new one. I couldn't call `createConnection` if no db name was already provided in `ormconfig.json`. Would you have an idea to get around this?

I wonder also if it is usual to create a database in a migration and if it has drawbacks. Does anybody has an experience to share on this?

**Comment by Sharlaan** [comment]
In retrospective, i actually don't think migrations should also be responsible for db creation.
**I was more thinking on Typeorm side, at first parsing the ormconfig file.**
or  
a workaround would be a specific internal script from foal which silently check if db exist before actually run `makemigration` ?

Nonetheless, here is a snippet of my README regarding installation :

> 
> Create the databases `<YOUR_DATABASE_NAME>-*` (typeorm won't create it if not exist !)
> 
> ```console
> createdb -U postgres <YOUR_DATABASE_NAME>
> createdb -U postgres <YOUR_DATABASE_NAME>-e2e
> createdb -U postgres <YOUR_DATABASE_NAME>-test
> ```
> 
> Run migration queries to create tables
> 
> ```console
> yarn migrations
> ```
> 
> ... then populate tables using the shell-scripts from scripts folder. Example below :
> 
> ```console
> foal run create-user channelName="<my uber name>" email="awesome.name@gmail.com" password="123456abcdef"
> ```
> 
> ... should display for each successfully inserted user :
> 
> <pre>
> User {
>   channelName: 'my uber name',
>   email: 'awesome.name@gmail.com',
>   password: 'pbkdf2_sha256$150000$utAROMwDWVWLhTKO+//K4w==$8uoLrwiK4CRn0r4k7wcKarhFD9i9JLxDHFJxeuYKjCQ=',  // Hashed password
>   id: 1  // Auto-generated ID
> }
> </pre>
> 
> Delete all data (WARNING this will destroy ALL tables AND database !)
> 
> ```console
> dropdb -U postgres <YOUR_DATABASE_NAME>
> ```

The `createdb` and `dropdb` commands are natively installed with PostgreSQL.
You are correct with needing to first connect to the default `postgres` with default user `postgres` to perform DB creation/deletion.

**Comment by LoicPoullain** [comment]
I think that DB creation should be treated outside of the framework. It's specific to the environment in which the application is run (local, cloud, etc) and so the needs may vary between developers. It is also something that we need to deal with only once in the application lifetime, so I'd rather not to add a new feature for this. This is why I'm closing this issue.

Thank you for sharing your README commands 👍
