### ISSUE TITLE
Support for local .env files

### ISSUE THREAD

**Issue by luxaritas** [FoalTS/foal#877]
My preferred workflow is to check in .env (.env.production, ...) files, but to gitignore .env.local (.env.production.local, ...). It seems like this is relatively common practice. Could this be supported?

**Comment by LoicPoullain** [comment]
Not sure to understand your issue. What's keeping you from adding `.env.local` and `.env.production.local` to `.gitignore`? What are trying to achieve?

**Comment by luxaritas** [comment]
What I'm looking for is Foal to read these .local files by default in the config module. Ie the process would be as follows (in reverse priority order, as .env doesnt override existing env vars with new .env contents)

1. Read .env.<NODE_ENV>.local
2. Read .env.<NODE_ENV>
3. Read .env.local
4. Read .env

As far as I can tell, only steps 2 and 4 are currently performed

**Comment by ognjenjevremovic** [comment]
Hey @LoicPoullain 👋 

I have been introduced to `foal` not so long ago (through the article on `dev.to`) and I was really into the project. I didn't use it in production apps (just yet), but rather tested the framework on some side projects.
I would like to contribute to `foal` and I have found this issue that it seems is welcoming to first time contributors to the project, such as I am.

Would you mind me asking if this issue has been **approved** in a way that is has passed some sort of internal *triage* and that it aligns with the project goals?
I'll be willing to provide PR for this functionality if that's ok in terms of feature support.

**Comment by LoicPoullain** [comment]
Ok, let's add this feature.

@ognjenjevremovic I'm assigning the task to you. 👍 You'll find some guidelines on how to set up the environment [here](https://github.com/FoalTS/foal/blob/master/.github/CONTRIBUTING.MD). The files that will probably require an update are  `env.ts` and `env.spec.ts`. Feel free to let me know if you have any questions.

PS: I noticed there is a typo at line 119 of `env.spec.ts` (bad copy past), so if you could fix it at the same time, it would be great 👍

**Comment by LoicPoullain** [comment]
Feature added in v2.3
