### ISSUE TITLE
Upgrade AJV version to ^7.0.0

### ISSUE THREAD

**Issue by Mvrlex** [FoalTS/foal#881]
Hi,

I have stumbled upon Foal on my search for the perfect TypeScript backend framework, and I really like it so far.
One suggestion: Would it be possible to upgrade the **AJV version to 7**? This adds better TypeScript support which would allow typing for schemas.

```typescript
import { JSONSchemaType } from 'ajv';

...

export const createTodoSchema: JSONSchemaType<Todo> = {
  additionalProperties: false,
  properties: {
    text: { type: 'string' },
  },
  required: [ 'text' ],
  type: 'object'
};
```

**Comment by LoicPoullain** [comment]
> I really like it so far.

Glad to hear it!

We cannot change the version of AJV that Foal uses internally as it might break existing applications (version 7 has some [breaking changes](https://github.com/ajv-validator/ajv/releases/tag/v7.0.0)).

However, if it is just to take advantage of type checking, it is possible to install `ajv@7` as a dependency of your project. Foal will still continue to use v6 internally but you will be able to import the `JSONSchemaType` interface in your application.

```
npm install ajv
```

```typescript
import { IAppController, Post, ValidateBody } from '@foal/core';
import { createConnection } from 'typeorm';
import { JSONSchemaType } from 'ajv';

interface Todo {
  text: string;
}

const createTodoSchema: JSONSchemaType<Todo> = {
  additionalProperties: false,
  properties: {
    text: { type: 'string' },
  },
  required: [ 'text' ],
  type: 'object'
};

export class AppController implements IAppController {

  @Post('/todos')
  @ValidateBody(createTodoSchema)
  createTodo() {
    // ...
  }

  async init() {
    await createConnection();
  }
}

```

Does it help?

**Comment by Mvrlex** [comment]
Sorry for the wait. Your suggestion works. I'll close the ticket.
