### ISSUE TITLE
Context typing issue

### ISSUE THREAD

**Issue by Sharlaan** [FoalTS/foal#890]
```ts
const CREDENTIALS_SCHEMA = {
  additionalProperties: false,
  properties: {
    email: { type: 'string', format: 'email' },
    password: { type: 'string' },
  },
  required: ['email', 'password'],
  type: 'object',
};

// @Log('AuthController', { body: true })
export class AuthController {
  @Post('/register')
  @ValidateBody(CREDENTIALS_SCHEMA)
  async register(context: Context<User>) {
    const { email, password } = context.request.body; // ==> TS can not infer request and body's type ?
    ...
```
![image](https://user-images.githubusercontent.com/2692027/110243766-0acf2b00-7f5c-11eb-9739-c4301b257cf3.png)

All requests' payload gets any as type ...
**How to get proper typings for payload ?** (_without relying upon `as CustomType`_ which sounds kinda "forcing" TS to me)

Versions:
Node 14
Foal 2.2
TS 4.2 (strict ON)

**Comment by LoicPoullain** [comment]
Unfortunately, we're reaching the limits of the language here. TypeScript does not provide the ability for decorators to force the types of the method arguments. Therefore, a hook cannot be used to modify or precise the type of `ctx` (and consequently the type of `ctx.request.body`).

The only thing that the language allows is, when using classes as argument types, to save them in an identity mapper. Then a decorator can use it at runtime. This is apparently what Nest and routing-controllers use when doing validation with validation classes. This is not used in Foal though.

```typescript
class Bar {}
class Foo() {

  bar(o: Bar) {
    // At runtime, we can know that the first argument is of type Bar.
  }

}
```

A workaround that can be used in your example is to add a third argument that will represent the request `body`. But it still does not solve the problem as the type is still forced. It might look a bit less dirty though.

```typescript
async register(context: Context<User>, params: any, body: MyInterface) {
  // ...
}
```

I will be opening an issue soon to discuss how type safety and schema redundancy are handled in Foal and to see what can be done to improve this.
