### ISSUE TITLE
createApp ReturnType

### ISSUE THREAD

**Issue by Sharlaan** [FoalTS/foal#892]
![image](https://user-images.githubusercontent.com/2692027/110253517-14bc5280-7f8b-11eb-95d9-15e0178b1380.png)

Is it possible to define something instead of returning `Promise<any>` ?

**Comment by LoicPoullain** [comment]
The returned object is promise of an Express object. Previously, Foal was using `@types/express` but using `@types/*` packages were causing a lot of trouble in maintaining the framework (instability). This is why the dependency has been removed and the return type is not `any`.

Why error do you get? Is is a linting or a compiler error? How does your `tsconfig` file look like?

One way to get around this would be to install manually `@types/express` and then to use this syntax:
```
import { Express } from 'express';
// ...

const app: Express = await createApp(...);
```

I don't know if `Express` is the correct name. Maybe it's `App` or `express.Express`, etc.

**Comment by Sharlaan** [comment]
Thanks for your answer.

> What error do you get ?
`Unsafe assignment of an any value.` eslint(@typescript-eslint/no-unsafe-assignment)

My tsconfig :
```json
{
  "compilerOptions": {
    "target": "es2020",                       /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019' or 'ESNEXT'. */
    "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
    "lib": [ "dom", "es2020" ],               /* Specify library files to be included in the compilation. */
    "skipLibCheck": true,
    "sourceMap": true,                        /* Generates corresponding '.map' file. */
    "outDir": "build",                        /* Redirect output structure to the directory. */
    "rootDir": "src",                         /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */
    "strict": true,                           /* Enable all strict type-checking options. */
    "noImplicitAny": true,                    /* Raise error on expressions and declarations with an implied 'any' type. */
    "esModuleInterop": true,                  /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
    "experimentalDecorators": true,           /* Enables experimental support for ES7 decorators. */
    "emitDecoratorMetadata": true,            /* Enables experimental support for emitting type metadata for decorators. */
    "forceConsistentCasingInFileNames": true /* Disallow inconsistently-cased references to the same file. */
  },
  "include": [ "src/**/*.ts" ]
}

```

My problem is just i'm using TS in strict mode as i don't like `any` (or `unknown`)

**Comment by Sharlaan** [comment]
Only way i found to make TS strict happy were using the dirty `as` :
```ts
  import { Application } from 'express';

  // forcing ReturnType of createApp as Application from express, instead of any ...
  const app = (await createApp(AppController)) as Application;
```

**Comment by LoicPoullain** [comment]
Thank you for sharing this code.

Unfortunately, I cannot propose something better. The `createApp` will continue to return the type `Promise<any>` because
- integrating `@types/express` was causing to much trouble in maintaining the framework in the past
- and implementing on our own a custom interface to return could lead to type conflicts in the future with other typed libraries using `@types/express`.

This is why I'm closing this issue. Thank you for your contribution on this 👍
