### ISSUE TITLE
Discord oauth authentication

### ISSUE THREAD

**Issue by Shair17** [FoalTS/foal#908]
I've try to add discord authentication to my application, but I didn't get it.

**Comment by LoicPoullain** [comment]
What code do you have? Is it based on the [AbstractProvider](https://foalts.org/docs/authentication-and-access-control/social-auth/#custom-provider)?

> https://discord.com/developers/docs/topics/oauth2

**Comment by LoicPoullain** [comment]
It might be also related to #754. Do you get `InvalidStateError`s?
