### ISSUE TITLE
Website: broken link to multi-user todo list intro

### ISSUE THREAD

**Issue by estaub** [FoalTS/foal#922]
https://foalts.org/docs/tutorials/multi-user-todo-list/1-Introduction is broken.

Looks like this isn't ready yet.

**Comment by LoicPoullain** [comment]
Same as https://github.com/FoalTS/foal/issues/921#issuecomment-832071055

**Comment by estaub** [comment]
It's working now.  I don't think it was on my end - other parts of the site were ok.
