### ISSUE TITLE
Watch config changes

### ISSUE THREAD

**Issue by zeigo** [FoalTS/foal#945]
Is there a way to watch config changes? For example, restart program if files in config folder changes when running `npm run develop`.

**Comment by LoicPoullain** [comment]
@zeigo in your `package.json`, you can replace your `develop` command with the following:
```json
{
  "develop": "npm run build && concurrently \"tsc -p tsconfig.app.json -w\" \"supervisor -w ./build,./config -e js,json,yml --no-restart-on error ./build/index.js\""
}
```

New projects starting with v2.5 will use this command and watch config files.

**Comment by LoicPoullain** [comment]
The PR has been merged, I'm closing the issue. If the above command doesn't work on your side, feel free to let me now.
