### ISSUE TITLE
Question: Upgrading from FoalTS 2.0.0 to 2.4.0

### ISSUE THREAD

**Issue by warren-gallagher** [FoalTS/foal#959]
Wondering if there is a preferred manner of upgrading FoalTS and the various dependencies it has.
Current:
```
    "@foal/core": "^2.0.0",
    "@foal/password": "^2.2.0",
    "@foal/storage": "^2.3.0",
    "@foal/swagger": "^2.2.0",
    "@foal/typeorm": "^2.0.0",
    "better-sqlite3": "~7.1.2",
    "typeorm": "0.2.26"
```

**Comment by LoicPoullain** [comment]
I would recommend to always keep the same version numbers for each of your package (i.e. every pkg uses 2.0 or 2.3 or 2.4). 

You can simply update your package.json with the values `^2.4.0` and run `npm install`.

Or run the following commands:
```bash
npm upgrade @foal/core @foal/typeorm # ...
```

Both should work fine.

**Comment by warren-gallagher** [comment]
Many thanks. Did the upgrade as you suggested and it went smoothly.
