### ISSUE TITLE
Add possibility to change default logger for express

### ISSUE THREAD

**Issue by HRK44** [FoalTS/foal#967]
As of now, you are using `morgan` to log requests.

I want to know if it's possible to use an other logger, such as `express-pino-logger`, if not, would it be possible to select a custom logger instead of `morgan` ?

Thanks

**Comment by LoicPoullain** [comment]
You can disable morgan in the configuration with the key `settings.loggerFormat`:
```json
{
  "settings": { "loggerFormat": "none" }
}
```

Then, you will be able to add your custom `express-pino-logger` middleware with this page: https://foalts.org/docs/cookbook/expressjs/#custom-express-instance

**Comment by HRK44** [comment]
Ok thanks for your answer, I think it's doable this way.
