### ISSUE TITLE
Override JWT requirement on specific routes

### ISSUE THREAD

**Issue by HRK44** [FoalTS/foal#973]
I have an API with a lot of sub apis with a lot of routes. Basically most (~90%) of my routes require a JWT so I want to use the `@JWTRequired` hook on my top level API.

The thing is, on some of the routes I want a `@JWTOptional` but when I use it, it doesn't override the top level `@JWTRequired`. So in the end I can't use my top-level `@JWTRequired` and I have to write it on each route and repeat it a lot.

Is there a way I could have a top level one, and override on specific routes?

**Comment by LoicPoullain** [comment]
@HRK44 it's not possible. Foal's hooks are executed consecutively, so if the first `@JWTRequired` respond with a 400 error, the remaining hooks won't be executed.

Here two workaround that I see:
- Use different sub-controllers to group routes that require authentication and routes where authentication is optional.
- Use `@JWTOptional` at the top level and then the hook `@UserRequired` on the routes that require authentication.
