### ISSUE TITLE
Support newer versions of typeorm

### ISSUE THREAD

**Issue by HRK44** [FoalTS/foal#974]
I can correctly run my server with `typeorm 0.2.26`, any above that (starting `0.2.27`) breaks the DB connection and I can't launch my local dev server anymore.

Any plans on supporting newer versions?

**Comment by LoicPoullain** [comment]
What error do you have? Could you share your traceback?

**Comment by HRK44** [comment]
Sure.

With typeorm 0.2.27, I have this error :

```
[1] Error: getaddrinfo EAI_AGAIN ocalhost
[1]     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:69:26)
[1] Program node ./build/index.js exited with code 1
[1] 
[0] 
[0] 2:38:46 PM - Found 0 errors. Watching for file changes.
```
As you can see, the `l` of `localhost` is missing.

This is my default config that is loaded :

```
    "database": {
        "type": "postgres",
        "database": "env(DB_NAME)",
        "url": "env(DB_HOST)",
        "port": "env(DB_PORT)",
        "username": "env(DB_USER)",
        "password": "env(DB_PASSWORD)"
    }
```

and this is my env file :

```
#DATABASE
DB_USER=adminuser
DB_HOST=localhost
DB_PASSWORD=root123
DB_NAME=mydb
DB_PORT=5556
```

And this is the error with the latest typeorm 0.2.34 :

```
2:41:42 PM - Starting compilation in watch mode...
[0] 
[1] Error: connect ECONNREFUSED 127.0.0.1:5432
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16)
[1] Program node ./build/index.js exited with code 1
[1]
```

This time looks like the port is not pulled correctly (showing 5432 but port is set to 5556 in the .env file).

Let me know if you need more data, thanks

**Comment by LoicPoullain** [comment]
Thank you for the details.

It looks like you're giving the name of the host as URL:

```json
"url": "env(DB_HOST)",
```

Does the following configuration solve the problem?

```json
"host": "env(DB_HOST)",
```

**Comment by HRK44** [comment]
Good catch, works with `host`
