### ISSUE TITLE
npm outdated doesn't show latest version 2.5.0

### ISSUE THREAD

**Issue by HRK44** [FoalTS/foal#975]
Not sure if this is an issue from the foal package but I still mention it here.

I had version 2.0.0 on @foal/core and @foal/typeorm installed, when running `npm outdated` it doesn't show me the latest versions (2.5.0). I had to manually check cause I noticed the other packages were at 2.5.0 (@foal/jwt and some others).

Is this an issue with the foal package or is it a `npm outdated` issue?

**Comment by LoicPoullain** [comment]
How the dependencies are specified in the `package.json`. With the `^` or `~` character?

**Comment by HRK44** [comment]
> How are the dependencies specified in the `package.json`? With the `^` or `~` character?

`"typeorm": "0.2.26",`

**Comment by LoicPoullain** [comment]
Hmm, it might be a cache issue from the `npm` command. But this is not an issue from the foal package (it has been properly registered and deployed to npm), this is why I'm closing it.
