### ISSUE TITLE
Middleware Problem

### ISSUE THREAD

**Issue by kingdun3284** [FoalTS/foal#980]
I have to insert an express middleware between controller function and foal's default middleware. Since the middleware will be affected by the bodyparser it can't be added in premiddlewares. Maybe adding a afterPremiddlewares option?

**Comment by LoicPoullain** [comment]
Would it possible to add manually the body parser as premiddleware just before yours?
```typescript
preMiddlewares: [
 bodyParser(),
 yourMiddleware()
]
```

It looks like the body parser is not re-executed if it has been called before: https://github.com/expressjs/body-parser/blob/master/lib/types/json.js#L99

**Comment by kingdun3284** [comment]
I would try, but I think this is not a good approach. As I am using [mikro orm](https://mikro-orm.io/docs/identity-map/), it indicates :
```
app.use((req, res, next) => {
  RequestContext.create(orm.em, next);
});
```
`You should register this middleware as the last one just before request handlers and before any of your custom middleware that is using the ORM. There might be issues when you register it before request processing middleware like queryParser or bodyParser, so definitely register the context after them.`

So, I think it is better to have a place to put premiddlewares after the defaults one.

**Comment by LoicPoullain** [comment]
@kingdun3284 this can be added. Do you want to submit a PR? 

```typescript
export interface CreateAppOptions {
  expressInstance?: any;
  serviceManager?: ServiceManager;
  preMiddlewares?: (Middleware|ErrorMiddleware)[];
  afterPreMiddlewares?: (Middleware|ErrorMiddleware)[];
  postMiddlewares?: (Middleware|ErrorMiddleware)[];
}
```

Regarding the tests, I think we can have something like this:
- we send a post request with a body. This body is parsed normally by Foal pre-middlewares (i.e. the express body parser)
- we add a custom after pre-middleware which overrides the request body.
- we check in the controller method, that the body has been properly overridden.

**Comment by kingdun3284** [comment]
@LoicPoullain Sure, I can create a PR for it.

**Comment by josephfinlayson** [comment]
Would it be also possible just to create a custom array of middlewares that can override to any custom order?

**Comment by LoicPoullain** [comment]
Hi @josephfinlayson 👋 

Foal's internal middlewares cannot be overridden because in many parts of the framework it is expected them to have been run. This is, for example, the case with the `Context.request` type, whose `body` and `cookies` properties are always set, or with the `@UseSessions` hook, which reads the values of `ctx.request.body._csrf` or `ctx.request.cookies.sessionID`.

`afterPreMiddlewares` will be the last option that will be added to `createApp` to provide a custom array of middlewares. No more options of this kind will be added in the future. 👍

**Comment by LoicPoullain** [comment]
Feature added in v2.7.
