### ISSUE TITLE
MySQL - SSL Certificate (CA) path in json settings

### ISSUE THREAD

**Issue by lcnvdl** [FoalTS/foal#981]
Hello!

I'm trying to configure my Azure Mysql Database. I couldn't find on internet 8and in the official Foal.ts website) how to configure the SSL CA Path of my database. My current configuration is:

```
  "database": {
    "type": "mysql",
    "host": "mydatabase.mysql.database.azure.com",
    "port": 3306,
    "username": "myuser",
    "password": "mypassword",
    "database": "mydatabase"
  }
```

How can I add my CA Cert path to the config . json?

Thanks in advance

**Comment by lcnvdl** [comment]
When I try to specify the cert file I got an error:

```json
  "database": {
    "type": "mysql",
    "host": "mydatabase.mysql.database.azure.com",
    "port": 3306,
    "username": "myuser",
    "password": "mypassword",
    "database": "mydatabase",
    "ssl": {
        "C:\\sql\\DigiCertGlobalRootCA.crt.pem"
    }
  }
```

Command:
```bash
npm run makemigrations
```

Error message:
```
Error during migration generation:
Error: ER_SECURE_TRANSPORT_REQUIRED: Connections using insecure transport are prohibited while --require_secure_transport=ON.
```

**Comment by kingdun3284** [comment]
This is not an foalts issue. Try to find the document of the orm you are using. By default, it should be typeORM.

**Comment by lcnvdl** [comment]
Hello. Then, How can I configure the SSL certificates using the Foalts Json configuration?

**Comment by kingdun3284** [comment]
Import config from foalts in your orm.config.js

**Comment by lcnvdl** [comment]
> Import config from foalts in your orm.config.js

Thank you very much! Now I understand how it works. I think that I can solve the problem with that information.

Best regards,
LR
