### ISSUE TITLE
migrations and different database types for dev/production

### ISSUE THREAD

**Issue by warren-gallagher** [FoalTS/foal#984]
I've been developing a new app using sqlite3 and have just started preparing for production using PostgreSQL. 

The migrations were created while I was using sqlite3.

When I ran:
``` bash
NODE_ENV=production npm run migrations
```
I got errors regarding AUTOINCREMENT.

I deleted my migrations and ran:
``` bash
NODE_ENV=production npm run make migrations
NODE_ENV=production npm run migrations
```
Everything worked this time.

Do I need different migrations for different database types? If so, is there a way to manage this by maintaining different migrations scripts in FoalTS?

BTW, in just a few hours I was able to convert my application from using local Disk and sqlite to using S3 Disk and PostgreSQL in only a few hours. Great job on this framework.

**Comment by kingdun3284** [comment]
You need migration for different db type.

**Comment by warren-gallagher** [comment]
OK. Unfortunate but understandable. It may be worth mentioning that in the database section of the documentation.

I was able to modify ormconfig.js, config/default.json and config/production.js so that I can maintain different migrations for different database types.
