### ISSUE TITLE
Typing issue with ajv-formats plugin

### ISSUE THREAD

**Issue by mohammaduvez** [FoalTS/foal#988]
I want to use [ajv-formats](https://ajv.js.org/packages/ajv-formats.html) Plugin.
I tried `getAjvInstance` method, 
```
import addFormats from 'ajv-formats';
...
export class AppController implements IAppController {
  async init(): Promise<void> {
    addFormats(getAjvInstance());
...
  }
...
}
```
<details>
<summary>but it has type mismatch.</summary>
Argument of type 'import("../node_modules/@foal/core/node_modules/ajv/lib/ajv").Ajv' is not assignable to parameter of type 'import("../node_modules/ajv-formats/node_modules/ajv/dist/core").default'.
  Type 'Ajv' is missing the following properties from type 'Ajv': opts, logger, scope, schemas, and 17 more.
</details>

**Comment by LoicPoullain** [comment]
It seems to be related to types that don't match. I assume `ajv-formats` uses a different version of AJV than Foal.

Foal v2 uses v6 of AJV. What version do `ajv-formats` use? If it's not v6, maybe you can downgrade it to a previous version that solve the issue.

Let me know how it goes.

**Comment by mohammaduvez** [comment]
[ajv-formats v0.2.0](https://github.com/ajv-validator/ajv-formats/blob/v0.2.0/package.json#L36) uses v6 of AJV, but that is WIP, can't use.
[ajv-formats from v0.3.0](https://github.com/ajv-validator/ajv-formats/blob/v0.3.0/package.json#L41) uses v7 of AJV.

**Comment by LoicPoullain** [comment]
This issue will be fixed in v3 where AJV has been upgraded to version 8.
