### ISSUE TITLE
Is there a reason for not typing `ValidateBody` `schema` argument?

### ISSUE THREAD

**Issue by ByScripts** [FoalTS/foal#999]
Hi FoalTS team.

When using the `@ValidateBody` decorator, I don't get TypeScript validation/completion, because the `schema` argument is typed as `object`:

```typescript
import { HookDecorator } from '../../core';

export declare function ValidateBody(schema: object | ((controller: any) => object), options?: {
    openapi?: boolean;
}): HookDecorator;
```

Is there any reason for it not being typed as `IApiSchema` (or another more suitable interface)?

```typescript
import { HookDecorator, IApiSchema } from '../../core';

export declare function ValidateBody(schema: IApiSchema | ((controller: any) => IApiSchema), options?: {
    openapi?: boolean;
}): HookDecorator;
```

For the moment, I'm using the `as` keyword:

```typescript
@ValidateBody({
    additionalProperties: false,
    properties: {
      text: { type: 'string' },
    },
    required: ['text'],
    type: 'object',
  } as IApiSchema)
```

Thank you.

**Comment by LoicPoullain** [comment]
Hi @ByScripts 👋 

`IApiSchema` is an OpenAPI schema whereas `@ValidateBody` expects a JSON schema. These two specifications are very similar but can be slightly different in some cases. In addition, AJV may allow you to add additional properties to the provided schema.

New versions of AJV support typing to define schemas. For backward compatibility, only the next major release of FoalTS will support AJV typing in the validate hooks.

**Comment by ByScripts** [comment]
Thank you for the explanation (and for the quick answer (and for FoalTS in general ^^))!
